global:
  # dev是开发模式，每个服端口不同，online是上线模式，每个服固定端口
  port_mode: dev
  log_path: "log/"
  config_path: "config/"
  reload_path: "status/"
  global_port_offset: 50000
  db_host: 127.0.0.1
  db_port: 3306
  db_user: root
  db_passwd: 'cys123456'
  enable_ssl: true
  # 分隔GameServer和CrossServer
  min_cross_server_id: 70

db_list:
  - name: db1
    host: 127.0.0.1
    port: 3306
    user: root
    passwd: 'cys123456'

server_list:
- name: game50
  type: game
  server_id: 50
  ip: 117.50.192.198
  area_id: 2
  area_name: "1-纽约"
  open_time: "2023-03-09 20:00:00"
  allow_login: 1
  enable_ssl: false
  state: free
  recommend_status: 0
  recommend_priority: 1
  cross_server_id: 70

- name: game55
  type: game
  server_id: 55
  ip: 117.50.192.198
  ssh_ip: 117.50.192.198
  area_id: 2
  area_name: "1-圣迭戈"
  open_time: "2023-06-03 20:00:00"
  allow_login: 1
  enable_ssl: true
  state: free
  recommend_status: 0
  recommend_priority: 1
  cross_server_id: 70

- name: game51
  type: game
  server_id: 51
  ip: 117.50.192.198
  area_id: 2
  area_name: "1-华盛顿"
  open_time: "2019-03-01 00:00:00"
  allow_login: 1
  enable_ssl: false
  state: free
  recommend_status: 0
  recommend_priority: 1
  cross_server_id: 70


- name: 策划1服
  type: game
  server_id: 61
  ip: 117.50.192.198
  area_id: 3
  area_name: "策划区"
  open_time: "2019-03-01 00:00:00"
  allow_login: 1
  enable_ssl: false
  state: free
  recommend_status: 0
  recommend_priority: 1
  cross_server_id: 70

- name: 跨服
  type: cross
  server_id: 70
  ip: 117.50.192.198

- name: cluster_router服
  type: cluster_router
  server_id: 2800
  ip: 117.50.192.198

- name: 世界服
  type: world
  server_id: 2801
  ip: 117.50.192.198

- name: gm服
  type: gm_router
  server_id: 2803
  ip: 117.50.192.198

- name: 登录服
  type: login
  server_id: 2810
  ip: 117.50.192.198
