---
--- Generated by Luanalysis
--- Created by linhe.
--- DateTime: 2023/6/7 上午9:56
---
local excel_data = require("excel_data")
local schema_game = require("schema_game")
local date = require "sys_utils.date"
local json = require("json")

-- 招募英雄
local recruit_hero_utils = DECLARE_MODULE("recruit_hero_utils")

function recruit_hero_utils:get_boozer()

end

