return {
    [ "add_final_hurt" ] = {
        [ "ch_key" ] = "最终增伤",
        [ "icon" ] = 190001,
        [ "id" ] = "add_final_hurt",
        [ "is_pct" ] = true,
        [ "name" ] = "最终增伤",
        [ "order" ] = 6,
    },
    [ "add_hurt" ] = {
        [ "ch_key" ] = "增伤",
        [ "icon" ] = 190001,
        [ "id" ] = "add_hurt",
        [ "is_pct" ] = true,
        [ "name" ] = "增伤",
        [ "order" ] = 8,
    },
    [ "anger_recover" ] = {
        [ "ch_key" ] = "怒气恢复",
        [ "icon" ] = 190001,
        [ "id" ] = "anger_recover",
        [ "name" ] = "怒气恢复",
        [ "order" ] = 20,
    },
    [ "att" ] = {
        [ "ch_key" ] = "攻击",
        [ "icon" ] = 190001,
        [ "id" ] = "att",
        [ "name" ] = "攻击",
        [ "order" ] = 24,
        [ "pct_attr" ] = "att_pct",
    },
    [ "att_pct" ] = {
        [ "ch_key" ] = "攻击百分比",
        [ "icon" ] = 190001,
        [ "id" ] = "att_pct",
        [ "is_pct" ] = true,
        [ "name" ] = "攻击",
        [ "order" ] = 15,
    },
    [ "business" ] = {
        [ "ch_key" ] = "商业",
        [ "city_income_item" ] = 101002,
        [ "city_income_item_rate" ] = 1,
        [ "id" ] = "business",
        [ "influence_item" ] = 101002,
        [ "is_role_attr" ] = true,
        [ "name" ] = "商业",
        [ "order" ] = 28,
        [ "other_add_role_attr" ] = true,
        [ "pct_attr" ] = "business_pct",
        [ "specialty_name" ] = "商业",
    },
    [ "business_pct" ] = {
        [ "ch_key" ] = "商业百分比",
        [ "id" ] = "business_pct",
        [ "is_pct" ] = true,
        [ "is_role_attr" ] = true,
        [ "name" ] = "商业",
        [ "order" ] = 19,
    },
    [ "charm" ] = {
        [ "ch_key" ] = "魅力",
        [ "icon" ] = 60003,
        [ "id" ] = "charm",
        [ "name" ] = "魅力",
        [ "order" ] = 2,
    },
    [ "crit" ] = {
        [ "ch_key" ] = "暴击",
        [ "icon" ] = 190001,
        [ "id" ] = "crit",
        [ "is_pct" ] = true,
        [ "name" ] = "暴击",
        [ "order" ] = 12,
    },
    [ "crit_def" ] = {
        [ "ch_key" ] = "抗暴",
        [ "icon" ] = 190001,
        [ "id" ] = "crit_def",
        [ "is_pct" ] = true,
        [ "name" ] = "抗暴",
        [ "order" ] = 11,
    },
    [ "culture" ] = {
        [ "ch_key" ] = "才艺",
        [ "icon" ] = 60002,
        [ "id" ] = "culture",
        [ "name" ] = "才艺",
        [ "order" ] = 3,
    },
    [ "def" ] = {
        [ "ch_key" ] = "防御",
        [ "icon" ] = 190001,
        [ "id" ] = "def",
        [ "name" ] = "防御",
        [ "order" ] = 22,
        [ "pct_attr" ] = "def_pct",
    },
    [ "def_pct" ] = {
        [ "ch_key" ] = "防御百分比",
        [ "icon" ] = 190001,
        [ "id" ] = "def_pct",
        [ "is_pct" ] = true,
        [ "name" ] = "防御",
        [ "order" ] = 13,
    },
    [ "etiquette" ] = {
        [ "ch_key" ] = "礼仪",
        [ "icon" ] = 60001,
        [ "id" ] = "etiquette",
        [ "name" ] = "礼仪",
        [ "order" ] = 4,
    },
    [ "fight" ] = {
        [ "ch_key" ] = "战斗",
        [ "id" ] = "fight",
        [ "is_role_attr" ] = true,
        [ "name" ] = "战斗",
        [ "order" ] = 25,
        [ "other_add_role_attr" ] = true,
        [ "pct_attr" ] = "fight_pct",
        [ "specialty_name" ] = "战斗",
    },
    [ "fight_pct" ] = {
        [ "ch_key" ] = "战斗百分比",
        [ "id" ] = "fight_pct",
        [ "is_pct" ] = true,
        [ "is_role_attr" ] = true,
        [ "name" ] = "战斗",
        [ "order" ] = 16,
    },
    [ "final_hurt_def" ] = {
        [ "ch_key" ] = "最终减伤",
        [ "icon" ] = 190001,
        [ "id" ] = "final_hurt_def",
        [ "is_pct" ] = true,
        [ "name" ] = "最终减伤",
        [ "order" ] = 5,
    },
    [ "hit" ] = {
        [ "ch_key" ] = "命中",
        [ "icon" ] = 190001,
        [ "id" ] = "hit",
        [ "is_pct" ] = true,
        [ "name" ] = "命中",
        [ "order" ] = 10,
    },
    [ "hurt_def" ] = {
        [ "ch_key" ] = "减伤",
        [ "icon" ] = 190001,
        [ "id" ] = "hurt_def",
        [ "is_pct" ] = true,
        [ "name" ] = "减伤",
        [ "order" ] = 7,
    },
    [ "init_anger" ] = {
        [ "ch_key" ] = "初始怒气",
        [ "icon" ] = 190001,
        [ "id" ] = "init_anger",
        [ "name" ] = "初始怒气",
        [ "order" ] = 21,
    },
    [ "management" ] = {
        [ "ch_key" ] = "管理",
        [ "city_income_item" ] = 101003,
        [ "city_income_item_rate" ] = 1,
        [ "id" ] = "management",
        [ "influence_item" ] = 101003,
        [ "is_role_attr" ] = true,
        [ "name" ] = "管理",
        [ "order" ] = 27,
        [ "other_add_role_attr" ] = true,
        [ "pct_attr" ] = "management_pct",
        [ "specialty_name" ] = "管理",
    },
    [ "management_pct" ] = {
        [ "ch_key" ] = "管理百分比",
        [ "id" ] = "management_pct",
        [ "is_pct" ] = true,
        [ "is_role_attr" ] = true,
        [ "name" ] = "管理",
        [ "order" ] = 18,
    },
    [ "max_hp" ] = {
        [ "ch_key" ] = "最大生命",
        [ "icon" ] = 190001,
        [ "id" ] = "max_hp",
        [ "name" ] = "血量",
        [ "order" ] = 23,
        [ "pct_attr" ] = "max_hp_pct",
    },
    [ "max_hp_pct" ] = {
        [ "ch_key" ] = "生命百分比",
        [ "icon" ] = 190001,
        [ "id" ] = "max_hp_pct",
        [ "is_pct" ] = true,
        [ "name" ] = "血量",
        [ "order" ] = 14,
    },
    [ "miss" ] = {
        [ "ch_key" ] = "闪避",
        [ "icon" ] = 190001,
        [ "id" ] = "miss",
        [ "is_pct" ] = true,
        [ "name" ] = "闪避",
        [ "order" ] = 9,
    },
    [ "planning" ] = {
        [ "ch_key" ] = "交际",
        [ "icon" ] = 60004,
        [ "id" ] = "planning",
        [ "name" ] = "交际",
        [ "order" ] = 1,
    },
    [ "renown" ] = {
        [ "ch_key" ] = "名望",
        [ "city_income_item" ] = 101004,
        [ "city_income_item_rate" ] = 1,
        [ "id" ] = "renown",
        [ "influence_item" ] = 101004,
        [ "is_role_attr" ] = true,
        [ "name" ] = "名望",
        [ "order" ] = 26,
        [ "other_add_role_attr" ] = true,
        [ "pct_attr" ] = "renown_pct",
        [ "specialty_name" ] = "名望",
    },
    [ "renown_pct" ] = {
        [ "ch_key" ] = "名望百分比",
        [ "id" ] = "renown_pct",
        [ "is_pct" ] = true,
        [ "is_role_attr" ] = true,
        [ "name" ] = "名望",
        [ "order" ] = 17,
    },
}