return {
    [ "ArenaUI" ] = {
        [ "battle_bg" ] = 2,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "ArenaUI",
        [ "is_random_bg" ] = true,
    },
    [ "CityStageUI" ] = {
        [ "battle_bg" ] = 3,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "have_count_down" ] = true,
        [ "id" ] = "CityStageUI",
    },
    [ "DaliyBattleUI" ] = {
        [ "battle_bg" ] = 4,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "have_count_down" ] = true,
        [ "id" ] = "DaliyBattleUI",
    },
    [ "DareTowerUI" ] = {
        [ "battle_bg" ] = 5,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "have_count_down" ] = true,
        [ "id" ] = "DareTowerUI",
    },
    [ "DynastyBuildingUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "DynastyBuildingUI",
    },
    [ "DynastyChallengeUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "DynastyChallengeUI",
    },
    [ "ExperimentUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "ExperimentUI",
    },
    [ "FriendUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "FriendUI",
    },
    [ "GuideUI" ] = {
        [ "battle_bg" ] = 1,
        [ "can_change_speed" ] = false,
        [ "can_skip" ] = false,
        [ "id" ] = "GuideUI",
    },
    [ "SelectGrabPlayerUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "SelectGrabPlayerUI",
        [ "is_random_bg" ] = true,
    },
    [ "TraitorBossUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "TraitorBossUI",
        [ "skip_lock_id" ] = 52,
    },
    [ "TraitorInfoUI" ] = {
        [ "battle_bg" ] = 6,
        [ "can_change_speed" ] = true,
        [ "can_skip" ] = true,
        [ "id" ] = "TraitorInfoUI",
    },
}