return {
    [ 0 ] = {
        [ "boy_dialog" ] = 1,
        [ "cooldown" ] = 3600,
        [ "depict" ] = "襁褓/抓周",
        [ "exp" ] = 1,
        [ "girl_dialog" ] = 2,
        [ "level" ] = 0,
        [ "total_exp" ] = 0,
        [ "vitality_limit" ] = 1,
    },
    [ 1 ] = {
        [ "boy_dialog" ] = 3,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "1",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 4,
        [ "level" ] = 1,
        [ "total_exp" ] = 0,
        [ "vitality_limit" ] = 3,
    },
    [ 2 ] = {
        [ "boy_dialog" ] = 3,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "2",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 4,
        [ "level" ] = 2,
        [ "total_exp" ] = 2,
        [ "vitality_limit" ] = 3,
    },
    [ 3 ] = {
        [ "boy_dialog" ] = 3,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "3",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 4,
        [ "level" ] = 3,
        [ "total_exp" ] = 4,
        [ "vitality_limit" ] = 3,
    },
    [ 4 ] = {
        [ "boy_dialog" ] = 3,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "4",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 4,
        [ "level" ] = 4,
        [ "total_exp" ] = 6,
        [ "vitality_limit" ] = 3,
    },
    [ 5 ] = {
        [ "boy_dialog" ] = 3,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "5",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 4,
        [ "level" ] = 5,
        [ "total_exp" ] = 8,
        [ "vitality_limit" ] = 3,
    },
    [ 6 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "6",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 6,
        [ "total_exp" ] = 10,
        [ "vitality_limit" ] = 3,
    },
    [ 7 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "7",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 7,
        [ "total_exp" ] = 12,
        [ "vitality_limit" ] = 3,
    },
    [ 8 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "8",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 8,
        [ "total_exp" ] = 14,
        [ "vitality_limit" ] = 3,
    },
    [ 9 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "9",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 9,
        [ "total_exp" ] = 16,
        [ "vitality_limit" ] = 3,
    },
    [ 10 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "10",
        [ "exp" ] = 2,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 10,
        [ "total_exp" ] = 18,
        [ "vitality_limit" ] = 3,
    },
    [ 11 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "11",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 11,
        [ "total_exp" ] = 20,
        [ "vitality_limit" ] = 3,
    },
    [ 12 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "12",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 12,
        [ "total_exp" ] = 23,
        [ "vitality_limit" ] = 3,
    },
    [ 13 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "13",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 13,
        [ "total_exp" ] = 26,
        [ "vitality_limit" ] = 3,
    },
    [ 14 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "14",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 14,
        [ "total_exp" ] = 29,
        [ "vitality_limit" ] = 3,
    },
    [ 15 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "15",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 15,
        [ "total_exp" ] = 32,
        [ "vitality_limit" ] = 3,
    },
    [ 16 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "16",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 16,
        [ "total_exp" ] = 35,
        [ "vitality_limit" ] = 3,
    },
    [ 17 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "17",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 17,
        [ "total_exp" ] = 38,
        [ "vitality_limit" ] = 3,
    },
    [ 18 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "18",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 18,
        [ "total_exp" ] = 41,
        [ "vitality_limit" ] = 3,
    },
    [ 19 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "19",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 19,
        [ "total_exp" ] = 44,
        [ "vitality_limit" ] = 3,
    },
    [ 20 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "20",
        [ "exp" ] = 3,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 20,
        [ "total_exp" ] = 47,
        [ "vitality_limit" ] = 3,
    },
    [ 21 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "21",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 21,
        [ "total_exp" ] = 50,
        [ "vitality_limit" ] = 3,
    },
    [ 22 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "22",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 22,
        [ "total_exp" ] = 54,
        [ "vitality_limit" ] = 3,
    },
    [ 23 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "23",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 23,
        [ "total_exp" ] = 58,
        [ "vitality_limit" ] = 3,
    },
    [ 24 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "24",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 24,
        [ "total_exp" ] = 62,
        [ "vitality_limit" ] = 3,
    },
    [ 25 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "25",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 25,
        [ "total_exp" ] = 66,
        [ "vitality_limit" ] = 3,
    },
    [ 26 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "26",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 26,
        [ "total_exp" ] = 70,
        [ "vitality_limit" ] = 3,
    },
    [ 27 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "27",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 27,
        [ "total_exp" ] = 74,
        [ "vitality_limit" ] = 3,
    },
    [ 28 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "28",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 28,
        [ "total_exp" ] = 78,
        [ "vitality_limit" ] = 3,
    },
    [ 29 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "29",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 29,
        [ "total_exp" ] = 82,
        [ "vitality_limit" ] = 3,
    },
    [ 30 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "30",
        [ "exp" ] = 4,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 30,
        [ "total_exp" ] = 86,
        [ "vitality_limit" ] = 3,
    },
    [ 31 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "31",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 31,
        [ "total_exp" ] = 90,
        [ "vitality_limit" ] = 3,
    },
    [ 32 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "32",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 32,
        [ "total_exp" ] = 95,
        [ "vitality_limit" ] = 3,
    },
    [ 33 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "33",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 33,
        [ "total_exp" ] = 100,
        [ "vitality_limit" ] = 3,
    },
    [ 34 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "34",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 34,
        [ "total_exp" ] = 105,
        [ "vitality_limit" ] = 3,
    },
    [ 35 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "35",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 35,
        [ "total_exp" ] = 110,
        [ "vitality_limit" ] = 3,
    },
    [ 36 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "36",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 36,
        [ "total_exp" ] = 115,
        [ "vitality_limit" ] = 3,
    },
    [ 37 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "37",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 37,
        [ "total_exp" ] = 120,
        [ "vitality_limit" ] = 3,
    },
    [ 38 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "38",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 38,
        [ "total_exp" ] = 125,
        [ "vitality_limit" ] = 3,
    },
    [ 39 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "39",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 39,
        [ "total_exp" ] = 130,
        [ "vitality_limit" ] = 3,
    },
    [ 40 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "40",
        [ "exp" ] = 5,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 40,
        [ "total_exp" ] = 135,
        [ "vitality_limit" ] = 3,
    },
    [ 41 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "41",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 41,
        [ "total_exp" ] = 140,
        [ "vitality_limit" ] = 3,
    },
    [ 42 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "42",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 42,
        [ "total_exp" ] = 146,
        [ "vitality_limit" ] = 3,
    },
    [ 43 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "43",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 43,
        [ "total_exp" ] = 152,
        [ "vitality_limit" ] = 3,
    },
    [ 44 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "44",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 44,
        [ "total_exp" ] = 158,
        [ "vitality_limit" ] = 3,
    },
    [ 45 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "45",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 45,
        [ "total_exp" ] = 164,
        [ "vitality_limit" ] = 3,
    },
    [ 46 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "46",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 46,
        [ "total_exp" ] = 170,
        [ "vitality_limit" ] = 3,
    },
    [ 47 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "47",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 47,
        [ "total_exp" ] = 176,
        [ "vitality_limit" ] = 3,
    },
    [ 48 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "48",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 48,
        [ "total_exp" ] = 182,
        [ "vitality_limit" ] = 3,
    },
    [ 49 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "49",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 49,
        [ "total_exp" ] = 188,
        [ "vitality_limit" ] = 3,
    },
    [ 50 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "50",
        [ "exp" ] = 6,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 50,
        [ "total_exp" ] = 194,
        [ "vitality_limit" ] = 3,
    },
    [ 51 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "51",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 51,
        [ "total_exp" ] = 200,
        [ "vitality_limit" ] = 3,
    },
    [ 52 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "52",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 52,
        [ "total_exp" ] = 207,
        [ "vitality_limit" ] = 3,
    },
    [ 53 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "53",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 53,
        [ "total_exp" ] = 214,
        [ "vitality_limit" ] = 3,
    },
    [ 54 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "54",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 54,
        [ "total_exp" ] = 221,
        [ "vitality_limit" ] = 3,
    },
    [ 55 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "55",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 55,
        [ "total_exp" ] = 228,
        [ "vitality_limit" ] = 3,
    },
    [ 56 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "56",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 56,
        [ "total_exp" ] = 235,
        [ "vitality_limit" ] = 3,
    },
    [ 57 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "57",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 57,
        [ "total_exp" ] = 242,
        [ "vitality_limit" ] = 3,
    },
    [ 58 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "58",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 58,
        [ "total_exp" ] = 249,
        [ "vitality_limit" ] = 3,
    },
    [ 59 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "59",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 59,
        [ "total_exp" ] = 256,
        [ "vitality_limit" ] = 3,
    },
    [ 60 ] = {
        [ "boy_dialog" ] = 5,
        [ "cooldown" ] = 7200,
        [ "depict" ] = "60",
        [ "exp" ] = 7,
        [ "girl_dialog" ] = 6,
        [ "level" ] = 60,
        [ "total_exp" ] = 263,
        [ "vitality_limit" ] = 3,
    },
}