return {
    [ 1 ] = {
        [ "add_luck" ] = 0,
        [ "crit_rate1" ] = 0.2,
        [ "crit_rate2" ] = 0.1,
        [ "each_exp" ] = 3,
        [ "exp" ] = 80,
        [ "init_rate" ] = 1,
        [ "level" ] = 1,
        [ "luck_limit" ] = 0,
        [ "total_exp" ] = 80,
    },
    [ 2 ] = {
        [ "add_luck" ] = 150,
        [ "crit_rate1" ] = 0.2,
        [ "crit_rate2" ] = 0.1,
        [ "each_exp" ] = 5,
        [ "exp" ] = 80,
        [ "init_rate" ] = 0.8,
        [ "level" ] = 2,
        [ "luck_limit" ] = 750,
        [ "total_exp" ] = 160,
    },
    [ 3 ] = {
        [ "add_luck" ] = 150,
        [ "crit_rate1" ] = 0.2,
        [ "crit_rate2" ] = 0.1,
        [ "each_exp" ] = 6,
        [ "exp" ] = 200,
        [ "init_rate" ] = 0.4,
        [ "level" ] = 3,
        [ "luck_limit" ] = 1500,
        [ "total_exp" ] = 360,
    },
    [ 4 ] = {
        [ "add_luck" ] = 150,
        [ "crit_rate1" ] = 0.2,
        [ "crit_rate2" ] = 0.1,
        [ "each_exp" ] = 12,
        [ "exp" ] = 480,
        [ "init_rate" ] = 0.3,
        [ "level" ] = 4,
        [ "luck_limit" ] = 3000,
        [ "total_exp" ] = 840,
    },
    [ 5 ] = {
        [ "add_luck" ] = 150,
        [ "crit_rate1" ] = 0.2,
        [ "crit_rate2" ] = 0.1,
        [ "each_exp" ] = 20,
        [ "exp" ] = 960,
        [ "init_rate" ] = 0.2,
        [ "level" ] = 5,
        [ "luck_limit" ] = 6000,
        [ "total_exp" ] = 1800,
    },
}