return {
    [ 1 ] = {
        [ "ch_key" ] = "武器",
        [ "id" ] = 1,
        [ "name" ] = "武器",
        [ "part_type" ] = 1,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 15,
    },
    [ 2 ] = {
        [ "ch_key" ] = "头盔",
        [ "id" ] = 2,
        [ "name" ] = "头盔",
        [ "part_type" ] = 1,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 15,
    },
    [ 3 ] = {
        [ "ch_key" ] = "腰带",
        [ "id" ] = 3,
        [ "name" ] = "腰带",
        [ "part_type" ] = 1,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 20,
    },
    [ 4 ] = {
        [ "ch_key" ] = "衣服",
        [ "id" ] = 4,
        [ "name" ] = "衣服",
        [ "part_type" ] = 1,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 20,
    },
    [ 5 ] = {
        [ "ch_key" ] = "攻击宝物",
        [ "id" ] = 5,
        [ "name" ] = "攻击宝物",
        [ "part_type" ] = 2,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 28,
    },
    [ 6 ] = {
        [ "ch_key" ] = "防御宝物",
        [ "id" ] = 6,
        [ "name" ] = "防御宝物",
        [ "part_type" ] = 2,
        [ "show_level" ] = 5,
        [ "unlock_level" ] = 28,
    },
}