return {
    [ 1 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "凶相毕露",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602006,
        [ "id" ] = 1,
        [ "name" ] = "凶相毕露",
        [ "type" ] = 2,
    },
    [ 2 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "恶龙伟力",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602007,
        [ "id" ] = 2,
        [ "name" ] = "恶龙伟力",
        [ "type" ] = 2,
    },
    [ 3 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "摩羯庇佑",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602014,
        [ "id" ] = 3,
        [ "name" ] = "摩羯庇佑",
        [ "type" ] = 2,
    },
    [ 4 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "地狱意志",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602015,
        [ "id" ] = 4,
        [ "name" ] = "冥界意志",
        [ "type" ] = 2,
    },
    [ 5 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "不洁信仰",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602004,
        [ "id" ] = 5,
        [ "name" ] = "不洁信仰",
        [ "type" ] = 2,
    },
    [ 6 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "不息之风",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602005,
        [ "id" ] = 6,
        [ "name" ] = "不息之风",
        [ "type" ] = 2,
    },
    [ 7 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "狂躁灵魂",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602012,
        [ "id" ] = 7,
        [ "name" ] = "狂躁灵魂",
        [ "type" ] = 2,
    },
    [ 8 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "堕落之心",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602013,
        [ "id" ] = 8,
        [ "name" ] = "堕落之心",
        [ "type" ] = 2,
    },
    [ 9 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "阴影凶心",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602002,
        [ "id" ] = 9,
        [ "name" ] = "阴影凶心",
        [ "type" ] = 2,
    },
    [ 10 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "凶眸之灾",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602003,
        [ "id" ] = 10,
        [ "name" ] = "凶眸之灾",
        [ "type" ] = 2,
    },
    [ 11 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "怪物凶性",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602010,
        [ "id" ] = 11,
        [ "name" ] = "怪物凶性",
        [ "type" ] = 2,
    },
    [ 12 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "无人宽恕",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 602011,
        [ "id" ] = 12,
        [ "name" ] = "无人宽恕",
        [ "type" ] = 2,
    },
    [ 13 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "地狱常客",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601052,
        [ "id" ] = 13,
        [ "name" ] = "底下常客",
        [ "type" ] = 2,
    },
    [ 14 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "罪恶滔天",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601053,
        [ "id" ] = 14,
        [ "name" ] = "罪行滔天",
        [ "type" ] = 2,
    },
    [ 15 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "亡命暴徒",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601040,
        [ "id" ] = 15,
        [ "name" ] = "亡命凶徒",
        [ "type" ] = 2,
    },
    [ 16 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "死神象征",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601044,
        [ "id" ] = 16,
        [ "name" ] = "死神象征",
        [ "type" ] = 2,
    },
    [ 17 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "恶魔雄心",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601048,
        [ "id" ] = 17,
        [ "name" ] = "恶魔雄心",
        [ "type" ] = 2,
    },
    [ 18 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "流亡之怒",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601041,
        [ "id" ] = 18,
        [ "name" ] = "流亡之怒",
        [ "type" ] = 2,
    },
    [ 19 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "厄运将至",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601045,
        [ "id" ] = 19,
        [ "name" ] = "厄运将至",
        [ "type" ] = 2,
    },
    [ 20 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "穷凶极恶",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601049,
        [ "id" ] = 20,
        [ "name" ] = "穷凶极恶",
        [ "type" ] = 2,
    },
    [ 21 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "凶恶成性",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601028,
        [ "id" ] = 21,
        [ "name" ] = "凶恶成性",
        [ "type" ] = 2,
    },
    [ 22 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "满手血腥",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601032,
        [ "id" ] = 22,
        [ "name" ] = "满手血腥",
        [ "type" ] = 2,
    },
    [ 23 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "贪得无厌",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601036,
        [ "id" ] = 23,
        [ "name" ] = "贪得无厌",
        [ "type" ] = 2,
    },
    [ 24 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暴力信仰",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601029,
        [ "id" ] = 24,
        [ "name" ] = "武力信仰",
        [ "type" ] = 2,
    },
    [ 25 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "无情凶心",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601033,
        [ "id" ] = 25,
        [ "name" ] = "无情凶心",
        [ "type" ] = 2,
    },
    [ 26 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "max_hp_pct",
            [ 2 ] = "att_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "吞象野心",
        [ "desc" ] = "穿戴%s时，%s增加%s,%s增加%s",
        [ "fate_item" ] = 601037,
        [ "id" ] = 26,
        [ "name" ] = "吞象野心",
        [ "type" ] = 2,
    },
    [ 27 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "强权联盟",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11011,
        [ "id" ] = 27,
        [ "name" ] = "强权联盟",
        [ "type" ] = 1,
    },
    [ 28 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "得力副手",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11061,
        [ "id" ] = 28,
        [ "name" ] = "得力副手",
        [ "type" ] = 1,
    },
    [ 29 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "重拳出击",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12051,
        [ "id" ] = 29,
        [ "name" ] = "重拳出击",
        [ "type" ] = 1,
    },
    [ 30 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "绝佳棋子",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11041,
        [ "id" ] = 30,
        [ "name" ] = "绝佳棋子",
        [ "type" ] = 1,
    },
    [ 31 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "钢铁凶心",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11021,
        [ "id" ] = 31,
        [ "name" ] = "钢铁凶心",
        [ "type" ] = 1,
    },
    [ 32 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "勉为其难",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11041,
        [ "id" ] = 32,
        [ "name" ] = "勉为其难",
        [ "type" ] = 1,
    },
    [ 33 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "寸土必争",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 33,
        [ "name" ] = "寸土必争",
        [ "type" ] = 1,
    },
    [ 34 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "堕落正义",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 34,
        [ "name" ] = "堕落正义",
        [ "type" ] = 1,
    },
    [ 35 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "冷酷盟友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11021,
        [ "id" ] = 35,
        [ "name" ] = "冷酷盟友",
        [ "type" ] = 1,
    },
    [ 36 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暧昧不清",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 36,
        [ "name" ] = "暧昧不清",
        [ "type" ] = 1,
    },
    [ 37 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "黑名单",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12042,
        [ "id" ] = 37,
        [ "name" ] = "黑名单",
        [ "type" ] = 1,
    },
    [ 38 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "共同目标",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11012,
        [ "id" ] = 38,
        [ "name" ] = "共同目标",
        [ "type" ] = 1,
    },
    [ 39 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "脆弱搭档",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11011,
        [ "id" ] = 39,
        [ "name" ] = "脆弱搭档",
        [ "type" ] = 1,
    },
    [ 40 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "医患关系",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11061,
        [ "id" ] = 40,
        [ "name" ] = "医患关系",
        [ "type" ] = 1,
    },
    [ 41 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "佣兵生涯",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 41,
        [ "name" ] = "佣兵生涯",
        [ "type" ] = 1,
    },
    [ 42 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "救命恩人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11012,
        [ "id" ] = 42,
        [ "name" ] = "救命恩人",
        [ "type" ] = 1,
    },
    [ 43 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "带刺玫瑰",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 43,
        [ "name" ] = "带刺玫瑰",
        [ "type" ] = 1,
    },
    [ 44 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "英国旧识",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11061,
        [ "id" ] = 44,
        [ "name" ] = "英国旧识",
        [ "type" ] = 1,
    },
    [ 45 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "远东友人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 45,
        [ "name" ] = "远东友人",
        [ "type" ] = 1,
    },
    [ 46 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "生意对手",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11042,
        [ "id" ] = 46,
        [ "name" ] = "生意对手",
        [ "type" ] = 1,
    },
    [ 47 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "黑道闺蜜",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 47,
        [ "name" ] = "帮组闺蜜",
        [ "type" ] = 1,
    },
    [ 48 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "残酷疗法",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11041,
        [ "id" ] = 48,
        [ "name" ] = "残酷疗法",
        [ "type" ] = 1,
    },
    [ 49 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "师出同门",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 49,
        [ "name" ] = "师出同门",
        [ "type" ] = 1,
    },
    [ 50 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "冷血黑道",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11032,
        [ "id" ] = 50,
        [ "name" ] = "冷血帮组",
        [ "type" ] = 1,
    },
    [ 51 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "美女与野兽",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11012,
        [ "id" ] = 51,
        [ "name" ] = "美女与野兽",
        [ "type" ] = 1,
    },
    [ 52 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "水火不容",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 52,
        [ "name" ] = "水火不容",
        [ "type" ] = 1,
    },
    [ 53 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "恶行累累",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14041,
        [ "id" ] = 53,
        [ "name" ] = "恶行累累",
        [ "type" ] = 1,
    },
    [ 54 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暴力信徒",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11052,
        [ "id" ] = 54,
        [ "name" ] = "武力信徒",
        [ "type" ] = 1,
    },
    [ 55 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "暂时合作",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11062,
        [ "id" ] = 55,
        [ "name" ] = "暂时合作",
        [ "type" ] = 1,
    },
    [ 56 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "喋血玫瑰",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 56,
        [ "name" ] = "喋血玫瑰",
        [ "type" ] = 1,
    },
    [ 57 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "复仇之心",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 57,
        [ "name" ] = "复仇之心",
        [ "type" ] = 1,
    },
    [ 58 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "孤注一掷",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11022,
        [ "id" ] = 58,
        [ "name" ] = "孤注一掷",
        [ "type" ] = 1,
    },
    [ 59 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "双生恶犬",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11032,
        [ "id" ] = 59,
        [ "name" ] = "双生恶犬",
        [ "type" ] = 1,
    },
    [ 60 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "老朋友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11061,
        [ "id" ] = 60,
        [ "name" ] = "老朋友",
        [ "type" ] = 1,
    },
    [ 61 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "战场旧识",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 61,
        [ "name" ] = "战场旧识",
        [ "type" ] = 1,
    },
    [ 62 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "恶棍义气",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11062,
        [ "id" ] = 62,
        [ "name" ] = "恶棍义气",
        [ "type" ] = 1,
    },
    [ 63 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "罪恶挚友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11042,
        [ "id" ] = 63,
        [ "name" ] = "罪恶挚友",
        [ "type" ] = 1,
    },
    [ 64 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "非法生意",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 64,
        [ "name" ] = "非法生意",
        [ "type" ] = 1,
    },
    [ 65 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "一面之缘",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 65,
        [ "name" ] = "一面之缘",
        [ "type" ] = 1,
    },
    [ 66 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "帮派宿敌",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11012,
        [ "id" ] = 66,
        [ "name" ] = "帮派宿敌",
        [ "type" ] = 1,
    },
    [ 67 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "亡命之花",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14051,
        [ "id" ] = 67,
        [ "name" ] = "亡命之花",
        [ "type" ] = 1,
    },
    [ 68 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "黑帮小姐",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 68,
        [ "name" ] = "帮组小姐",
        [ "type" ] = 1,
    },
    [ 69 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "冷血姐妹",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 69,
        [ "name" ] = "冷血姐妹",
        [ "type" ] = 1,
    },
    [ 70 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "格斗达人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11042,
        [ "id" ] = 70,
        [ "name" ] = "格斗达人",
        [ "type" ] = 1,
    },
    [ 71 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "致命伤疤",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11062,
        [ "id" ] = 71,
        [ "name" ] = "致命伤疤",
        [ "type" ] = 1,
    },
    [ 72 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "共同信仰",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11041,
        [ "id" ] = 72,
        [ "name" ] = "共同信仰",
        [ "type" ] = 1,
    },
    [ 73 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "危险同行",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 73,
        [ "name" ] = "危险同行",
        [ "type" ] = 1,
    },
    [ 74 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "凶恶猎犬",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11032,
        [ "id" ] = 74,
        [ "name" ] = "凶恶猎犬",
        [ "type" ] = 1,
    },
    [ 75 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "帮派砥柱",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12061,
        [ "id" ] = 75,
        [ "name" ] = "帮派砥柱",
        [ "type" ] = 1,
    },
    [ 76 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "不义之盟",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12022,
        [ "id" ] = 76,
        [ "name" ] = "不义之盟",
        [ "type" ] = 1,
    },
    [ 77 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "杀手本能",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13062,
        [ "id" ] = 77,
        [ "name" ] = "杀手本能",
        [ "type" ] = 1,
    },
    [ 78 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "互有输赢",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12042,
        [ "id" ] = 78,
        [ "name" ] = "互有输赢",
        [ "type" ] = 1,
    },
    [ 79 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "屠夫直感",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12051,
        [ "id" ] = 79,
        [ "name" ] = "屠夫直感",
        [ "type" ] = 1,
    },
    [ 80 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "各怀鬼胎",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12042,
        [ "id" ] = 80,
        [ "name" ] = "各怀鬼胎",
        [ "type" ] = 1,
    },
    [ 81 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "冤家路窄",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 81,
        [ "name" ] = "冤家路窄",
        [ "type" ] = 1,
    },
    [ 82 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "辉煌过往",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 82,
        [ "name" ] = "辉煌过往",
        [ "type" ] = 1,
    },
    [ 83 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "可靠盟友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12051,
        [ "id" ] = 83,
        [ "name" ] = "可靠盟友",
        [ "type" ] = 1,
    },
    [ 84 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "各取所需",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 84,
        [ "name" ] = "各取所需",
        [ "type" ] = 1,
    },
    [ 85 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "危险伙伴",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13041,
        [ "id" ] = 85,
        [ "name" ] = "危险伙伴",
        [ "type" ] = 1,
    },
    [ 86 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暗箱操作",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12032,
        [ "id" ] = 86,
        [ "name" ] = "暗箱操作",
        [ "type" ] = 1,
    },
    [ 87 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "互相利用",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12061,
        [ "id" ] = 87,
        [ "name" ] = "互相利用",
        [ "type" ] = 1,
    },
    [ 88 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "杀手软肋",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12022,
        [ "id" ] = 88,
        [ "name" ] = "杀手软肋",
        [ "type" ] = 1,
    },
    [ 89 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "向往自由",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 89,
        [ "name" ] = "向往自由",
        [ "type" ] = 1,
    },
    [ 90 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "铤而走险",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12032,
        [ "id" ] = 90,
        [ "name" ] = "铤而走险",
        [ "type" ] = 1,
    },
    [ 91 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "铁锤外交",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 91,
        [ "name" ] = "铁锤外交",
        [ "type" ] = 1,
    },
    [ 92 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "公平交易",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12022,
        [ "id" ] = 92,
        [ "name" ] = "公平交易",
        [ "type" ] = 1,
    },
    [ 93 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "沉默野兽",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 93,
        [ "name" ] = "沉默野兽",
        [ "type" ] = 1,
    },
    [ 94 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "绅士与铁匠",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12021,
        [ "id" ] = 94,
        [ "name" ] = "绅士与铁匠",
        [ "type" ] = 1,
    },
    [ 95 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "重锤出击",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 95,
        [ "name" ] = "重锤出击",
        [ "type" ] = 1,
    },
    [ 96 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "刺杀之恨",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12042,
        [ "id" ] = 96,
        [ "name" ] = "刺杀之恨",
        [ "type" ] = 1,
    },
    [ 97 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "伦敦血战",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 97,
        [ "name" ] = "伦敦血战",
        [ "type" ] = 1,
    },
    [ 98 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "雅俗偏见",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12041,
        [ "id" ] = 98,
        [ "name" ] = "雅俗偏见",
        [ "type" ] = 1,
    },
    [ 99 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "胆大妄为",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12032,
        [ "id" ] = 99,
        [ "name" ] = "胆大妄为",
        [ "type" ] = 1,
    },
    [ 100 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "冷血莽夫",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 100,
        [ "name" ] = "冷血莽夫",
        [ "type" ] = 1,
    },
    [ 101 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "技巧与蛮力",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 101,
        [ "name" ] = "技巧与蛮力",
        [ "type" ] = 1,
    },
    [ 102 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "清理门户",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12041,
        [ "id" ] = 102,
        [ "name" ] = "清理门户",
        [ "type" ] = 1,
    },
    [ 103 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "大干一票",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12011,
        [ "id" ] = 103,
        [ "name" ] = "大干一票",
        [ "type" ] = 1,
    },
    [ 104 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "通缉犯",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 104,
        [ "name" ] = "通缉犯",
        [ "type" ] = 1,
    },
    [ 105 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "分道扬镳",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 105,
        [ "name" ] = "分道扬镳",
        [ "type" ] = 1,
    },
    [ 106 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "阴暗过往",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12052,
        [ "id" ] = 106,
        [ "name" ] = "阴暗过往",
        [ "type" ] = 1,
    },
    [ 107 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "雾都黑幕",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12062,
        [ "id" ] = 107,
        [ "name" ] = "雾都黑幕",
        [ "type" ] = 1,
    },
    [ 108 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "相识恨晚",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12022,
        [ "id" ] = 108,
        [ "name" ] = "相识恨晚",
        [ "type" ] = 1,
    },
    [ 109 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "西部对决",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 109,
        [ "name" ] = "西部对决",
        [ "type" ] = 1,
    },
    [ 110 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "横行无阻",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12011,
        [ "id" ] = 110,
        [ "name" ] = "横行无阻",
        [ "type" ] = 1,
    },
    [ 111 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "冠冕堂皇",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12021,
        [ "id" ] = 111,
        [ "name" ] = "冠冕堂皇",
        [ "type" ] = 1,
    },
    [ 112 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "阴险对手",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 112,
        [ "name" ] = "阴险对手",
        [ "type" ] = 1,
    },
    [ 113 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "谈笑风生",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 113,
        [ "name" ] = "谈笑风生",
        [ "type" ] = 1,
    },
    [ 114 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "屡教不改",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12032,
        [ "id" ] = 114,
        [ "name" ] = "屡教不改",
        [ "type" ] = 1,
    },
    [ 115 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "艺术家",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12052,
        [ "id" ] = 115,
        [ "name" ] = "艺术家",
        [ "type" ] = 1,
    },
    [ 116 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "无法地带",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 116,
        [ "name" ] = "无法地带",
        [ "type" ] = 1,
    },
    [ 117 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "绅士淑女",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 117,
        [ "name" ] = "绅士淑女",
        [ "type" ] = 1,
    },
    [ 118 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "虚伪绅士",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12021,
        [ "id" ] = 118,
        [ "name" ] = "虚伪绅士",
        [ "type" ] = 1,
    },
    [ 119 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "凶恶艺术",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12041,
        [ "id" ] = 119,
        [ "name" ] = "凶恶艺术",
        [ "type" ] = 1,
    },
    [ 120 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "铁石心肠",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12042,
        [ "id" ] = 120,
        [ "name" ] = "铁石心肠",
        [ "type" ] = 1,
    },
    [ 121 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "摇滚拥泵",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 121,
        [ "name" ] = "摇滚拥泵",
        [ "type" ] = 1,
    },
    [ 122 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "生存之道",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12062,
        [ "id" ] = 122,
        [ "name" ] = "生存之道",
        [ "type" ] = 1,
    },
    [ 123 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "般若鬼面",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13062,
        [ "id" ] = 123,
        [ "name" ] = "般若鬼面",
        [ "type" ] = 1,
    },
    [ 124 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "浪客仁心",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13032,
        [ "id" ] = 124,
        [ "name" ] = "浪客仁心",
        [ "type" ] = 1,
    },
    [ 125 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "王牌对决",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14021,
        [ "id" ] = 125,
        [ "name" ] = "王牌对决",
        [ "type" ] = 1,
    },
    [ 126 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "武者风采",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13041,
        [ "id" ] = 126,
        [ "name" ] = "武者风采",
        [ "type" ] = 1,
    },
    [ 127 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "战功赫赫",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13012,
        [ "id" ] = 127,
        [ "name" ] = "战功赫赫",
        [ "type" ] = 1,
    },
    [ 128 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "南亚霸主",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13041,
        [ "id" ] = 128,
        [ "name" ] = "南亚霸主",
        [ "type" ] = 1,
    },
    [ 129 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "火力压制",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 129,
        [ "name" ] = "火力压制",
        [ "type" ] = 1,
    },
    [ 130 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "生意伙伴",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 130,
        [ "name" ] = "生意伙伴",
        [ "type" ] = 1,
    },
    [ 131 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "特殊病人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13012,
        [ "id" ] = 131,
        [ "name" ] = "特殊病人",
        [ "type" ] = 1,
    },
    [ 132 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "过命交情",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 132,
        [ "name" ] = "过命交情",
        [ "type" ] = 1,
    },
    [ 133 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "危险患者",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14042,
        [ "id" ] = 133,
        [ "name" ] = "危险患者",
        [ "type" ] = 1,
    },
    [ 134 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "奇异体质",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13021,
        [ "id" ] = 134,
        [ "name" ] = "奇异体质",
        [ "type" ] = 1,
    },
    [ 135 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "致命武力",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13062,
        [ "id" ] = 135,
        [ "name" ] = "致命武力",
        [ "type" ] = 1,
    },
    [ 136 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "虚伪友谊",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13032,
        [ "id" ] = 136,
        [ "name" ] = "虚伪友谊",
        [ "type" ] = 1,
    },
    [ 137 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "一见钟情",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 137,
        [ "name" ] = "一见钟情",
        [ "type" ] = 1,
    },
    [ 138 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "拳脚专家",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13021,
        [ "id" ] = 138,
        [ "name" ] = "拳脚专家",
        [ "type" ] = 1,
    },
    [ 139 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "异国伙伴",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 139,
        [ "name" ] = "异国伙伴",
        [ "type" ] = 1,
    },
    [ 140 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "涌泉相报",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13032,
        [ "id" ] = 140,
        [ "name" ] = "涌泉相报",
        [ "type" ] = 1,
    },
    [ 141 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "往日上级",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 141,
        [ "name" ] = "往日上级",
        [ "type" ] = 1,
    },
    [ 142 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "爆破者",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13052,
        [ "id" ] = 142,
        [ "name" ] = "爆破者",
        [ "type" ] = 1,
    },
    [ 143 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "联合忍道",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 143,
        [ "name" ] = "联合忍道",
        [ "type" ] = 1,
    },
    [ 144 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "忍者克星",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13041,
        [ "id" ] = 144,
        [ "name" ] = "忍者克星",
        [ "type" ] = 1,
    },
    [ 145 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "剑道同行",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 145,
        [ "name" ] = "剑道同行",
        [ "type" ] = 1,
    },
    [ 146 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "野性难驯",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13051,
        [ "id" ] = 146,
        [ "name" ] = "野性难驯",
        [ "type" ] = 1,
    },
    [ 147 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "功夫达人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13021,
        [ "id" ] = 147,
        [ "name" ] = "功夫达人",
        [ "type" ] = 1,
    },
    [ 148 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "以柔克刚",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 148,
        [ "name" ] = "以柔克刚",
        [ "type" ] = 1,
    },
    [ 149 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "重归于好",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 149,
        [ "name" ] = "重归于好",
        [ "type" ] = 1,
    },
    [ 150 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "师门故人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13042,
        [ "id" ] = 150,
        [ "name" ] = "师门故人",
        [ "type" ] = 1,
    },
    [ 151 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "华夏血脉",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13022,
        [ "id" ] = 151,
        [ "name" ] = "华夏血脉",
        [ "type" ] = 1,
    },
    [ 152 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "东亚世仇",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 152,
        [ "name" ] = "东亚世仇",
        [ "type" ] = 1,
    },
    [ 153 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "公平决斗",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 153,
        [ "name" ] = "公平决斗",
        [ "type" ] = 1,
    },
    [ 154 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "肉搏达人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13061,
        [ "id" ] = 154,
        [ "name" ] = "肉搏达人",
        [ "type" ] = 1,
    },
    [ 155 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "黑色暴徒",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13051,
        [ "id" ] = 155,
        [ "name" ] = "黑色暴徒",
        [ "type" ] = 1,
    },
    [ 156 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "精致药瓶",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13032,
        [ "id" ] = 156,
        [ "name" ] = "精致药瓶",
        [ "type" ] = 1,
    },
    [ 157 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "旧日仇人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 157,
        [ "name" ] = "旧日仇人",
        [ "type" ] = 1,
    },
    [ 158 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "高额悬赏",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13022,
        [ "id" ] = 158,
        [ "name" ] = "高额悬赏",
        [ "type" ] = 1,
    },
    [ 159 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "野蛮行事",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13052,
        [ "id" ] = 159,
        [ "name" ] = "野蛮行事",
        [ "type" ] = 1,
    },
    [ 160 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "死里逃生",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 160,
        [ "name" ] = "死里逃生",
        [ "type" ] = 1,
    },
    [ 161 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "近战达人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 161,
        [ "name" ] = "近战达人",
        [ "type" ] = 1,
    },
    [ 162 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "龙争虎斗",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13021,
        [ "id" ] = 162,
        [ "name" ] = "龙争虎斗",
        [ "type" ] = 1,
    },
    [ 163 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "铁拳之傲",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13061,
        [ "id" ] = 163,
        [ "name" ] = "铁拳之傲",
        [ "type" ] = 1,
    },
    [ 164 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "壮志雄心",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 164,
        [ "name" ] = "壮志雄心",
        [ "type" ] = 1,
    },
    [ 165 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "臂力过人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 165,
        [ "name" ] = "臂力过人",
        [ "type" ] = 1,
    },
    [ 166 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "尚武精神",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13021,
        [ "id" ] = 166,
        [ "name" ] = "尚武精神",
        [ "type" ] = 1,
    },
    [ 167 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "持强凌弱",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13042,
        [ "id" ] = 167,
        [ "name" ] = "持强凌弱",
        [ "type" ] = 1,
    },
    [ 168 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暴力至上",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13041,
        [ "id" ] = 168,
        [ "name" ] = "武力至上",
        [ "type" ] = 1,
    },
    [ 169 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "牢狱生涯",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 169,
        [ "name" ] = "牢狱生涯",
        [ "type" ] = 1,
    },
    [ 170 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "寸草不留",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13051,
        [ "id" ] = 170,
        [ "name" ] = "寸草不留",
        [ "type" ] = 1,
    },
    [ 171 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "火灾幸存",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14021,
        [ "id" ] = 171,
        [ "name" ] = "火灾幸存",
        [ "type" ] = 1,
    },
    [ 172 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "燃料来源",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14052,
        [ "id" ] = 172,
        [ "name" ] = "燃料来源",
        [ "type" ] = 1,
    },
    [ 173 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "罪恶精英",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11021,
        [ "id" ] = 173,
        [ "name" ] = "罪恶精英",
        [ "type" ] = 1,
    },
    [ 174 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "针锋相对",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14042,
        [ "id" ] = 174,
        [ "name" ] = "针锋相对",
        [ "type" ] = 1,
    },
    [ 175 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 22,
            [ 2 ] = 22,
        },
        [ "ch_key" ] = "面具阴影",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14061,
        [ "id" ] = 175,
        [ "name" ] = "面具阴影",
        [ "type" ] = 1,
    },
    [ 176 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "共同任务",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14042,
        [ "id" ] = 176,
        [ "name" ] = "共同任务",
        [ "type" ] = 1,
    },
    [ 177 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 20,
        },
        [ "ch_key" ] = "西部偶遇",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 177,
        [ "name" ] = "西部偶遇",
        [ "type" ] = 1,
    },
    [ 178 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 18,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "罪恶都市",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 178,
        [ "name" ] = "罪恶都市",
        [ "type" ] = 1,
    },
    [ 179 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "忠实顾客",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14061,
        [ "id" ] = 179,
        [ "name" ] = "忠实顾客",
        [ "type" ] = 1,
    },
    [ 180 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "昔日同僚",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 180,
        [ "name" ] = "昔日同僚",
        [ "type" ] = 1,
    },
    [ 181 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "丧心病狂",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11041,
        [ "id" ] = 181,
        [ "name" ] = "丧心病狂",
        [ "type" ] = 1,
    },
    [ 182 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "疯狂意志",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14041,
        [ "id" ] = 182,
        [ "name" ] = "疯狂意志",
        [ "type" ] = 1,
    },
    [ 183 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 18,
        },
        [ "ch_key" ] = "利害相关",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14021,
        [ "id" ] = 183,
        [ "name" ] = "利害相关",
        [ "type" ] = 1,
    },
    [ 184 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "业余医生",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14052,
        [ "id" ] = 184,
        [ "name" ] = "业余医生",
        [ "type" ] = 1,
    },
    [ 185 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 12,
        },
        [ "ch_key" ] = "负隅顽抗",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 185,
        [ "name" ] = "负隅顽抗",
        [ "type" ] = 1,
    },
    [ 186 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "双持爱好者",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14041,
        [ "id" ] = 186,
        [ "name" ] = "双持爱好者",
        [ "type" ] = 1,
    },
    [ 187 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "西部旧友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 187,
        [ "name" ] = "西部旧友",
        [ "type" ] = 1,
    },
    [ 188 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "不念旧情",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14052,
        [ "id" ] = 188,
        [ "name" ] = "不念旧情",
        [ "type" ] = 1,
    },
    [ 189 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "虐待狂",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 189,
        [ "name" ] = "虐待狂",
        [ "type" ] = 1,
    },
    [ 190 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "以雪前耻",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14031,
        [ "id" ] = 190,
        [ "name" ] = "以雪前耻",
        [ "type" ] = 1,
    },
    [ 191 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 16,
            [ 2 ] = 16,
        },
        [ "ch_key" ] = "二次合作",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 191,
        [ "name" ] = "二次合作",
        [ "type" ] = 1,
    },
    [ 192 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "断后任务",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14042,
        [ "id" ] = 192,
        [ "name" ] = "断后任务",
        [ "type" ] = 1,
    },
    [ 193 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 12,
            [ 2 ] = 14,
        },
        [ "ch_key" ] = "最高通缉",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 193,
        [ "name" ] = "最高通缉",
        [ "type" ] = 1,
    },
    [ 194 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "枪支交易",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14011,
        [ "id" ] = 194,
        [ "name" ] = "枪支交易",
        [ "type" ] = 1,
    },
    [ 195 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "残忍共识",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14041,
        [ "id" ] = 195,
        [ "name" ] = "残忍共识",
        [ "type" ] = 1,
    },
    [ 196 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "大打出手",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 196,
        [ "name" ] = "大打出手",
        [ "type" ] = 1,
    },
    [ 197 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "利益冲突",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11051,
        [ "id" ] = 197,
        [ "name" ] = "利益冲突",
        [ "type" ] = 1,
    },
    [ 198 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "性格不合",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14022,
        [ "id" ] = 198,
        [ "name" ] = "性格不合",
        [ "type" ] = 1,
    },
    [ 199 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "暴虐秉性",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14062,
        [ "id" ] = 199,
        [ "name" ] = "暴虐秉性",
        [ "type" ] = 1,
    },
    [ 200 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "黑道大佬",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14012,
        [ "id" ] = 200,
        [ "name" ] = "帮组大佬",
        [ "type" ] = 1,
    },
    [ 201 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "利益纠纷",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11031,
        [ "id" ] = 201,
        [ "name" ] = "利益纠纷",
        [ "type" ] = 1,
    },
    [ 202 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "最终救赎",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14051,
        [ "id" ] = 202,
        [ "name" ] = "最终救赎",
        [ "type" ] = 1,
    },
    [ 203 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "风格迥异",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14011,
        [ "id" ] = 203,
        [ "name" ] = "风格迥异",
        [ "type" ] = 1,
    },
    [ 204 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "笑里藏刀",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14052,
        [ "id" ] = 204,
        [ "name" ] = "笑里藏刀",
        [ "type" ] = 1,
    },
    [ 205 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "釜山旧仇",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12012,
        [ "id" ] = 205,
        [ "name" ] = "釜山旧仇",
        [ "type" ] = 1,
    },
    [ 206 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "亡命竞技",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14062,
        [ "id" ] = 206,
        [ "name" ] = "亡命竞技",
        [ "type" ] = 1,
    },
    [ 207 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "貌合神离",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14031,
        [ "id" ] = 207,
        [ "name" ] = "貌合神离",
        [ "type" ] = 1,
    },
    [ 208 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "重温旧事",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 208,
        [ "name" ] = "重温旧事",
        [ "type" ] = 1,
    },
    [ 209 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "犯罪博士",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 12031,
        [ "id" ] = 209,
        [ "name" ] = "犯罪博士",
        [ "type" ] = 1,
    },
    [ 210 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "落魄朋友",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14041,
        [ "id" ] = 210,
        [ "name" ] = "落魄朋友",
        [ "type" ] = 1,
    },
    [ 211 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "不详美貌",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14051,
        [ "id" ] = 211,
        [ "name" ] = "不详美貌",
        [ "type" ] = 1,
    },
    [ 212 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "暴力淑女",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14032,
        [ "id" ] = 212,
        [ "name" ] = "武力淑女",
        [ "type" ] = 1,
    },
    [ 213 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "旧日情人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13031,
        [ "id" ] = 213,
        [ "name" ] = "旧日情人",
        [ "type" ] = 1,
    },
    [ 214 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "慧眼识才",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14031,
        [ "id" ] = 214,
        [ "name" ] = "慧眼识才",
        [ "type" ] = 1,
    },
    [ 215 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 15,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "逃亡之伴",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 11052,
        [ "id" ] = 215,
        [ "name" ] = "逃亡之伴",
        [ "type" ] = 1,
    },
    [ 216 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "def_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "医者自危",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14042,
        [ "id" ] = 216,
        [ "name" ] = "医者自危",
        [ "type" ] = 1,
    },
    [ 217 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "att_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 15,
        },
        [ "ch_key" ] = "紧急任务",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 13011,
        [ "id" ] = 217,
        [ "name" ] = "紧急任务",
        [ "type" ] = 1,
    },
    [ 218 ] = {
        [ "attr_list" ] = {
            [ 1 ] = "def_pct",
            [ 2 ] = "max_hp_pct",
        },
        [ "attr_value_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "ch_key" ] = "共同敌人",
        [ "desc" ] = "与%s一起上阵，%s增加%s,%s增加%s",
        [ "fate_hero" ] = 14011,
        [ "id" ] = 218,
        [ "name" ] = "共同敌人",
        [ "type" ] = 1,
    },
    [ "hero_dict" ] = {
    },
}