return {
    [ 1 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 0,
            [ "fight" ] = 0,
            [ "management" ] = 0,
            [ "renown" ] = 0,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 0,
            [ 2 ] = 0,
            [ 3 ] = 0,
            [ 4 ] = 0,
        },
        [ "add_child_flair" ] = 0,
        [ "attr_sum_limit" ] = 0,
        [ "ch_key" ] = "未册封",
        [ "icon" ] = 90009,
        [ "id" ] = 1,
        [ "level_limit" ] = 0,
        [ "max_count" ] = -1,
        [ "name" ] = "无",
        [ "salon_attr_point" ] = 0,
    },
    [ 2 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 1000,
            [ "fight" ] = 1000,
            [ "management" ] = 1000,
            [ "renown" ] = 1000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 1000,
            [ 2 ] = 1000,
            [ 3 ] = 1000,
            [ 4 ] = 1000,
        },
        [ "add_child_flair" ] = 1,
        [ "attr_sum_limit" ] = 100,
        [ "ch_key" ] = "美人",
        [ "icon" ] = 90010,
        [ "id" ] = 2,
        [ "level_limit" ] = 10,
        [ "max_count" ] = -1,
        [ "name" ] = "甜心",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302016,
        [ "salon_attr_point" ] = 1,
    },
    [ 3 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 4000,
            [ "fight" ] = 4000,
            [ "management" ] = 4000,
            [ "renown" ] = 4000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 4000,
            [ 2 ] = 4000,
            [ 3 ] = 4000,
            [ 4 ] = 4000,
        },
        [ "add_child_flair" ] = 3,
        [ "attr_sum_limit" ] = 800,
        [ "ch_key" ] = "答应",
        [ "icon" ] = 90011,
        [ "id" ] = 3,
        [ "level_limit" ] = 25,
        [ "max_count" ] = -1,
        [ "name" ] = "宝贝",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302017,
        [ "salon_attr_point" ] = 2,
    },
    [ 4 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 10000,
            [ "fight" ] = 10000,
            [ "management" ] = 10000,
            [ "renown" ] = 10000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 10000,
            [ 2 ] = 10000,
            [ 3 ] = 10000,
            [ 4 ] = 10000,
        },
        [ "add_child_flair" ] = 5,
        [ "attr_sum_limit" ] = 4000,
        [ "ch_key" ] = "常在",
        [ "icon" ] = 90012,
        [ "id" ] = 4,
        [ "level_limit" ] = 40,
        [ "max_count" ] = -1,
        [ "name" ] = "知音",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302018,
        [ "salon_attr_point" ] = 3,
    },
    [ 5 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 20000,
            [ "fight" ] = 20000,
            [ "management" ] = 20000,
            [ "renown" ] = 20000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 20000,
            [ 2 ] = 20000,
            [ 3 ] = 20000,
            [ 4 ] = 20000,
        },
        [ "add_child_flair" ] = 8,
        [ "attr_sum_limit" ] = 8000,
        [ "ch_key" ] = "贵人",
        [ "icon" ] = 90013,
        [ "id" ] = 5,
        [ "level_limit" ] = 60,
        [ "max_count" ] = -1,
        [ "name" ] = "伴侣",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302019,
        [ "salon_attr_point" ] = 4,
    },
    [ 6 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 40000,
            [ "fight" ] = 40000,
            [ "management" ] = 40000,
            [ "renown" ] = 40000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 40000,
            [ 2 ] = 40000,
            [ 3 ] = 40000,
            [ 4 ] = 40000,
        },
        [ "add_child_flair" ] = 12,
        [ "attr_sum_limit" ] = 16000,
        [ "ch_key" ] = "嫔",
        [ "icon" ] = 90014,
        [ "id" ] = 6,
        [ "level_limit" ] = 85,
        [ "max_count" ] = 6,
        [ "name" ] = "灵魂伴侣",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302020,
        [ "salon_attr_point" ] = 5,
    },
    [ 7 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 80000,
            [ "fight" ] = 80000,
            [ "management" ] = 80000,
            [ "renown" ] = 80000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 80000,
            [ 2 ] = 80000,
            [ 3 ] = 80000,
            [ 4 ] = 80000,
        },
        [ "add_child_flair" ] = 16,
        [ "attr_sum_limit" ] = 32000,
        [ "ch_key" ] = "妃",
        [ "icon" ] = 90015,
        [ "id" ] = 7,
        [ "level_limit" ] = 110,
        [ "max_count" ] = 6,
        [ "name" ] = "爱人",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302021,
        [ "salon_attr_point" ] = 6,
    },
    [ 8 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 200000,
            [ "fight" ] = 200000,
            [ "management" ] = 200000,
            [ "renown" ] = 200000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 200000,
            [ 2 ] = 200000,
            [ 3 ] = 200000,
            [ 4 ] = 200000,
        },
        [ "add_child_flair" ] = 20,
        [ "attr_sum_limit" ] = 64000,
        [ "ch_key" ] = "贵妃",
        [ "icon" ] = 90016,
        [ "id" ] = 8,
        [ "level_limit" ] = 140,
        [ "max_count" ] = 3,
        [ "name" ] = "妻子",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302022,
        [ "salon_attr_point" ] = 7,
    },
    [ 9 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 500000,
            [ "fight" ] = 500000,
            [ "management" ] = 500000,
            [ "renown" ] = 500000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 500000,
            [ 2 ] = 500000,
            [ 3 ] = 500000,
            [ 4 ] = 500000,
        },
        [ "add_child_flair" ] = 24,
        [ "attr_sum_limit" ] = 128000,
        [ "ch_key" ] = "皇贵妃",
        [ "icon" ] = 90017,
        [ "id" ] = 9,
        [ "level_limit" ] = 175,
        [ "max_count" ] = 2,
        [ "name" ] = "女主人",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302023,
        [ "salon_attr_point" ] = 8,
    },
    [ 10 ] = {
        [ "add_attr_dict" ] = {
            [ "business" ] = 1000000,
            [ "fight" ] = 1000000,
            [ "management" ] = 1000000,
            [ "renown" ] = 1000000,
        },
        [ "add_attr_list" ] = {
            [ 1 ] = "business",
            [ 2 ] = "management",
            [ 3 ] = "renown",
            [ 4 ] = "fight",
        },
        [ "add_attr_num_list" ] = {
            [ 1 ] = 1000000,
            [ 2 ] = 1000000,
            [ 3 ] = 1000000,
            [ 4 ] = 1000000,
        },
        [ "add_child_flair" ] = 30,
        [ "add_levy_list" ] = {
            [ 1 ] = 1,
            [ 2 ] = 2,
            [ 3 ] = 3,
        },
        [ "add_levy_percent_list" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
        },
        [ "attr_sum_limit" ] = 256000,
        [ "ch_key" ] = "皇后",
        [ "icon" ] = 90018,
        [ "id" ] = 10,
        [ "level_limit" ] = 220,
        [ "max_count" ] = 1,
        [ "name" ] = "第一夫人",
        [ "promote_item_count" ] = 1,
        [ "promote_item_id" ] = 302024,
        [ "salon_attr_point" ] = 9,
    },
}