return {
    [ 1 ] = {
        [ "ch_key" ] = "征收金币",
        [ "effect_id" ] = "1",
        [ "id" ] = 1,
        [ "influence_attribute" ] = "business",
        [ "levy_item_id" ] = 101002,
        [ "name" ] = "获取盈利",
        [ "sound_id" ] = "205",
        [ "trans_ratio" ] = 1,
    },
    [ 2 ] = {
        [ "ch_key" ] = "征收食物",
        [ "effect_id" ] = "2",
        [ "id" ] = 2,
        [ "influence_attribute" ] = "management",
        [ "levy_item_id" ] = 101003,
        [ "name" ] = "制造装备",
        [ "sound_id" ] = "206",
        [ "trans_ratio" ] = 1,
    },
    [ 3 ] = {
        [ "cast_item_id" ] = 101003,
        [ "ch_key" ] = "征收帮众",
        [ "effect_id" ] = "3",
        [ "id" ] = 3,
        [ "influence_attribute" ] = "renown",
        [ "levy_item_id" ] = 101004,
        [ "name" ] = "招募帮众",
        [ "sound_id" ] = "207",
        [ "trans_ratio" ] = 1,
    },
}