return {
    [ 1 ] = {
        [ "add_item_num" ] = 300,
        [ "add_vip_exp" ] = 600,
        [ "daily_item_num" ] = 200,
        [ "desc" ] = "月卡描述",
        [ "id" ] = 1,
        [ "item_id" ] = 101005,
        [ "name" ] = "月卡",
        [ "price" ] = 25,
        [ "type" ] = 1,
        [ "validity_period_day" ] = 30,
    },
    [ 2 ] = {
        [ "add_item_num" ] = 1500,
        [ "add_vip_exp" ] = 2000,
        [ "daily_item_num" ] = 300,
        [ "desc" ] = "终身卡描述",
        [ "id" ] = 2,
        [ "item_id" ] = 101005,
        [ "name" ] = "终身卡",
        [ "price" ] = 98,
        [ "type" ] = 2,
    },
}