return {
    [ 1 ] = {
        [ "aim_move_speed" ] = 1.5,
        [ "dart_unit" ] = 6002,
        [ "icon" ] = 90062,
        [ "id" ] = 1,
        [ "introduce_str" ] = "扔中靶心，积分更高",
        [ "name" ] = "飞镖",
        [ "rule_text" ] = "扔中靶心积分+20 扔中大环积分+ 10 扔中小环积分+5",
        [ "score_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 10,
            [ 3 ] = 5,
            [ 4 ] = 0,
        },
        [ "throw_cool_time" ] = 2,
        [ "time" ] = 3,
        [ "ui" ] = "ThrowDartUI",
    },
    [ 2 ] = {
        [ "dice_icon_list" ] = {
            [ 1 ] = 90051,
            [ 2 ] = 90052,
            [ 3 ] = 90053,
            [ 4 ] = 90054,
            [ 5 ] = 90055,
            [ 6 ] = 90056,
        },
        [ "dicing_time" ] = 0.7,
        [ "icon" ] = 90063,
        [ "id" ] = 2,
        [ "introduce_str" ] = "用骰子击败对方",
        [ "max_point" ] = 6,
        [ "name" ] = "掷色子",
        [ "rule_text" ] = "扔出的点数比对方大，即可获得更多积分",
        [ "score_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 10,
            [ 3 ] = 0,
        },
        [ "time" ] = 3,
        [ "ui" ] = "DicingUI",
    },
    [ 3 ] = {
        [ "boom_pause_time" ] = 1,
        [ "icon" ] = 90064,
        [ "id" ] = 3,
        [ "introduce_str" ] = "30秒内，抓到的钱越多积分越多",
        [ "move_speed_list" ] = {
            [ 1 ] = 0.4,
            [ 2 ] = 0.1,
            [ 3 ] = 0.1,
        },
        [ "name" ] = "射钞票",
        [ "rule_text" ] = "点击钞票将其射下，注意不要射到闪光弹",
        [ "score_list" ] = {
            [ 1 ] = 2,
            [ 2 ] = 1,
            [ 3 ] = 0,
        },
        [ "shoot_tip_list" ] = {
            [ 1 ] = "射中钞票x2 <color=#01D12e>  +%s</color>分",
            [ 2 ] = "射中钞票 <color=#01D12e>  +%s</color>分",
        },
        [ "spawn_cool_time" ] = 0.5,
        [ "spawn_weight_list" ] = {
            [ 1 ] = 2,
            [ 2 ] = 6,
            [ 3 ] = 2,
        },
        [ "time" ] = 30,
        [ "ui" ] = "ShootMoneyUI",
    },
}