return {
    [ 1 ] = {
        [ "big_icon" ] = 50035002,
        [ "drop_list" ] = {
            [ 1 ] = 1028,
        },
        [ "drop_str" ] = "有几率获得:金钱、物资、帮众",
        [ "hero_unit_id" ] = 35002,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "求求您了，别打了！",
            [ 2 ] = "对不起，我不该与您作对的！",
        },
        [ "icon" ] = 50035002,
        [ "id" ] = 1,
        [ "max_torture_num" ] = 10,
        [ "name" ] = "亚伯",
        [ "normal_talk_list" ] = {
            [ 1 ] = "放过我吧。",
            [ 2 ] = "求求您别打我，我什么都说",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 20,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
    [ 2 ] = {
        [ "big_icon" ] = 50011062,
        [ "drop_list" ] = {
            [ 1 ] = 1029,
        },
        [ "drop_str" ] = "有几率获得:金钱、物资、帮众、兴奋药",
        [ "hero_unit_id" ] = 11062,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "原谅我这次吧，求求您了！",
            [ 2 ] = "别打了，我什么都说！",
        },
        [ "icon" ] = 50011062,
        [ "id" ] = 2,
        [ "max_torture_num" ] = 25,
        [ "name" ] = "克尔顿",
        [ "normal_talk_list" ] = {
            [ 1 ] = "只要放过我，我什么都肯做！",
            [ 2 ] = "饶了我吧！",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 60,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
    [ 3 ] = {
        [ "big_icon" ] = 50011031,
        [ "drop_list" ] = {
            [ 1 ] = 1030,
        },
        [ "drop_str" ] = "有几率获得:金钱、物资、帮众、情报",
        [ "hero_unit_id" ] = 11031,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "没吃饭吗？再用点劲啊！",
            [ 2 ] = "我是不会屈服的，杂种！",
        },
        [ "icon" ] = 50011031,
        [ "id" ] = 3,
        [ "max_torture_num" ] = 50,
        [ "name" ] = "卡米拉",
        [ "normal_talk_list" ] = {
            [ 1 ] = "又要来给我挠痒痒了吗？",
            [ 2 ] = "有种就杀了我啊！",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "219",
        [ "stage" ] = 100,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5002,
    },
    [ 4 ] = {
        [ "big_icon" ] = 50011011,
        [ "drop_list" ] = {
            [ 1 ] = 1031,
        },
        [ "drop_str" ] = "有几率获得:提神烟、水果糖、奶粉、红酒、机票",
        [ "hero_unit_id" ] = 11011,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "原谅我这次吧，求求您了！",
            [ 2 ] = "别打了，我什么都说！",
        },
        [ "icon" ] = 50011011,
        [ "id" ] = 4,
        [ "max_torture_num" ] = 15,
        [ "name" ] = "布兰迪",
        [ "normal_talk_list" ] = {
            [ 1 ] = "只要放过我，我什么都肯做！",
            [ 2 ] = "饶了我吧！",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 200,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
    [ 5 ] = {
        [ "big_icon" ] = 50014032,
        [ "drop_list" ] = {
            [ 1 ] = 1032,
        },
        [ "drop_str" ] = "有几率获得:银项链、金项链、钻石项链",
        [ "hero_unit_id" ] = 14032,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "求求您了，别打了！",
            [ 2 ] = "对不起，我不该与您作对的！",
        },
        [ "icon" ] = 50014032,
        [ "id" ] = 5,
        [ "max_torture_num" ] = 10,
        [ "name" ] = "莉莲",
        [ "normal_talk_list" ] = {
            [ 1 ] = "放过我吧。",
            [ 2 ] = "求求您别打我，我什么都说",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "219",
        [ "stage" ] = 300,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5002,
    },
    [ 6 ] = {
        [ "big_icon" ] = 50012021,
        [ "drop_list" ] = {
            [ 1 ] = 1033,
        },
        [ "drop_str" ] = "有几率获得:金钱、物资、帮众",
        [ "hero_unit_id" ] = 12021,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "原谅我这次吧，求求您了！",
            [ 2 ] = "别打了，我什么都说！",
        },
        [ "icon" ] = 50012021,
        [ "id" ] = 6,
        [ "max_torture_num" ] = 80,
        [ "name" ] = "兰斯",
        [ "normal_talk_list" ] = {
            [ 1 ] = "只要放过我，我什么都肯做！",
            [ 2 ] = "饶了我吧！",
        },
        [ "prestige_cost" ] = 20,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 400,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
    [ 7 ] = {
        [ "big_icon" ] = 50013032,
        [ "drop_list" ] = {
            [ 1 ] = 1034,
        },
        [ "drop_str" ] = "有几率获得:钻石",
        [ "hero_unit_id" ] = 13043,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "没吃饭吗？再用点劲啊！",
            [ 2 ] = "我是不会屈服的，杂种！",
        },
        [ "icon" ] = 50013032,
        [ "id" ] = 7,
        [ "max_torture_num" ] = 25,
        [ "name" ] = "露西",
        [ "normal_talk_list" ] = {
            [ 1 ] = "又要来给我挠痒痒了吗？",
            [ 2 ] = "有种就杀了我啊！",
        },
        [ "prestige_cost" ] = 30,
        [ "screech_sound_id" ] = "219",
        [ "stage" ] = 500,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5002,
    },
    [ 8 ] = {
        [ "big_icon" ] = 50014041,
        [ "drop_list" ] = {
            [ 1 ] = 1035,
        },
        [ "drop_str" ] = "有几率获得:金钱、物资、帮众",
        [ "hero_unit_id" ] = 14041,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "原谅我这次吧，求求您了！",
            [ 2 ] = "别打了，我什么都说！",
        },
        [ "icon" ] = 50014041,
        [ "id" ] = 8,
        [ "max_torture_num" ] = 40,
        [ "name" ] = "罗根",
        [ "normal_talk_list" ] = {
            [ 1 ] = "只要放过我，我什么都肯做！",
            [ 2 ] = "饶了我吧！",
        },
        [ "prestige_cost" ] = 30,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 600,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
    [ 9 ] = {
        [ "big_icon" ] = 50011052,
        [ "drop_list" ] = {
            [ 1 ] = 1036,
        },
        [ "drop_str" ] = "有几率获得:提神烟、水果糖、奶粉、红酒、机票",
        [ "hero_unit_id" ] = 11052,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "求求您了，别打了！",
            [ 2 ] = "对不起，我不该与您作对的！",
        },
        [ "icon" ] = 50011052,
        [ "id" ] = 9,
        [ "max_torture_num" ] = 30,
        [ "name" ] = "诺玛",
        [ "normal_talk_list" ] = {
            [ 1 ] = "放过我吧。",
            [ 2 ] = "求求您别打我，我什么都说",
        },
        [ "prestige_cost" ] = 40,
        [ "screech_sound_id" ] = "219",
        [ "stage" ] = 700,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5002,
    },
    [ 10 ] = {
        [ "big_icon" ] = 50012051,
        [ "drop_list" ] = {
            [ 1 ] = 1037,
        },
        [ "drop_str" ] = "有几率获得:钻石、银项链、金项链、钻石项链、授权令",
        [ "hero_unit_id" ] = 12051,
        [ "hurt_talk_list" ] = {
            [ 1 ] = "原谅我这次吧，求求您了！",
            [ 2 ] = "别打了，我什么都说！",
        },
        [ "icon" ] = 50012051,
        [ "id" ] = 10,
        [ "max_torture_num" ] = 9999,
        [ "name" ] = "查尔斯",
        [ "normal_talk_list" ] = {
            [ 1 ] = "只要放过我，我什么都肯做！",
            [ 2 ] = "饶了我吧！",
        },
        [ "prestige_cost" ] = 200,
        [ "screech_sound_id" ] = "218",
        [ "stage" ] = 800,
        [ "torture_type_list" ] = {
            [ 1 ] = 1,
        },
        [ "unit_id" ] = 5001,
    },
}