return {
    [ 1 ] = {
        [ "activity_close_time" ] = 1684684800,
        [ "activity_desc" ] = "精良装备打造您的最强黑道军团，单笔充值指定金额即可领取橙色装备宝箱。",
        [ "activity_end_time" ] = 1684598400,
        [ "activity_name" ] = "每日单充",
        [ "activity_start_time" ] = 1683993600,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "精良装备",
        [ "id" ] = 1,
        [ "show_other_reward" ] = false,
        [ "title" ] = "传奇头目",
        [ "unit" ] = 12051,
    },
    [ 2 ] = {
        [ "activity_close_time" ] = 1685289600,
        [ "activity_desc" ] = "神秘宝物助力您成就黑道巅峰，单笔充值指定金额即可领取橙色色宝物宝箱。",
        [ "activity_end_time" ] = 1685203200,
        [ "activity_name" ] = "每日单充",
        [ "activity_start_time" ] = 1684598400,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "神秘宝物",
        [ "id" ] = 2,
        [ "show_other_reward" ] = false,
        [ "title" ] = "佳人有约",
        [ "unit" ] = 23011,
    },
    [ 3 ] = {
        [ "activity_close_time" ] = 1685894400,
        [ "activity_desc" ] = "性感佳人期待与您的邂逅，单笔充值指定金额即可领取橙色情人宝箱。",
        [ "activity_end_time" ] = 1685808000,
        [ "activity_name" ] = "每日单充",
        [ "activity_start_time" ] = 1685203200,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330002,
        [ "ch_key" ] = "佳人有约",
        [ "id" ] = 3,
        [ "show_other_reward" ] = false,
        [ "title" ] = "全副武装",
        [ "unit" ] = 21051,
    },
    [ 4 ] = {
        [ "activity_close_time" ] = 1686499200,
        [ "activity_desc" ] = "精锐头目助您征战黑帮世界，单笔充值指定金额即可领取橙色头目宝箱。",
        [ "activity_end_time" ] = 1686412800,
        [ "activity_name" ] = "每日单充",
        [ "activity_start_time" ] = 1685808000,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330002,
        [ "ch_key" ] = "精锐头目",
        [ "id" ] = 4,
        [ "show_other_reward" ] = false,
        [ "title" ] = "黑道重宝",
        [ "unit" ] = 21031,
    },
    [ 5 ] = {
        [ "activity_close_time" ] = 1687104000,
        [ "activity_desc" ] = "为了防止世界被破坏",
        [ "activity_end_time" ] = 1687017600,
        [ "activity_name" ] = "超值单充",
        [ "activity_start_time" ] = 1686412800,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "每日单充5",
        [ "id" ] = 5,
        [ "show_other_reward" ] = false,
        [ "title" ] = "充钱3",
        [ "unit" ] = 21051,
    },
    [ 6 ] = {
        [ "activity_close_time" ] = 1687708800,
        [ "activity_desc" ] = "为了守护世界的和平",
        [ "activity_end_time" ] = 1687622400,
        [ "activity_name" ] = "超值单充",
        [ "activity_start_time" ] = 1687017600,
        [ "activity_type" ] = 1,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "每日单充6",
        [ "id" ] = 6,
        [ "show_other_reward" ] = false,
        [ "title" ] = "充钱4",
        [ "unit" ] = 21051,
    },
    [ 7 ] = {
        [ "activity_close_time" ] = 1684684800,
        [ "activity_desc" ] = "贯彻爱与真实的邪恶",
        [ "activity_end_time" ] = 1684598400,
        [ "activity_name" ] = "充值抽奖",
        [ "activity_start_time" ] = 1683993600,
        [ "activity_type" ] = 3,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "贯彻爱与真实的邪恶",
        [ "desc" ] = {
            [ 1 ] = "感恩回礼，回馈不断！",
        },
        [ "draw_diff_count" ] = {
            [ 1 ] = 6,
            [ 2 ] = 5,
            [ 3 ] = 4,
        },
        [ "id" ] = 7,
        [ "recharge_count_list" ] = {
            [ 1 ] = 0,
            [ 2 ] = 102,
            [ 3 ] = 202,
        },
        [ "show_other_reward" ] = true,
        [ "title" ] = "充钱5",
        [ "unit" ] = 21051,
    },
    [ 8 ] = {
        [ "activity_close_time" ] = 1685894400,
        [ "activity_desc" ] = "可爱又迷人的反派角色",
        [ "activity_end_time" ] = 1685808000,
        [ "activity_name" ] = "充值抽奖",
        [ "activity_start_time" ] = 1685203200,
        [ "activity_type" ] = 3,
        [ "bg" ] = 330001,
        [ "ch_key" ] = "可爱又迷人的反派角色",
        [ "desc" ] = {
            [ 1 ] = "感恩回礼，回馈不断！",
        },
        [ "draw_diff_count" ] = {
            [ 1 ] = 6,
            [ 2 ] = 5,
            [ 3 ] = 4,
        },
        [ "id" ] = 8,
        [ "recharge_count_list" ] = {
            [ 1 ] = 0,
            [ 2 ] = 102,
            [ 3 ] = 302,
        },
        [ "show_other_reward" ] = true,
        [ "title" ] = "充钱6",
        [ "unit" ] = 21051,
    },
}