return {
    [ 1 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 1,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 100000,
        [ "item_id" ] = 101002,
        [ "weight" ] = 500,
    },
    [ 2 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 2,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 100000,
        [ "item_id" ] = 101004,
        [ "weight" ] = 500,
    },
    [ 3 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 3,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 201001,
        [ "weight" ] = 100,
    },
    [ 4 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 4,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 201002,
        [ "weight" ] = 100,
    },
    [ 5 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 5,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 201003,
        [ "weight" ] = 100,
    },
    [ 6 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 6,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301017,
        [ "weight" ] = 100,
    },
    [ 7 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 7,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301018,
        [ "weight" ] = 100,
    },
    [ 8 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 8,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301007,
        [ "weight" ] = 100,
    },
    [ 9 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 9,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301008,
        [ "weight" ] = 100,
    },
    [ 10 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 10,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301003,
        [ "weight" ] = 100,
    },
    [ 11 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 11,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301004,
        [ "weight" ] = 100,
    },
    [ 12 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 12,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301005,
        [ "weight" ] = 100,
    },
    [ 13 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 13,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301021,
        [ "weight" ] = 500,
    },
    [ 14 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 14,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301022,
        [ "weight" ] = 100,
    },
    [ 15 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 15,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301023,
        [ "weight" ] = 50,
    },
    [ 16 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 16,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301024,
        [ "weight" ] = 500,
    },
    [ 17 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 17,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301025,
        [ "weight" ] = 100,
    },
    [ 18 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 18,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301026,
        [ "weight" ] = 50,
    },
    [ 19 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 19,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301027,
        [ "weight" ] = 500,
    },
    [ 20 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 20,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301028,
        [ "weight" ] = 100,
    },
    [ 21 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 21,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301029,
        [ "weight" ] = 50,
    },
    [ 22 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 22,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301030,
        [ "weight" ] = 500,
    },
    [ 23 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 23,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301031,
        [ "weight" ] = 100,
    },
    [ 24 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 24,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 301032,
        [ "weight" ] = 50,
    },
    [ 25 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 25,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 302002,
        [ "weight" ] = 100,
    },
    [ 26 ] = {
        [ "activity_id" ] = 7,
        [ "award_type" ] = 0,
        [ "id" ] = 26,
        [ "is_show_award" ] = false,
        [ "item_count" ] = 1,
        [ "item_id" ] = 302003,
        [ "weight" ] = 50,
    },
    [ 27 ] = {
        [ "activity_id" ] = 7,
        [ "award_num" ] = 2,
        [ "award_pre_turn" ] = 50,
        [ "award_turn" ] = 10,
        [ "award_type" ] = 1,
        [ "id" ] = 27,
        [ "is_show_award" ] = true,
        [ "item_count" ] = 1,
        [ "item_id" ] = 204020,
        [ "weight" ] = 100,
    },
    [ 28 ] = {
        [ "activity_id" ] = 7,
        [ "award_num" ] = 1,
        [ "award_pre_turn" ] = 100,
        [ "award_turn" ] = 1,
        [ "award_type" ] = 1,
        [ "id" ] = 28,
        [ "is_show_award" ] = true,
        [ "item_count" ] = 10,
        [ "item_id" ] = 204020,
        [ "weight" ] = 1,
    },
    [ 29 ] = {
        [ "activity_id" ] = 7,
        [ "award_num" ] = 2,
        [ "award_pre_turn" ] = 55,
        [ "award_turn" ] = 4,
        [ "award_type" ] = 2,
        [ "id" ] = 29,
        [ "is_show_award" ] = true,
        [ "item_count" ] = 666,
        [ "item_id" ] = 101005,
        [ "weight" ] = 50,
    },
    [ 30 ] = {
        [ "activity_id" ] = 7,
        [ "award_num" ] = 2,
        [ "award_pre_turn" ] = 55,
        [ "award_turn" ] = 4,
        [ "award_type" ] = 2,
        [ "id" ] = 30,
        [ "is_show_award" ] = true,
        [ "item_count" ] = 888,
        [ "item_id" ] = 101005,
        [ "weight" ] = 50,
    },
}