return {
    [ 1 ] = {
        [ "head_icon_id" ] = 10017,
        [ "res_name" ] = "Head White",
        [ "res_path" ] = "UISprite/Icon",
        [ "role_look_id" ] = 1,
        [ "sex" ] = 1,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 1,
        [ "unlock_icon" ] = 10017,
        [ "unlocked" ] = true,
    },
    [ 2 ] = {
        [ "head_icon_id" ] = 10019,
        [ "role_look_id" ] = 2,
        [ "sex" ] = 1,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 3,
        [ "unlock_icon" ] = 10017,
        [ "unlocked" ] = true,
    },
    [ 3 ] = {
        [ "head_icon_id" ] = 10047,
        [ "role_look_id" ] = 3,
        [ "sex" ] = 1,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 7,
        [ "unlock_icon" ] = 10017,
        [ "unlocked" ] = true,
    },
    [ 4 ] = {
        [ "head_icon_id" ] = 10045,
        [ "role_look_id" ] = 4,
        [ "sex" ] = 1,
        [ "skin_id" ] = 2,
        [ "unit_id" ] = 5,
        [ "unlock_icon" ] = 10017,
        [ "unlocked" ] = true,
    },
    [ 5 ] = {
        [ "head_icon_id" ] = 10042,
        [ "role_look_id" ] = 5,
        [ "sex" ] = 1,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 3019,
        [ "unlock_icon" ] = 10017,
        [ "unlocked" ] = true,
    },
    [ 6 ] = {
        [ "head_icon_id" ] = 10018,
        [ "res_name" ] = "Head White",
        [ "res_path" ] = "UISprite/Icon",
        [ "role_look_id" ] = 6,
        [ "sex" ] = 2,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 2,
        [ "unlock_icon" ] = 10018,
        [ "unlocked" ] = true,
    },
    [ 7 ] = {
        [ "head_icon_id" ] = 10020,
        [ "role_look_id" ] = 7,
        [ "sex" ] = 2,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 4,
        [ "unlock_icon" ] = 10018,
        [ "unlocked" ] = true,
    },
    [ 8 ] = {
        [ "head_icon_id" ] = 10048,
        [ "role_look_id" ] = 8,
        [ "sex" ] = 2,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 8,
        [ "unlock_icon" ] = 10018,
        [ "unlocked" ] = true,
    },
    [ 9 ] = {
        [ "head_icon_id" ] = 10046,
        [ "role_look_id" ] = 9,
        [ "sex" ] = 2,
        [ "skin_id" ] = 2,
        [ "unit_id" ] = 6,
        [ "unlock_icon" ] = 10018,
        [ "unlocked" ] = true,
    },
    [ 10 ] = {
        [ "head_icon_id" ] = 10049,
        [ "role_look_id" ] = 10,
        [ "sex" ] = 2,
        [ "skin_id" ] = 1,
        [ "unit_id" ] = 9,
        [ "unlock_icon" ] = 10018,
        [ "unlocked" ] = true,
    },
}