return {
    [ 1 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 1,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201001,
            [ 2 ] = 201002,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9601,
        [ "select_num" ] = 1,
    },
    [ 2 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 2,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 301023,
            [ 2 ] = 301026,
            [ 3 ] = 301029,
            [ 4 ] = 301032,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9607,
        [ "select_num" ] = 1,
    },
    [ 3 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 3,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9613,
        [ "select_num" ] = 1,
    },
    [ 4 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 4,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205107,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9619,
        [ "select_num" ] = 1,
    },
    [ 5 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 5,
        [ "item_count" ] = {
            [ 1 ] = 80,
        },
        [ "item_id" ] = {
            [ 1 ] = 205107,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9625,
        [ "select_num" ] = 1,
    },
    [ 6 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 6,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9631,
        [ "select_num" ] = 1,
    },
    [ 7 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 7,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9637,
        [ "select_num" ] = 1,
    },
    [ 8 ] = {
        [ "activity_id" ] = 1,
        [ "id" ] = 8,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9643,
        [ "select_num" ] = 1,
    },
    [ 9 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 9,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201003,
            [ 2 ] = 301004,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9602,
        [ "select_num" ] = 1,
    },
    [ 10 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 10,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 302006,
            [ 2 ] = 302009,
            [ 3 ] = 302012,
            [ 4 ] = 302015,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9608,
        [ "select_num" ] = 1,
    },
    [ 11 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 11,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9614,
        [ "select_num" ] = 1,
    },
    [ 12 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 12,
        [ "item_count" ] = {
            [ 1 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 205108,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9620,
        [ "select_num" ] = 1,
    },
    [ 13 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 13,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205108,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9626,
        [ "select_num" ] = 1,
    },
    [ 14 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 14,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9632,
        [ "select_num" ] = 1,
    },
    [ 15 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 15,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9638,
        [ "select_num" ] = 1,
    },
    [ 16 ] = {
        [ "activity_id" ] = 2,
        [ "id" ] = 16,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9644,
        [ "select_num" ] = 1,
    },
    [ 17 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 17,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201001,
            [ 2 ] = 201002,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9603,
        [ "select_num" ] = 1,
    },
    [ 18 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 18,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 301023,
            [ 2 ] = 301026,
            [ 3 ] = 301029,
            [ 4 ] = 301032,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9609,
        [ "select_num" ] = 1,
    },
    [ 19 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 19,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9615,
        [ "select_num" ] = 1,
    },
    [ 20 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 20,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205110,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9621,
        [ "select_num" ] = 1,
    },
    [ 21 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 21,
        [ "item_count" ] = {
            [ 1 ] = 80,
        },
        [ "item_id" ] = {
            [ 1 ] = 205110,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9627,
        [ "select_num" ] = 1,
    },
    [ 22 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 22,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9633,
        [ "select_num" ] = 1,
    },
    [ 23 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 23,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9639,
        [ "select_num" ] = 1,
    },
    [ 24 ] = {
        [ "activity_id" ] = 3,
        [ "id" ] = 24,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9645,
        [ "select_num" ] = 1,
    },
    [ 25 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 25,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201003,
            [ 2 ] = 301004,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9604,
        [ "select_num" ] = 1,
    },
    [ 26 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 26,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 302006,
            [ 2 ] = 302009,
            [ 3 ] = 302012,
            [ 4 ] = 302015,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9610,
        [ "select_num" ] = 1,
    },
    [ 27 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 27,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9616,
        [ "select_num" ] = 1,
    },
    [ 28 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 28,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9622,
        [ "select_num" ] = 1,
    },
    [ 29 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 29,
        [ "item_count" ] = {
            [ 1 ] = 80,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9628,
        [ "select_num" ] = 1,
    },
    [ 30 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 30,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9634,
        [ "select_num" ] = 1,
    },
    [ 31 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 31,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9640,
        [ "select_num" ] = 1,
    },
    [ 32 ] = {
        [ "activity_id" ] = 4,
        [ "id" ] = 32,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9646,
        [ "select_num" ] = 1,
    },
    [ 33 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 33,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201003,
            [ 2 ] = 301004,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9605,
        [ "select_num" ] = 1,
    },
    [ 34 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 34,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 302006,
            [ 2 ] = 302009,
            [ 3 ] = 302012,
            [ 4 ] = 302015,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9617,
        [ "select_num" ] = 1,
    },
    [ 35 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 35,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9623,
        [ "select_num" ] = 1,
    },
    [ 36 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 36,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9629,
        [ "select_num" ] = 1,
    },
    [ 37 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 37,
        [ "item_count" ] = {
            [ 1 ] = 80,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9635,
        [ "select_num" ] = 1,
    },
    [ 38 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 38,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9641,
        [ "select_num" ] = 1,
    },
    [ 39 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 39,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9647,
        [ "select_num" ] = 1,
    },
    [ 40 ] = {
        [ "activity_id" ] = 5,
        [ "id" ] = 40,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9611,
        [ "select_num" ] = 1,
    },
    [ 41 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 41,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 201003,
            [ 2 ] = 301004,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "reward_id" ] = 9606,
        [ "select_num" ] = 1,
    },
    [ 42 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 42,
        [ "item_count" ] = {
            [ 1 ] = 10,
            [ 2 ] = 10,
            [ 3 ] = 10,
            [ 4 ] = 10,
        },
        [ "item_id" ] = {
            [ 1 ] = 302006,
            [ 2 ] = 302009,
            [ 3 ] = 302012,
            [ 4 ] = 302015,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 2,
        [ "reward_id" ] = 9612,
        [ "select_num" ] = 1,
    },
    [ 43 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 43,
        [ "item_count" ] = {
            [ 1 ] = 3,
            [ 2 ] = 2,
            [ 3 ] = 2,
            [ 4 ] = 2,
        },
        [ "item_id" ] = {
            [ 1 ] = 206101,
            [ 2 ] = 206102,
            [ 3 ] = 206103,
            [ 4 ] = 206104,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 3,
        [ "reward_id" ] = 9618,
        [ "select_num" ] = 1,
    },
    [ 44 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 44,
        [ "item_count" ] = {
            [ 1 ] = 30,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 4,
        [ "reward_id" ] = 9624,
        [ "select_num" ] = 1,
    },
    [ 45 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 45,
        [ "item_count" ] = {
            [ 1 ] = 80,
        },
        [ "item_id" ] = {
            [ 1 ] = 205102,
        },
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 5,
        [ "reward_id" ] = 9630,
        [ "select_num" ] = 1,
    },
    [ 46 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 46,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 6,
        [ "reward_id" ] = 9636,
        [ "select_num" ] = 1,
    },
    [ 47 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 47,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 7,
        [ "reward_id" ] = 9642,
        [ "select_num" ] = 1,
    },
    [ 48 ] = {
        [ "activity_id" ] = 6,
        [ "id" ] = 48,
        [ "limit_num" ] = 1,
        [ "recharge_rank" ] = 8,
        [ "reward_id" ] = 9648,
        [ "select_num" ] = 1,
    },
    [ 1001 ] = {
        [ "id" ] = 1001,
        [ "level_list" ] = {
            [ 1 ] = 1,
            [ 2 ] = 10,
        },
        [ "mark" ] = true,
        [ "name" ] = "60砖石",
        [ "next_id" ] = 1006,
        [ "recharge_id" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3001,
            [ 2 ] = 3016,
        },
    },
    [ 1002 ] = {
        [ "id" ] = 1002,
        [ "level_list" ] = {
            [ 1 ] = 11,
            [ 2 ] = 20,
        },
        [ "mark" ] = true,
        [ "name" ] = "300砖石",
        [ "next_id" ] = 1007,
        [ "recharge_id" ] = 3,
        [ "recharge_rank" ] = 3,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3002,
            [ 2 ] = 3017,
        },
    },
    [ 1003 ] = {
        [ "id" ] = 1003,
        [ "level_list" ] = {
            [ 1 ] = 21,
            [ 2 ] = 30,
        },
        [ "mark" ] = true,
        [ "name" ] = "680砖石",
        [ "next_id" ] = 1008,
        [ "recharge_id" ] = 4,
        [ "recharge_rank" ] = 4,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3003,
            [ 2 ] = 3018,
        },
    },
    [ 1004 ] = {
        [ "id" ] = 1004,
        [ "level_list" ] = {
            [ 1 ] = 31,
            [ 2 ] = 40,
        },
        [ "mark" ] = true,
        [ "name" ] = "1280砖石",
        [ "next_id" ] = 1009,
        [ "recharge_id" ] = 5,
        [ "recharge_rank" ] = 5,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3004,
            [ 2 ] = 3019,
        },
    },
    [ 1005 ] = {
        [ "id" ] = 1005,
        [ "level_list" ] = {
            [ 1 ] = 41,
            [ 2 ] = 50,
        },
        [ "mark" ] = true,
        [ "name" ] = "3280砖石",
        [ "next_id" ] = 1010,
        [ "recharge_id" ] = 7,
        [ "recharge_rank" ] = 7,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3005,
            [ 2 ] = 3020,
        },
    },
    [ 1006 ] = {
        [ "id" ] = 1006,
        [ "level_list" ] = {
            [ 1 ] = 51,
            [ 2 ] = 60,
        },
        [ "mark" ] = true,
        [ "name" ] = "60砖石",
        [ "next_id" ] = 1011,
        [ "recharge_id" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3006,
            [ 2 ] = 3021,
        },
    },
    [ 1007 ] = {
        [ "id" ] = 1007,
        [ "level_list" ] = {
            [ 1 ] = 61,
            [ 2 ] = 70,
        },
        [ "mark" ] = true,
        [ "name" ] = "300砖石",
        [ "next_id" ] = 1012,
        [ "recharge_id" ] = 3,
        [ "recharge_rank" ] = 3,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3007,
            [ 2 ] = 3022,
        },
    },
    [ 1008 ] = {
        [ "id" ] = 1008,
        [ "level_list" ] = {
            [ 1 ] = 71,
            [ 2 ] = 80,
        },
        [ "mark" ] = true,
        [ "name" ] = "680砖石",
        [ "next_id" ] = 1013,
        [ "recharge_id" ] = 4,
        [ "recharge_rank" ] = 4,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3008,
            [ 2 ] = 3023,
        },
    },
    [ 1009 ] = {
        [ "id" ] = 1009,
        [ "level_list" ] = {
            [ 1 ] = 81,
            [ 2 ] = 90,
        },
        [ "mark" ] = true,
        [ "name" ] = "1280砖石",
        [ "next_id" ] = 1014,
        [ "recharge_id" ] = 5,
        [ "recharge_rank" ] = 5,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3009,
            [ 2 ] = 3024,
        },
    },
    [ 1010 ] = {
        [ "id" ] = 1010,
        [ "level_list" ] = {
            [ 1 ] = 91,
            [ 2 ] = 110,
        },
        [ "mark" ] = true,
        [ "name" ] = "3280砖石",
        [ "next_id" ] = 1015,
        [ "recharge_id" ] = 7,
        [ "recharge_rank" ] = 7,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3010,
            [ 2 ] = 3025,
        },
    },
    [ 1011 ] = {
        [ "id" ] = 1011,
        [ "level_list" ] = {
            [ 1 ] = 111,
            [ 2 ] = 130,
        },
        [ "mark" ] = true,
        [ "name" ] = "60砖石",
        [ "next_id" ] = 1001,
        [ "recharge_id" ] = 1,
        [ "recharge_rank" ] = 1,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3011,
            [ 2 ] = 3026,
        },
    },
    [ 1012 ] = {
        [ "id" ] = 1012,
        [ "level_list" ] = {
            [ 1 ] = 131,
            [ 2 ] = 150,
        },
        [ "mark" ] = true,
        [ "name" ] = "300砖石",
        [ "next_id" ] = 1002,
        [ "recharge_id" ] = 3,
        [ "recharge_rank" ] = 3,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3012,
            [ 2 ] = 3027,
        },
    },
    [ 1013 ] = {
        [ "id" ] = 1013,
        [ "level_list" ] = {
            [ 1 ] = 151,
            [ 2 ] = 170,
        },
        [ "mark" ] = true,
        [ "name" ] = "680砖石",
        [ "next_id" ] = 1003,
        [ "recharge_id" ] = 4,
        [ "recharge_rank" ] = 4,
        [ "rechargeable_times" ] = 2,
        [ "reset_cycle" ] = 1,
        [ "reward_list" ] = {
            [ 1 ] = 3013,
            [ 2 ] = 3028,
        },
    },
    [ 1014 ] = {
        [ "id" ] = 1014,
        [ "level_list" ] = {
            [ 1 ] = 171,
            [ 2 ] = 190,
        },
        [ "mark" ] = true,
        [ "name" ] = "1280砖石",
        [ "next_id" ] = 1004,
        [ "recharge_id" ] = 5,
        [ "recharge_rank" ] = 5,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3014,
            [ 2 ] = 3029,
        },
    },
    [ 1015 ] = {
        [ "id" ] = 1015,
        [ "level_list" ] = {
            [ 1 ] = 191,
            [ 2 ] = 200,
        },
        [ "mark" ] = true,
        [ "name" ] = "3280砖石",
        [ "next_id" ] = 1005,
        [ "recharge_id" ] = 7,
        [ "recharge_rank" ] = 7,
        [ "rechargeable_times" ] = 1,
        [ "reset_cycle" ] = 7,
        [ "reward_list" ] = {
            [ 1 ] = 3015,
            [ 2 ] = 3030,
        },
    },
    [ 2001 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9001,
            [ 2 ] = 9014,
            [ 3 ] = 9027,
        },
        [ "duration_days" ] = 3,
        [ "duration_sec" ] = 259200,
        [ "id" ] = 2001,
        [ "id_list" ] = {
            [ 1 ] = 2001,
            [ 2 ] = 2002,
            [ 3 ] = 2003,
            [ 4 ] = 2004,
            [ 5 ] = 2005,
            [ 6 ] = 2006,
            [ 7 ] = 2007,
            [ 8 ] = 2008,
            [ 9 ] = 2009,
            [ 10 ] = 2010,
            [ 11 ] = 2011,
            [ 12 ] = 2012,
            [ 13 ] = 2013,
            [ 14 ] = 2014,
        },
        [ "interval_days" ] = 0,
        [ "interval_sec" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 60,
        [ "recharge_amount_list" ] = {
            [ 1 ] = 60,
            [ 2 ] = 250,
            [ 3 ] = 500,
            [ 4 ] = 1500,
            [ 5 ] = 3000,
            [ 6 ] = 5000,
            [ 7 ] = 7500,
            [ 8 ] = 10000,
            [ 9 ] = 15000,
            [ 10 ] = 20000,
            [ 11 ] = 30000,
            [ 12 ] = 45000,
            [ 13 ] = 60000,
            [ 14 ] = 80000,
        },
        [ "reserve_days" ] = 1,
        [ "reserve_sec" ] = 86400,
    },
    [ 2002 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9002,
            [ 2 ] = 9015,
            [ 3 ] = 9028,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2002,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 250,
        [ "reserve_days" ] = 1,
    },
    [ 2003 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9003,
            [ 2 ] = 9016,
            [ 3 ] = 9029,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2003,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 500,
        [ "reserve_days" ] = 1,
    },
    [ 2004 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9004,
            [ 2 ] = 9017,
            [ 3 ] = 9030,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2004,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 1500,
        [ "reserve_days" ] = 1,
    },
    [ 2005 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9005,
            [ 2 ] = 9018,
            [ 3 ] = 9031,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2005,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 3000,
        [ "reserve_days" ] = 1,
    },
    [ 2006 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9006,
            [ 2 ] = 9019,
            [ 3 ] = 9032,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2006,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 5000,
        [ "reserve_days" ] = 1,
    },
    [ 2007 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9007,
            [ 2 ] = 9020,
            [ 3 ] = 9033,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2007,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 7500,
        [ "reserve_days" ] = 1,
    },
    [ 2008 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9008,
            [ 2 ] = 9021,
            [ 3 ] = 9034,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2008,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 10000,
        [ "reserve_days" ] = 1,
    },
    [ 2009 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9009,
            [ 2 ] = 9022,
            [ 3 ] = 9035,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2009,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 15000,
        [ "reserve_days" ] = 1,
    },
    [ 2010 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9010,
            [ 2 ] = 9023,
            [ 3 ] = 9036,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2010,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 20000,
        [ "reserve_days" ] = 1,
    },
    [ 2011 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9011,
            [ 2 ] = 9024,
            [ 3 ] = 9037,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2011,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 30000,
        [ "reserve_days" ] = 1,
    },
    [ 2012 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9012,
            [ 2 ] = 9025,
            [ 3 ] = 9038,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2012,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 45000,
        [ "reserve_days" ] = 1,
    },
    [ 2013 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9013,
            [ 2 ] = 9026,
            [ 3 ] = 9039,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2013,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 60000,
        [ "reserve_days" ] = 1,
    },
    [ 2014 ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9041,
            [ 2 ] = 9042,
            [ 3 ] = 9043,
        },
        [ "duration_days" ] = 3,
        [ "id" ] = 2014,
        [ "interval_days" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 80000,
        [ "reserve_days" ] = 1,
    },
    [ "accumulated_recharge_activity" ] = {
        [ "accum_level_list" ] = {
            [ 1 ] = 20,
            [ 2 ] = 50,
            [ 3 ] = 100,
        },
        [ "accum_reward_list" ] = {
            [ 1 ] = 9001,
            [ 2 ] = 9014,
            [ 3 ] = 9027,
        },
        [ "duration_days" ] = 3,
        [ "duration_sec" ] = 259200,
        [ "id" ] = 2001,
        [ "id_list" ] = {
            [ 1 ] = 2001,
            [ 2 ] = 2002,
            [ 3 ] = 2003,
            [ 4 ] = 2004,
            [ 5 ] = 2005,
            [ 6 ] = 2006,
            [ 7 ] = 2007,
            [ 8 ] = 2008,
            [ 9 ] = 2009,
            [ 10 ] = 2010,
            [ 11 ] = 2011,
            [ 12 ] = 2012,
            [ 13 ] = 2013,
            [ 14 ] = 2014,
        },
        [ "interval_days" ] = 0,
        [ "interval_sec" ] = 0,
        [ "is_accumulated_recharge_activity" ] = true,
        [ "recharge_amount" ] = 60,
        [ "recharge_amount_list" ] = {
            [ 1 ] = 60,
            [ 2 ] = 250,
            [ 3 ] = 500,
            [ 4 ] = 1500,
            [ 5 ] = 3000,
            [ 6 ] = 5000,
            [ 7 ] = 7500,
            [ 8 ] = 10000,
            [ 9 ] = 15000,
            [ 10 ] = 20000,
            [ 11 ] = 30000,
            [ 12 ] = 45000,
            [ 13 ] = 60000,
            [ 14 ] = 80000,
        },
        [ "reserve_days" ] = 1,
        [ "reserve_sec" ] = 86400,
    },
    [ "recharge_dict" ] = {
        [ 1 ] = {
            [ 1 ] = 1001,
            [ 2 ] = 1006,
            [ 3 ] = 1011,
        },
        [ 3 ] = {
            [ 1 ] = 1002,
            [ 2 ] = 1007,
            [ 3 ] = 1012,
        },
        [ 4 ] = {
            [ 1 ] = 1003,
            [ 2 ] = 1008,
            [ 3 ] = 1013,
        },
        [ 5 ] = {
            [ 1 ] = 1004,
            [ 2 ] = 1009,
            [ 3 ] = 1014,
        },
        [ 7 ] = {
            [ 1 ] = 1005,
            [ 2 ] = 1010,
            [ 3 ] = 1015,
        },
    },
}