return {
    [ 1 ] = {
        [ "activity_name" ] = "首冲礼包",
        [ "ch_key" ] = "首冲礼包",
        [ "effect" ] = "300111",
        [ "icon" ] = 2800018,
        [ "id" ] = 1,
        [ "is_show_in_mainscence" ] = true,
        [ "system_name" ] = "RechargeActivity1",
        [ "type" ] = 2,
    },
    [ 2 ] = {
        [ "activity" ] = 1,
        [ "activity_name" ] = "帮派崛起",
        [ "ch_key" ] = "寻花觅柳",
        [ "icon" ] = 2800003,
        [ "id" ] = 2,
        [ "is_show_in_mainscence" ] = true,
        [ "system_name" ] = "TLActivity1",
        [ "type" ] = 1,
    },
    [ 3 ] = {
        [ "activity" ] = 2,
        [ "activity_name" ] = "家族崛起",
        [ "ch_key" ] = "盛夏将至",
        [ "icon" ] = 2800004,
        [ "id" ] = 3,
        [ "is_show_in_mainscence" ] = true,
        [ "system_name" ] = "TLActivity2",
        [ "type" ] = 1,
    },
    [ 4 ] = {
        [ "activity_name" ] = "精良装备",
        [ "ch_key" ] = "精良装备",
        [ "icon" ] = 2800030,
        [ "id" ] = 4,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 1,
        [ "system_name" ] = "RechargeActivity2",
        [ "type" ] = 3,
    },
    [ 5 ] = {
        [ "activity_name" ] = "神秘宝物",
        [ "ch_key" ] = "神秘宝物",
        [ "icon" ] = 2800032,
        [ "id" ] = 5,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 2,
        [ "system_name" ] = "RechargeActivity3",
        [ "type" ] = 3,
    },
    [ 6 ] = {
        [ "activity_name" ] = "佳人有约",
        [ "ch_key" ] = "佳人有约",
        [ "icon" ] = 2800033,
        [ "id" ] = 6,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 3,
        [ "system_name" ] = "RechargeActivity4",
        [ "type" ] = 3,
    },
    [ 7 ] = {
        [ "activity_name" ] = "精锐头目",
        [ "ch_key" ] = "精锐头目",
        [ "icon" ] = 2800031,
        [ "id" ] = 7,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 4,
        [ "system_name" ] = "RechargeActivity5",
        [ "type" ] = 3,
    },
    [ 8 ] = {
        [ "activity_name" ] = "节日活动",
        [ "ch_key" ] = "节日活动",
        [ "effect" ] = "300111",
        [ "festival_activity" ] = 1,
        [ "icon" ] = 2800015,
        [ "id" ] = 8,
        [ "is_show_in_mainscence" ] = true,
        [ "system_name" ] = "FestivalActivity",
        [ "turn_activity" ] = 9,
        [ "type" ] = 4,
    },
    [ 9 ] = {
        [ "activity_name" ] = "活动兑换",
        [ "ch_key" ] = "活动兑换",
        [ "festival_activity" ] = 1,
        [ "icon" ] = 2800016,
        [ "id" ] = 9,
        [ "is_show_in_mainscence" ] = false,
        [ "system_name" ] = "FestivalExchange",
        [ "type" ] = 5,
    },
    [ 10 ] = {
        [ "activity_name" ] = "充值抽奖",
        [ "ch_key" ] = "充值抽奖",
        [ "effect" ] = "300111",
        [ "icon" ] = 2800019,
        [ "id" ] = 10,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 7,
        [ "system_name" ] = "RechargeDraw",
        [ "type" ] = 6,
    },
    [ 11 ] = {
        [ "activity_name" ] = "豪华签到",
        [ "ch_key" ] = "豪华签到",
        [ "icon" ] = 2800029,
        [ "id" ] = 11,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 9,
        [ "system_name" ] = "RechargeActivity6",
        [ "type" ] = 3,
    },
    [ 12 ] = {
        [ "activity_name" ] = "限时累充",
        [ "ch_key" ] = "限时累充",
        [ "icon" ] = 2800028,
        [ "id" ] = 12,
        [ "is_show_in_mainscence" ] = false,
        [ "recharge_activity" ] = 11,
        [ "system_name" ] = "RechargeActivity7",
        [ "type" ] = 3,
    },
    [ 13 ] = {
        [ "activity_name" ] = "每日礼包",
        [ "ch_key" ] = "每日礼包",
        [ "icon" ] = 2800037,
        [ "id" ] = 13,
        [ "is_show_in_mainscence" ] = true,
        [ "recharge_activity" ] = 12,
        [ "system_name" ] = "RechargeActivity8",
        [ "type" ] = 7,
    },
}