return {
    [ 1 ] = {
        [ "ch_key" ] = "狩猎积分排行",
        [ "group_id" ] = 1,
        [ "id" ] = 1,
        [ "name" ] = "狩猎积分排行",
        [ "rank_gist_name" ] = "狩猎积分",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 4,
    },
    [ 2 ] = {
        [ "ch_key" ] = "竞技场排行",
        [ "give_reward_time" ] = 22,
        [ "group_id" ] = 2,
        [ "has_reward" ] = true,
        [ "id" ] = 2,
        [ "mail_id" ] = 3,
        [ "name" ] = "竞技场排行",
        [ "rank_gist_name" ] = "战力",
        [ "rank_tag" ] = "排行",
        [ "reward_desc" ] = "奖励每日22:00发放",
        [ "reward_list" ] = {
            [ 1 ] = 21,
            [ 2 ] = 22,
            [ 3 ] = 23,
            [ 4 ] = 24,
            [ 5 ] = 25,
            [ 6 ] = 26,
            [ 7 ] = 27,
            [ 8 ] = 27,
        },
        [ "reward_tag" ] = "奖励",
        [ "reward_tier" ] = {
            [ 1 ] = 1,
            [ 2 ] = 5,
            [ 3 ] = 20,
            [ 4 ] = 50,
            [ 5 ] = 100,
            [ 6 ] = 300,
            [ 7 ] = 1000,
        },
        [ "sort" ] = 5,
    },
    [ 3 ] = {
        [ "ch_key" ] = "派对积分排行",
        [ "group_id" ] = 3,
        [ "id" ] = 3,
        [ "is_cross_server" ] = true,
        [ "name" ] = "派对积分排行",
        [ "rank_gist_name" ] = "派对积分",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 6,
    },
    [ 4 ] = {
        [ "ch_key" ] = "沙龙积分排行",
        [ "group_id" ] = 4,
        [ "id" ] = 4,
        [ "is_cross_server" ] = true,
        [ "name" ] = "沙龙积分排行",
        [ "rank_gist_name" ] = "沙龙积分",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 7,
    },
    [ 5 ] = {
        [ "ch_key" ] = "试炼排行",
        [ "group_id" ] = 5,
        [ "id" ] = 5,
        [ "name" ] = "地下黑拳排行",
        [ "rank_gist_name" ] = "星数",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 8,
    },
    [ 6 ] = {
        [ "ch_key" ] = "叛军伤害排行",
        [ "group_id" ] = 6,
        [ "has_reward" ] = true,
        [ "id" ] = 6,
        [ "mail_id" ] = 11,
        [ "name" ] = "特工对抗排行",
        [ "rank_gist_name" ] = "伤害",
        [ "rank_tag" ] = "伤害排行",
        [ "reward_desc" ] = "奖励每日00:00发放",
        [ "reward_list" ] = {
            [ 1 ] = 20001,
            [ 2 ] = 20002,
            [ 3 ] = 20003,
            [ 4 ] = 20004,
            [ 5 ] = 20005,
            [ 6 ] = 20006,
            [ 7 ] = 20007,
            [ 8 ] = 20008,
            [ 9 ] = 20009,
        },
        [ "reward_tag" ] = "奖励",
        [ "reward_tier" ] = {
            [ 1 ] = 1,
            [ 2 ] = 2,
            [ 3 ] = 3,
            [ 4 ] = 5,
            [ 5 ] = 10,
            [ 6 ] = 30,
            [ 7 ] = 50,
            [ 8 ] = 100,
            [ 9 ] = 200,
        },
        [ "sort" ] = 9,
    },
    [ 7 ] = {
        [ "ch_key" ] = "叛军功勋排行",
        [ "group_id" ] = 6,
        [ "has_reward" ] = true,
        [ "id" ] = 7,
        [ "mail_id" ] = 10,
        [ "name" ] = "对抗特工排行",
        [ "rank_gist_name" ] = "贡献",
        [ "rank_tag" ] = "贡献排行",
        [ "reward_desc" ] = "奖励每日00:00发放",
        [ "reward_list" ] = {
            [ 1 ] = 20010,
            [ 2 ] = 20011,
            [ 3 ] = 20012,
            [ 4 ] = 20013,
            [ 5 ] = 20014,
            [ 6 ] = 20015,
            [ 7 ] = 20016,
            [ 8 ] = 20017,
            [ 9 ] = 20018,
        },
        [ "reward_tag" ] = "奖励",
        [ "reward_tier" ] = {
            [ 1 ] = 1,
            [ 2 ] = 2,
            [ 3 ] = 3,
            [ 4 ] = 5,
            [ 5 ] = 10,
            [ 6 ] = 30,
            [ 7 ] = 50,
            [ 8 ] = 100,
            [ 9 ] = 200,
        },
        [ "sort" ] = 9,
    },
    [ 8 ] = {
        [ "ch_key" ] = "战力排行",
        [ "group_id" ] = 7,
        [ "id" ] = 8,
        [ "name" ] = "战力排行",
        [ "rank_gist_name" ] = "战力",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 1,
    },
    [ 9 ] = {
        [ "ch_key" ] = "帮力排行",
        [ "group_id" ] = 8,
        [ "id" ] = 9,
        [ "name" ] = "帮力排行",
        [ "rank_gist_name" ] = "帮力",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 2,
    },
    [ 10 ] = {
        [ "ch_key" ] = "等级排行",
        [ "group_id" ] = 9,
        [ "id" ] = 10,
        [ "name" ] = "等级排行",
        [ "rank_gist_name" ] = "等级",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 3,
    },
    [ 11 ] = {
        [ "ch_key" ] = "关卡星数排行",
        [ "group_id" ] = 10,
        [ "id" ] = 11,
        [ "name" ] = "关卡星数排行",
        [ "rank_gist_name" ] = "星数",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 10,
    },
    [ 12 ] = {
        [ "ch_key" ] = "限时活动排行",
        [ "group_id" ] = 11,
        [ "id" ] = 12,
        [ "name" ] = "限时活动排行",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 11,
    },
    [ 13 ] = {
        [ "ch_key" ] = "叛军boss荣誉排行",
        [ "group_id" ] = 12,
        [ "id" ] = 13,
        [ "name" ] = "本服王牌特工排行",
        [ "rank_gist_name" ] = "黑道荣誉",
        [ "rank_tag" ] = "荣誉排行",
        [ "sort" ] = 12,
    },
    [ 14 ] = {
        [ "ch_key" ] = "叛军boss最大伤害排行",
        [ "group_id" ] = 12,
        [ "id" ] = 14,
        [ "name" ] = "本服王牌特工排行",
        [ "rank_gist_name" ] = "伤害",
        [ "rank_tag" ] = "伤害排行",
        [ "sort" ] = 12,
    },
    [ 15 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服战力排行",
        [ "group_id" ] = 13,
        [ "id" ] = 15,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服战力排行",
        [ "rank_gist_name" ] = "战力",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 13,
    },
    [ 16 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服帮力排行",
        [ "group_id" ] = 14,
        [ "id" ] = 16,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服帮力排行",
        [ "rank_gist_name" ] = "帮力",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 14,
    },
    [ 17 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服关卡星数排行",
        [ "group_id" ] = 15,
        [ "id" ] = 17,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服关卡星数排行",
        [ "rank_gist_name" ] = "星数",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 15,
    },
    [ 18 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服叛军boss荣誉排行",
        [ "group_id" ] = 16,
        [ "id" ] = 18,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服特工排行",
        [ "rank_gist_name" ] = "黑道荣誉",
        [ "rank_tag" ] = "荣誉排行",
        [ "sort" ] = 16,
    },
    [ 19 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服叛军boss最大伤害排行",
        [ "group_id" ] = 17,
        [ "id" ] = 19,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服特工伤害排行",
        [ "rank_gist_name" ] = "伤害",
        [ "rank_tag" ] = "伤害排行",
        [ "sort" ] = 17,
    },
    [ 20 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服狩猎积分排行",
        [ "group_id" ] = 18,
        [ "id" ] = 20,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服狩猎积分排行",
        [ "rank_gist_name" ] = "狩猎积分",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 18,
    },
    [ 21 ] = {
        [ "all_show" ] = true,
        [ "ch_key" ] = "跨服试炼排行",
        [ "group_id" ] = 19,
        [ "id" ] = 21,
        [ "is_cross_server" ] = true,
        [ "name" ] = "跨服试炼排行",
        [ "rank_gist_name" ] = "星数",
        [ "rank_tag" ] = "排行",
        [ "sort" ] = 19,
    },
}