return {
    [ 1 ] = {
        [ "attr_name" ] = "crit",
        [ "attr_value" ] = 3,
        [ "cost_star" ] = 3,
        [ "id" ] = 1,
    },
    [ 2 ] = {
        [ "attr_name" ] = "add_hurt",
        [ "attr_value" ] = 5,
        [ "cost_star" ] = 3,
        [ "id" ] = 2,
    },
    [ 3 ] = {
        [ "attr_name" ] = "hit",
        [ "attr_value" ] = 3,
        [ "cost_star" ] = 3,
        [ "id" ] = 3,
    },
    [ 4 ] = {
        [ "attr_name" ] = "crit_def",
        [ "attr_value" ] = 3,
        [ "cost_star" ] = 3,
        [ "id" ] = 4,
    },
    [ 5 ] = {
        [ "attr_name" ] = "hurt_def",
        [ "attr_value" ] = 5,
        [ "cost_star" ] = 3,
        [ "id" ] = 5,
    },
    [ 6 ] = {
        [ "attr_name" ] = "miss",
        [ "attr_value" ] = 3,
        [ "cost_star" ] = 3,
        [ "id" ] = 6,
    },
    [ 7 ] = {
        [ "attr_name" ] = "max_hp_pct",
        [ "attr_value" ] = 5,
        [ "cost_star" ] = 3,
        [ "id" ] = 7,
    },
    [ 8 ] = {
        [ "attr_name" ] = "crit",
        [ "attr_value" ] = 6,
        [ "cost_star" ] = 6,
        [ "id" ] = 8,
    },
    [ 9 ] = {
        [ "attr_name" ] = "add_hurt",
        [ "attr_value" ] = 10,
        [ "cost_star" ] = 6,
        [ "id" ] = 9,
    },
    [ 10 ] = {
        [ "attr_name" ] = "hit",
        [ "attr_value" ] = 6,
        [ "cost_star" ] = 6,
        [ "id" ] = 10,
    },
    [ 11 ] = {
        [ "attr_name" ] = "crit_def",
        [ "attr_value" ] = 6,
        [ "cost_star" ] = 6,
        [ "id" ] = 11,
    },
    [ 12 ] = {
        [ "attr_name" ] = "hurt_def",
        [ "attr_value" ] = 10,
        [ "cost_star" ] = 6,
        [ "id" ] = 12,
    },
    [ 13 ] = {
        [ "attr_name" ] = "miss",
        [ "attr_value" ] = 6,
        [ "cost_star" ] = 6,
        [ "id" ] = 13,
    },
    [ 14 ] = {
        [ "attr_name" ] = "max_hp_pct",
        [ "attr_value" ] = 10,
        [ "cost_star" ] = 6,
        [ "id" ] = 14,
    },
    [ 15 ] = {
        [ "attr_name" ] = "crit",
        [ "attr_value" ] = 9,
        [ "cost_star" ] = 9,
        [ "id" ] = 15,
    },
    [ 16 ] = {
        [ "attr_name" ] = "add_hurt",
        [ "attr_value" ] = 15,
        [ "cost_star" ] = 9,
        [ "id" ] = 16,
    },
    [ 17 ] = {
        [ "attr_name" ] = "hit",
        [ "attr_value" ] = 9,
        [ "cost_star" ] = 9,
        [ "id" ] = 17,
    },
    [ 18 ] = {
        [ "attr_name" ] = "crit_def",
        [ "attr_value" ] = 9,
        [ "cost_star" ] = 9,
        [ "id" ] = 18,
    },
    [ 19 ] = {
        [ "attr_name" ] = "hurt_def",
        [ "attr_value" ] = 15,
        [ "cost_star" ] = 9,
        [ "id" ] = 19,
    },
    [ 20 ] = {
        [ "attr_name" ] = "miss",
        [ "attr_value" ] = 9,
        [ "cost_star" ] = 9,
        [ "id" ] = 20,
    },
    [ 21 ] = {
        [ "attr_name" ] = "max_hp_pct",
        [ "attr_value" ] = 15,
        [ "cost_star" ] = 9,
        [ "id" ] = 21,
    },
    [ "id_list" ] = {
        [ 1 ] = {
            [ 1 ] = 1,
            [ 2 ] = 2,
            [ 3 ] = 3,
            [ 4 ] = 4,
            [ 5 ] = 5,
            [ 6 ] = 6,
            [ 7 ] = 7,
        },
        [ 2 ] = {
            [ 1 ] = 8,
            [ 2 ] = 9,
            [ 3 ] = 10,
            [ 4 ] = 11,
            [ 5 ] = 12,
            [ 6 ] = 13,
            [ 7 ] = 14,
        },
        [ 3 ] = {
            [ 1 ] = 15,
            [ 2 ] = 16,
            [ 3 ] = 17,
            [ 4 ] = 18,
            [ 5 ] = 19,
            [ 6 ] = 20,
            [ 7 ] = 21,
        },
    },
}