return {
    [ 1 ] = {
        [ "ch_key" ] = "总部大厅按钮",
        [ "id" ] = 1,
        [ "path" ] = "Panel/GameScenePanel/Headquarters/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 2 ] = {
        [ "ch_key" ] = "邮件按钮",
        [ "id" ] = 2,
        [ "path" ] = "Panel/SceneMenuPanel/FoldPanel/BtnList/MailBtn",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 3 ] = {
        [ "ch_key" ] = "教父殿堂按钮",
        [ "id" ] = 3,
        [ "path" ] = "Panel/GameScenePanel/Church/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 4 ] = {
        [ "ch_key" ] = "娱乐中心按钮",
        [ "id" ] = 4,
        [ "path" ] = "Panel/GameScenePanel/Entertainment/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 5 ] = {
        [ "ch_key" ] = "出行",
        [ "id" ] = 5,
        [ "path" ] = "Panel/GameScenePanel/BigMap/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 6 ] = {
        [ "ch_key" ] = "王朝",
        [ "id" ] = 6,
        [ "path" ] = "Panel/GameScenePanel/Dynasty/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 7 ] = {
        [ "ch_key" ] = "俱乐部",
        [ "id" ] = 7,
        [ "path" ] = "Panel/GameScenePanel/NightClub/Title",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 8 ] = {
        [ "ch_key" ] = "主界面加号",
        [ "id" ] = 8,
        [ "path" ] = "Panel/SceneMenuPanel/FoldRedPoint",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 9 ] = {
        [ "ch_key" ] = "好友",
        [ "id" ] = 9,
        [ "path" ] = "Panel/SceneMenuPanel/FoldPanel/BtnList/FriendBtn",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 10 ] = {
        [ "ch_key" ] = "回收",
        [ "id" ] = 10,
        [ "path" ] = "Panel/SceneMenuPanel/FoldPanel/BtnList/DecomposeBtn",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 11 ] = {
        [ "ch_key" ] = "首周签到入口",
        [ "id" ] = 11,
        [ "path" ] = "Panel/SceneMenuPanel/CurActivityPanel/FirstWeekCheck",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 12 ] = {
        [ "ch_key" ] = "VIP入口",
        [ "id" ] = 12,
        [ "path" ] = "Panel/SceneMenuPanel/VipBtn/huanguan",
        [ "ui_name" ] = "MainSceneUI",
    },
    [ 13 ] = {
        [ "ch_key" ] = "发布命令按钮",
        [ "id" ] = 13,
        [ "path" ] = "Panel/Btn_List/Cmd_Btn",
        [ "ui_name" ] = "GreatHallUI",
    },
    [ 14 ] = {
        [ "ch_key" ] = "处理情报按钮",
        [ "id" ] = 14,
        [ "path" ] = "Panel/Btn_List/Info_Btn",
        [ "ui_name" ] = "GreatHallUI",
    },
    [ 15 ] = {
        [ "ch_key" ] = "明星酒店",
        [ "id" ] = 15,
        [ "path" ] = "Panel/GameScenePanel/CelebrityHotel/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 16 ] = {
        [ "ch_key" ] = "管理中心",
        [ "id" ] = 16,
        [ "path" ] = "Panel/GameScenePanel/ControlCenter/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 17 ] = {
        [ "ch_key" ] = "育儿所",
        [ "id" ] = 17,
        [ "path" ] = "Panel/GameScenePanel/ChildPlayground/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 18 ] = {
        [ "ch_key" ] = "婚配所",
        [ "id" ] = 18,
        [ "path" ] = "Panel/GameScenePanel/MarriageOffice/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 19 ] = {
        [ "ch_key" ] = "派对",
        [ "id" ] = 19,
        [ "path" ] = "Panel/GameScenePanel/Banquet/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 20 ] = {
        [ "ch_key" ] = "培训中心",
        [ "id" ] = 20,
        [ "path" ] = "Panel/GameScenePanel/TrainningCentre/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 21 ] = {
        [ "ch_key" ] = "沙龙",
        [ "id" ] = 21,
        [ "path" ] = "Panel/GameScenePanel/Recreation/Title",
        [ "ui_name" ] = "EntertainmentUI",
    },
    [ 22 ] = {
        [ "ch_key" ] = "随机约会",
        [ "id" ] = 22,
        [ "path" ] = "Panel/ShowLoverPanel/DownMesFrame/TurnCardButton",
        [ "ui_name" ] = "CelebrityHotelUI",
    },
    [ 23 ] = {
        [ "ch_key" ] = "膜拜按钮",
        [ "id" ] = 23,
        [ "path" ] = "Panel/BottomPanel/WorshipBtn",
        [ "ui_name" ] = "ChurchUI",
    },
    [ 24 ] = {
        [ "ch_key" ] = "监狱",
        [ "id" ] = 24,
        [ "path" ] = "Panel/GameScenePanel/GangsterPrison/Title",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 25 ] = {
        [ "ch_key" ] = "狩猎",
        [ "id" ] = 25,
        [ "path" ] = "Panel/GameScenePanel/HuntingArea/Title",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 26 ] = {
        [ "ch_key" ] = "关卡征服",
        [ "id" ] = 26,
        [ "path" ] = "Panel/GameScenePanel/GangsterMelee/Title",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 27 ] = {
        [ "ch_key" ] = "秘密出行",
        [ "id" ] = 27,
        [ "path" ] = "Panel/GameScenePanel/SecretVisit/Title",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 28 ] = {
        [ "ch_key" ] = "黑道挑战",
        [ "id" ] = 28,
        [ "path" ] = "Panel/GameScenePanel/PlaymentEntry/Title",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 29 ] = {
        [ "ch_key" ] = "大地图猎杀猛兽",
        [ "id" ] = 29,
        [ "path" ] = "Panel/GameScenePanel/ChallengeRareAnimalBtn/Text",
        [ "ui_name" ] = "BigMapUI",
    },
    [ 30 ] = {
        [ "ch_key" ] = "狩猎首通奖励",
        [ "id" ] = 30,
        [ "path" ] = "Panel/PanelList/SelectGroundPanel/BottonBar/FirstPassAwardBtn/Text",
        [ "ui_name" ] = "HuntingGroundUI",
    },
    [ 31 ] = {
        [ "ch_key" ] = "狩猎猎杀猛兽",
        [ "id" ] = 31,
        [ "path" ] = "Panel/PanelList/SelectGroundPanel/BottonBar/ChallengeRareAnimalBtn/Text",
        [ "ui_name" ] = "HuntingGroundUI",
    },
    [ 32 ] = {
        [ "ch_key" ] = "关卡一键领取",
        [ "id" ] = 32,
        [ "path" ] = "Panel/PanelList/StrategyMapUIInitialPanel/BottomBar/OneKeyGetBtn",
        [ "ui_name" ] = "StrategyMapUI",
    },
    [ 33 ] = {
        [ "ch_key" ] = "阵容入口按钮",
        [ "id" ] = 33,
        [ "path" ] = "Panel/GameMenuPanel/LineUp/Btn",
        [ "ui_name" ] = "GameMenuUI",
    },
    [ 34 ] = {
        [ "ch_key" ] = "每日目标入口按钮",
        [ "id" ] = 34,
        [ "path" ] = "Panel/GameMenuPanel/DailyTarget/Btn",
        [ "ui_name" ] = "GameMenuUI",
    },
    [ 35 ] = {
        [ "ch_key" ] = "成就入口按钮",
        [ "id" ] = 35,
        [ "path" ] = "Panel/GameMenuPanel/Achievement/Btn",
        [ "ui_name" ] = "GameMenuUI",
    },
    [ 36 ] = {
        [ "ch_key" ] = "福利入口按钮",
        [ "id" ] = 36,
        [ "path" ] = "Panel/GameMenuPanel/Welfare/Btn",
        [ "ui_name" ] = "GameMenuUI",
    },
    [ 37 ] = {
        [ "ch_key" ] = "开服基金页签",
        [ "id" ] = 37,
        [ "path" ] = "Panel/ServerFundFrame/TabPanel/ServerFund",
        [ "ui_name" ] = "WelfareUI",
    },
    [ 38 ] = {
        [ "ch_key" ] = "全民福利页签",
        [ "id" ] = 38,
        [ "path" ] = "Panel/ServerFundFrame/TabPanel/FundWelfare",
        [ "ui_name" ] = "WelfareUI",
    },
    [ 39 ] = {
        [ "ch_key" ] = "王朝管理按钮",
        [ "id" ] = 39,
        [ "path" ] = "Panel/BuildingPanel/Management/Title",
        [ "ui_name" ] = "DynastyUI",
    },
    [ 40 ] = {
        [ "ch_key" ] = "王朝事务所按钮",
        [ "id" ] = 40,
        [ "path" ] = "Panel/BuildingPanel/Office/Title",
        [ "ui_name" ] = "DynastyUI",
    },
    [ 41 ] = {
        [ "ch_key" ] = "王朝科研所按钮",
        [ "id" ] = 41,
        [ "path" ] = "Panel/BuildingPanel/Institute/Title",
        [ "ui_name" ] = "DynastyUI",
    },
    [ 42 ] = {
        [ "ch_key" ] = "王朝挑战按钮",
        [ "id" ] = 42,
        [ "path" ] = "Panel/BuildingPanel/Challenge/Title",
        [ "ui_name" ] = "DynastyUI",
    },
    [ 43 ] = {
        [ "ch_key" ] = "王朝争霸按钮",
        [ "id" ] = 43,
        [ "path" ] = "Panel/BuildingPanel/Hegemony/Title",
        [ "ui_name" ] = "DynastyUI",
    },
    [ 44 ] = {
        [ "ch_key" ] = "王朝管理页签",
        [ "id" ] = 44,
        [ "path" ] = "Panel/TabPanel/ManageBtn",
        [ "ui_name" ] = "DynastyManageUI",
    },
    [ 45 ] = {
        [ "ch_key" ] = "王朝申请",
        [ "id" ] = 45,
        [ "path" ] = "Panel/Content/ManagePanel/OpPanel/HandleApplyBtn",
        [ "ui_name" ] = "DynastyManageUI",
    },
    [ 46 ] = {
        [ "ch_key" ] = "王朝建设页签",
        [ "id" ] = 46,
        [ "path" ] = "Panel/TabPanel/BuildBtn",
        [ "ui_name" ] = "DynastyOfficeUI",
    },
    [ 47 ] = {
        [ "ch_key" ] = "王朝活跃页签",
        [ "id" ] = 47,
        [ "path" ] = "Panel/TabPanel/ActiveBtn",
        [ "ui_name" ] = "DynastyOfficeUI",
    },
    [ 48 ] = {
        [ "ch_key" ] = "科研所学习页签",
        [ "id" ] = 48,
        [ "path" ] = "Panel/TabPanel/LearnBtn",
        [ "ui_name" ] = "DynastyInstituteUI",
    },
    [ 49 ] = {
        [ "ch_key" ] = "好友申请列表",
        [ "id" ] = 49,
        [ "path" ] = "Panel/FriendListFrame/FriendListDownFrame/ApplyListBtn",
        [ "ui_name" ] = "FriendUI",
    },
    [ 50 ] = {
        [ "ch_key" ] = "分解页签",
        [ "id" ] = 50,
        [ "path" ] = "Panel/OpCatalog/Viewport/Content/DecomposeBtn",
        [ "ui_name" ] = "DecomposeUI",
    },
    [ 51 ] = {
        [ "ch_key" ] = "装备分解页签",
        [ "id" ] = 51,
        [ "path" ] = "Panel/DecomposePanel/ItemTabPanel/Viewport/Content/Equipment",
        [ "ui_name" ] = "DecomposeUI",
    },
    [ 52 ] = {
        [ "ch_key" ] = "头目碎片分解页签",
        [ "id" ] = 52,
        [ "path" ] = "Panel/DecomposePanel/ItemTabPanel/Viewport/Content/HeroFragment",
        [ "ui_name" ] = "DecomposeUI",
    },
    [ 53 ] = {
        [ "ch_key" ] = "情人碎片分解页签",
        [ "id" ] = 53,
        [ "path" ] = "Panel/DecomposePanel/ItemTabPanel/Viewport/Content/LoverFragment",
        [ "ui_name" ] = "DecomposeUI",
    },
    [ 54 ] = {
        [ "ch_key" ] = "提亲请求按钮",
        [ "id" ] = 54,
        [ "path" ] = "Panel/DownFrame/MarryRequestButton",
        [ "ui_name" ] = "LuxuryHouseUI",
    },
    [ 55 ] = {
        [ "ch_key" ] = "特工奖励按钮",
        [ "id" ] = 55,
        [ "path" ] = "Panel/InfoFrame/RewardBtn",
        [ "ui_name" ] = "TraitorPreviewUI",
    },
    [ 56 ] = {
        [ "ch_key" ] = "王牌特工入口按钮",
        [ "id" ] = 56,
        [ "path" ] = "Panel/DownFrame/BossBtn",
        [ "ui_name" ] = "TraitorPreviewUI",
    },
    [ 57 ] = {
        [ "ch_key" ] = "王牌特工奖励按钮",
        [ "id" ] = 57,
        [ "path" ] = "Panel/RewardBtn",
        [ "ui_name" ] = "TraitorBossUI",
    },
    [ 58 ] = {
        [ "ch_key" ] = "VIP商城入口",
        [ "id" ] = 58,
        [ "path" ] = "Panel/Top/VipShopBtn",
        [ "ui_name" ] = "VipUI",
    },
    [ 59 ] = {
        [ "ch_key" ] = "日常礼包页签",
        [ "id" ] = 59,
        [ "path" ] = "Panel/Middle/TagList/1",
        [ "ui_name" ] = "VipShopUI",
    },
}