return {
    [ 1 ] = {
        [ "back_icon" ] = 10043,
        [ "ch_key" ] = "男主角",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10017,
        [ "id" ] = 1,
        [ "name" ] = "男主角",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Lead/Lead_nanzhujiao/nanzhujiao_pb",
        [ "unlock_icon" ] = 10017,
    },
    [ 2 ] = {
        [ "back_icon" ] = 10044,
        [ "ch_key" ] = "女主角",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10018,
        [ "id" ] = 2,
        [ "name" ] = "男主角",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Lead/Lead_nvzhujiao/nvzhujiao_pb",
        [ "unlock_icon" ] = 10018,
    },
    [ 3 ] = {
        [ "back_icon" ] = 10043,
        [ "ch_key" ] = "男主角2",
        [ "default_anim" ] = "animation",
        [ "icon" ] = 10019,
        [ "id" ] = 3,
        [ "name" ] = "男主角2",
        [ "res_path" ] = "Unit/Lead/Lead_nanzhujue2/nanzhujue2_pb",
        [ "unlock_icon" ] = 10019,
    },
    [ 4 ] = {
        [ "back_icon" ] = 10044,
        [ "ch_key" ] = "女主角2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10020,
        [ "id" ] = 4,
        [ "name" ] = "男主角2",
        [ "res_path" ] = "Unit/Lead/Lead_nvzhujue2/nvzhujue2_pb",
        [ "unlock_icon" ] = 10020,
    },
    [ 5 ] = {
        [ "back_icon" ] = 10043,
        [ "ch_key" ] = "男主角3",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10045,
        [ "id" ] = 5,
        [ "name" ] = "男主角3",
        [ "res_path" ] = "Unit/Lead/Lead_nanzhu3/nanzhu3_pb",
        [ "unlock_icon" ] = 10045,
    },
    [ 6 ] = {
        [ "back_icon" ] = 10044,
        [ "ch_key" ] = "女主角3",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10046,
        [ "id" ] = 6,
        [ "name" ] = "女主角3",
        [ "res_path" ] = "Unit/Lead/Lead_nvzhu3/nvzhu3_pb",
        [ "unlock_icon" ] = 10046,
    },
    [ 7 ] = {
        [ "back_icon" ] = 10043,
        [ "ch_key" ] = "男主角4",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10047,
        [ "id" ] = 7,
        [ "name" ] = "男主角4",
        [ "res_path" ] = "Unit/Lead/Lead_nanzhu4/nanzhu4_pb",
        [ "unlock_icon" ] = 10047,
    },
    [ 8 ] = {
        [ "back_icon" ] = 10044,
        [ "ch_key" ] = "女主角4",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10048,
        [ "id" ] = 8,
        [ "name" ] = "女主角4",
        [ "res_path" ] = "Unit/Lead/Lead_nvzhu4/nvzhu4_pb",
        [ "unlock_icon" ] = 10048,
    },
    [ 9 ] = {
        [ "back_icon" ] = 10044,
        [ "ch_key" ] = "女主角5",
        [ "default_anim" ] = "animation",
        [ "icon" ] = 10049,
        [ "id" ] = 9,
        [ "name" ] = "女主角5",
        [ "res_path" ] = "Unit/Lead/Lead_nvkongjie/nvkongjie_pb",
        [ "unlock_icon" ] = 10049,
    },
    [ 3000 ] = {
        [ "ch_key" ] = "弗兰克",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10042,
        [ "id" ] = 3000,
        [ "name" ] = "弗兰克",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Npc/npc_fulanke/fulanke_pb",
    },
    [ 3001 ] = {
        [ "ch_key" ] = "管家",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3001,
        [ "name" ] = "管家",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3002 ] = {
        [ "ch_key" ] = "陌生人",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3002,
        [ "name" ] = "陌生人",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_jieke/jieke_pb",
    },
    [ 3003 ] = {
        [ "ch_key" ] = "陌生人2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3003,
        [ "name" ] = "陌生人",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_hengli/hengli_pb",
    },
    [ 3004 ] = {
        [ "ch_key" ] = "安娜",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3004,
        [ "name" ] = "安娜",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_zhudi/zhudi_pb",
    },
    [ 3005 ] = {
        [ "ch_key" ] = "托马斯",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3005,
        [ "name" ] = "托马斯",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Npc/npc_tuomasi/tuomasi_pb",
    },
    [ 3006 ] = {
        [ "ch_key" ] = "弗兰克_黑",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10042,
        [ "id" ] = 3006,
        [ "name" ] = "幕后黑手",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Npc/npc_fulanke/fulanke_black_pb",
    },
    [ 3007 ] = {
        [ "ch_key" ] = "玛丽",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3007,
        [ "name" ] = "玛丽",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_zhudi/zhudi_pb",
    },
    [ 3008 ] = {
        [ "ch_key" ] = "弗兰克残党1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3008,
        [ "name" ] = "弗兰克残党",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_gongqi/gongqi_pb",
    },
    [ 3009 ] = {
        [ "ch_key" ] = "弗兰克残党2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3009,
        [ "name" ] = "弗兰克残党",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_L.E/L.E_pb",
    },
    [ 3010 ] = {
        [ "ch_key" ] = "刀锋",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3010,
        [ "name" ] = "刀锋",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_huoer/huoer_pb",
    },
    [ 3011 ] = {
        [ "ch_key" ] = "帮派头目",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3011,
        [ "name" ] = "帮派头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_bier/bier_pb",
    },
    [ 3012 ] = {
        [ "ch_key" ] = "杀手男",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3012,
        [ "name" ] = "杀手",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3013 ] = {
        [ "ch_key" ] = "杀手女",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3013,
        [ "name" ] = "杀手",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_yelian/yelian_pb",
    },
    [ 3014 ] = {
        [ "ch_key" ] = "地狱帮头目1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3014,
        [ "name" ] = "地狱帮头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_dirang/dirang_pb",
    },
    [ 3015 ] = {
        [ "ch_key" ] = "地狱帮头目2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3015,
        [ "name" ] = "地狱帮头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_fan/fan_pb",
    },
    [ 3016 ] = {
        [ "ch_key" ] = "地狱帮头目3",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3016,
        [ "name" ] = "地狱帮头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_baoluo/baoluo_pb",
    },
    [ 3017 ] = {
        [ "ch_key" ] = "琼恩",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3017,
        [ "name" ] = "琼恩",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_laerfu/laerfu_pb",
    },
    [ 3018 ] = {
        [ "ch_key" ] = "托马斯亲信",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3018,
        [ "name" ] = "神秘人",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_danding/danding_pb",
    },
    [ 3019 ] = {
        [ "ch_key" ] = "战斧叛徒",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10042,
        [ "id" ] = 3019,
        [ "name" ] = "战斧叛徒",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_bier/bier_pb",
    },
    [ 3020 ] = {
        [ "ch_key" ] = "毒品供货商",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3020,
        [ "name" ] = "毒品供货商",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_samite/samite_pb",
    },
    [ 3021 ] = {
        [ "ch_key" ] = "帮派叛徒",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3021,
        [ "name" ] = "帮派叛徒",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_gongqi/gongqi_pb",
    },
    [ 3022 ] = {
        [ "ch_key" ] = "战斧头目",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3022,
        [ "name" ] = "战斧头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_luojie/luojie_pb",
    },
    [ 3023 ] = {
        [ "ch_key" ] = "剃刀头目",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3023,
        [ "name" ] = "剃刀头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_yuehan/yuehan_pb",
    },
    [ 3024 ] = {
        [ "ch_key" ] = "布兰迪",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3024,
        [ "name" ] = "布兰迪",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_dawei/dawei_pb",
    },
    [ 3025 ] = {
        [ "ch_key" ] = "西蒙",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3025,
        [ "name" ] = "西蒙",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_xiaoen/xiaoen_pb",
    },
    [ 3026 ] = {
        [ "ch_key" ] = "萨斯",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3026,
        [ "name" ] = "萨斯",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_bier/bier_pb",
    },
    [ 3027 ] = {
        [ "ch_key" ] = "黑手党头目",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3027,
        [ "name" ] = "黑手党头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_shankou/shankou_pb",
    },
    [ 3028 ] = {
        [ "ch_key" ] = "山口组头目",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3028,
        [ "name" ] = "山口组头目",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_L.E/L.E_pb",
    },
    [ 3029 ] = {
        [ "ch_key" ] = "莉莲",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 10029,
        [ "id" ] = 3029,
        [ "name" ] = "莉莲",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_meier/meier_pb",
    },
    [ 3030 ] = {
        [ "ch_key" ] = "诺德",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3030,
        [ "name" ] = "诺德",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_jiesen/jiesen_pb",
    },
    [ 3031 ] = {
        [ "ch_key" ] = "托马斯手下",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3031,
        [ "name" ] = "托马斯手下",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_bahe/bahe_pb",
    },
    [ 3032 ] = {
        [ "ch_key" ] = "托马斯亲信2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3032,
        [ "name" ] = "托马斯亲信",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_danding/danding_pb",
    },
    [ 3033 ] = {
        [ "ch_key" ] = "兰斯",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3033,
        [ "name" ] = "兰斯",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_maidi/maidi_pb",
    },
    [ 3034 ] = {
        [ "ch_key" ] = "龙套头目1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3034,
        [ "name" ] = "龙套头目1",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3035 ] = {
        [ "ch_key" ] = "龙套头目2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3035,
        [ "name" ] = "龙套头目2",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3036 ] = {
        [ "ch_key" ] = "龙套头目3",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3036,
        [ "name" ] = "龙套头目3",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3037 ] = {
        [ "ch_key" ] = "龙套头目4",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3037,
        [ "name" ] = "龙套头目4",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3038 ] = {
        [ "ch_key" ] = "龙套头目5",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3038,
        [ "name" ] = "龙套头目5",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3039 ] = {
        [ "ch_key" ] = "龙套头目6",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3039,
        [ "name" ] = "龙套头目6",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3040 ] = {
        [ "ch_key" ] = "龙套头目7",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3040,
        [ "name" ] = "龙套头目7",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3041 ] = {
        [ "ch_key" ] = "龙套头目8",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3041,
        [ "name" ] = "龙套头目8",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3042 ] = {
        [ "ch_key" ] = "龙套头目9",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3042,
        [ "name" ] = "龙套头目9",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3043 ] = {
        [ "ch_key" ] = "龙套头目10",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3043,
        [ "name" ] = "龙套头目10",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 3044 ] = {
        [ "ch_key" ] = "叛徒头目1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 3044,
        [ "name" ] = "叛徒头目1",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Npc/npc_guanjia/guanjia_pb",
    },
    [ 4001 ] = {
        [ "ch_key" ] = "豹子",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90038,
        [ "id" ] = 4001,
        [ "name" ] = "豹子",
        [ "res_path" ] = "Unit/Animal/baozi/baozi_pb",
    },
    [ 4002 ] = {
        [ "ch_key" ] = "牛",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90039,
        [ "id" ] = 4002,
        [ "name" ] = "牛",
        [ "res_path" ] = "Unit/Animal/niu/niu_pb",
    },
    [ 4003 ] = {
        [ "ch_key" ] = "兔子",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90040,
        [ "id" ] = 4003,
        [ "name" ] = "兔子",
        [ "res_path" ] = "Unit/Animal/tuzi/tuzi_pb",
    },
    [ 4004 ] = {
        [ "ch_key" ] = "猪",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90041,
        [ "id" ] = 4004,
        [ "name" ] = "猪",
        [ "res_path" ] = "Unit/Animal/zhu/zhu_pb",
    },
    [ 4005 ] = {
        [ "ch_key" ] = "北极熊",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90045,
        [ "id" ] = 4005,
        [ "name" ] = "北极熊",
        [ "res_path" ] = "Unit/Animal/beijixiong/beijixiong_pb",
    },
    [ 4006 ] = {
        [ "ch_key" ] = "袋鼠",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90046,
        [ "id" ] = 4006,
        [ "name" ] = "袋鼠",
        [ "res_path" ] = "Unit/Animal/daishu/daishu_pb",
    },
    [ 4007 ] = {
        [ "ch_key" ] = "黑熊",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90047,
        [ "id" ] = 4007,
        [ "name" ] = "黑熊",
        [ "res_path" ] = "Unit/Animal/heixiong/heixiong_pb",
    },
    [ 4008 ] = {
        [ "ch_key" ] = "角马",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90048,
        [ "id" ] = 4008,
        [ "name" ] = "角马",
        [ "res_path" ] = "Unit/Animal/jiaoma/jiaoma_pb",
    },
    [ 4009 ] = {
        [ "ch_key" ] = "牦牛",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90049,
        [ "id" ] = 4009,
        [ "name" ] = "牦牛",
        [ "res_path" ] = "Unit/Animal/maoniu/maoniu_pb",
    },
    [ 4010 ] = {
        [ "ch_key" ] = "麋鹿",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90050,
        [ "id" ] = 4010,
        [ "name" ] = "麋鹿",
        [ "res_path" ] = "Unit/Animal/milu/milu_pb",
    },
    [ 4011 ] = {
        [ "ch_key" ] = "鬣狗",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90057,
        [ "id" ] = 4011,
        [ "name" ] = "鬣狗",
        [ "res_path" ] = "Unit/Animal/liegou/liegou_pb",
    },
    [ 4012 ] = {
        [ "ch_key" ] = "狼",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90058,
        [ "id" ] = 4012,
        [ "name" ] = "狼",
        [ "res_path" ] = "Unit/Animal/lang/lang_pb",
    },
    [ 4013 ] = {
        [ "ch_key" ] = "狮子",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90059,
        [ "id" ] = 4013,
        [ "name" ] = "狮子",
        [ "res_path" ] = "Unit/Animal/shizi/shizi_pb",
    },
    [ 4014 ] = {
        [ "ch_key" ] = "虎",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90060,
        [ "id" ] = 4014,
        [ "name" ] = "虎",
        [ "res_path" ] = "Unit/Animal/laohu/laohu_pb",
    },
    [ 4015 ] = {
        [ "ch_key" ] = "鹿",
        [ "default_anim" ] = "run",
        [ "icon" ] = 90061,
        [ "id" ] = 4015,
        [ "name" ] = "鹿",
        [ "res_path" ] = "Unit/Animal/lu/lu_pb",
    },
    [ 5001 ] = {
        [ "ch_key" ] = "犯人男",
        [ "circle_icon" ] = 100003,
        [ "default_anim" ] = "idle",
        [ "id" ] = 5001,
        [ "name" ] = "犯人男",
        [ "res_path" ] = "Unit/Prisoner/qiufannan/qiufannan_pb",
    },
    [ 5002 ] = {
        [ "ch_key" ] = "犯人女",
        [ "circle_icon" ] = 100001,
        [ "default_anim" ] = "idle",
        [ "id" ] = 5002,
        [ "name" ] = "犯人女",
        [ "res_path" ] = "Unit/Prisoner/qiufannv/qiufannv_pb",
    },
    [ 6001 ] = {
        [ "ch_key" ] = "鞭子",
        [ "default_anim" ] = "animation",
        [ "id" ] = 6001,
        [ "name" ] = "鞭子",
        [ "res_path" ] = "Unit/Other/Prison/bianzi/bianzi_pb",
    },
    [ 6002 ] = {
        [ "ch_key" ] = "飞镖",
        [ "id" ] = 6002,
        [ "name" ] = "飞镖",
        [ "res_path" ] = "Unit/Other/feibiao/Dart",
    },
    [ 7001 ] = {
        [ "ch_key" ] = "成年男1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 7001,
        [ "name" ] = "成年男1",
        [ "res_path" ] = "Unit/children/chengniannan/chengniannan_pb",
    },
    [ 7002 ] = {
        [ "ch_key" ] = "成年女1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 7002,
        [ "name" ] = "成年女1",
        [ "res_path" ] = "Unit/children/chengniannan/chengniannv_pb",
    },
    [ 7003 ] = {
        [ "ch_key" ] = "成年男黑",
        [ "default_anim" ] = "animation",
        [ "id" ] = 7003,
        [ "name" ] = "成年男黑",
        [ "res_path" ] = "Unit/children/heirenchengniannan/heinan_chengnian_pb",
    },
    [ 7004 ] = {
        [ "ch_key" ] = "成年女黑",
        [ "default_anim" ] = "idle",
        [ "id" ] = 7004,
        [ "name" ] = "成年女黑",
        [ "res_path" ] = "Unit/children/heirenchengniannv/heinv_chengnian_pb",
    },
    [ 8001 ] = {
        [ "ch_key" ] = "男婴儿白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140004,
        [ "id" ] = 8001,
        [ "name" ] = "男婴儿白_1",
        [ "res_path" ] = "Unit/children/baobaonan/nan_baobao_pb",
    },
    [ 8002 ] = {
        [ "ch_key" ] = "女婴儿白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140005,
        [ "id" ] = 8002,
        [ "name" ] = "女婴儿白_1",
        [ "res_path" ] = "Unit/children/baobaonv/nv_baobao_pb",
    },
    [ 8003 ] = {
        [ "ch_key" ] = "男孩子白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140006,
        [ "id" ] = 8003,
        [ "name" ] = "男孩子白_1",
        [ "res_path" ] = "Unit/children/ertongnan/nan_haizi_pb",
    },
    [ 8004 ] = {
        [ "ch_key" ] = "女孩子白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140007,
        [ "id" ] = 8004,
        [ "name" ] = "女孩子白_1",
        [ "res_path" ] = "Unit/children/ertongnv/nv_haizi_pb",
    },
    [ 8005 ] = {
        [ "ch_key" ] = "男成年白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140008,
        [ "id" ] = 8005,
        [ "name" ] = "男成年白_1",
        [ "res_path" ] = "Unit/children/chengniannan/nan_chengnian_pb",
    },
    [ 8006 ] = {
        [ "ch_key" ] = "女成年白_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140009,
        [ "id" ] = 8006,
        [ "name" ] = "女成年白_1",
        [ "res_path" ] = "Unit/children/chengniannv/nv_chengnian_pb",
    },
    [ 8007 ] = {
        [ "ch_key" ] = "男婴儿黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140021,
        [ "id" ] = 8007,
        [ "name" ] = "男婴儿黑_1",
        [ "res_path" ] = "Unit/children/heirennanbaobao/heinan_baobao_pb",
    },
    [ 8008 ] = {
        [ "ch_key" ] = "女婴儿黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140016,
        [ "id" ] = 8008,
        [ "name" ] = "女婴儿黑_1",
        [ "res_path" ] = "Unit/children/heirennvbaobao/heinv_baobao_pb",
    },
    [ 8009 ] = {
        [ "ch_key" ] = "男孩子黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140019,
        [ "id" ] = 8009,
        [ "name" ] = "男孩子黑_1",
        [ "res_path" ] = "Unit/children/heirenertongnan/heinan_haizi_pb",
    },
    [ 8010 ] = {
        [ "ch_key" ] = "女孩子黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140017,
        [ "id" ] = 8010,
        [ "name" ] = "女孩子黑_1",
        [ "res_path" ] = "Unit/children/heirenertongnv/heinv_haizi_pb",
    },
    [ 8011 ] = {
        [ "ch_key" ] = "男成年黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140010,
        [ "id" ] = 8011,
        [ "name" ] = "男成年黑_1",
        [ "res_path" ] = "Unit/children/heirenchengniannan/heinan_chengnian_pb",
    },
    [ 8012 ] = {
        [ "ch_key" ] = "女成年黑_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140012,
        [ "id" ] = 8012,
        [ "name" ] = "女成年黑_1",
        [ "res_path" ] = "Unit/children/heirenchengniannv/heinv_chengnian_pb",
    },
    [ 8013 ] = {
        [ "ch_key" ] = "男婴儿黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140014,
        [ "id" ] = 8013,
        [ "name" ] = "男婴儿黄_1",
        [ "res_path" ] = "Unit/children/huangrennanbaobao/huangnan_baobao_pb",
    },
    [ 8014 ] = {
        [ "ch_key" ] = "女婴儿黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -138,
            [ 2 ] = -196,
        },
        [ "icon" ] = 140015,
        [ "id" ] = 8014,
        [ "name" ] = "女婴儿黄_1",
        [ "res_path" ] = "Unit/children/huangrennvbaobao/huangnv_baobao_pb",
    },
    [ 8015 ] = {
        [ "ch_key" ] = "男孩子黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140020,
        [ "id" ] = 8015,
        [ "name" ] = "男孩子黄_1",
        [ "res_path" ] = "Unit/children/huangrenertongnan/huangnan_haizi_pb",
    },
    [ 8016 ] = {
        [ "ch_key" ] = "女孩子黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -186,
            [ 2 ] = -50.5,
        },
        [ "icon" ] = 140018,
        [ "id" ] = 8016,
        [ "name" ] = "女孩子黄_1",
        [ "res_path" ] = "Unit/children/huangrenertongnv/huangnv_haizi_pb",
    },
    [ 8017 ] = {
        [ "ch_key" ] = "男成年黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140011,
        [ "id" ] = 8017,
        [ "name" ] = "男成年黄_1",
        [ "res_path" ] = "Unit/children/huangrenchengniannan/huangnan_chengnian_pb",
    },
    [ 8018 ] = {
        [ "ch_key" ] = "女成年黄_1",
        [ "dialog_pos" ] = {
            [ 1 ] = -176,
            [ 2 ] = -13,
        },
        [ "icon" ] = 140013,
        [ "id" ] = 8018,
        [ "name" ] = "女成年黄_1",
        [ "res_path" ] = "Unit/children/huangrenchengniannv/huangnv_chengnian_pb",
    },
    [ 9001 ] = {
        [ "ch_key" ] = "琳恩自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9001,
        [ "name" ] = "琳恩自慰",
        [ "res_path" ] = "Unit/Video/lover_lingen_sex/lover_lingen_sex_pb",
    },
    [ 9002 ] = {
        [ "ch_key" ] = "菲欧娜自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9002,
        [ "name" ] = "菲欧娜自慰",
        [ "res_path" ] = "Unit/Video/lover_feiounan_sex/lover_feiounan_sex_pb",
    },
    [ 9003 ] = {
        [ "ch_key" ] = "海蒂自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9003,
        [ "name" ] = "海蒂自慰",
        [ "res_path" ] = "Unit/Video/lover_haidi_sex/lover_haidi_sex_pb",
    },
    [ 9004 ] = {
        [ "ch_key" ] = "rose自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9004,
        [ "name" ] = "rose自慰",
        [ "res_path" ] = "Unit/Video/lover_rose_sex/lover_rose_sex_pb",
    },
    [ 9005 ] = {
        [ "ch_key" ] = "索菲亚自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9005,
        [ "name" ] = "索菲亚自慰",
        [ "res_path" ] = "Unit/Video/lover_suofeiya_sex/lover_suofeiya_sex_pb",
    },
    [ 9006 ] = {
        [ "ch_key" ] = "维多利亚自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9006,
        [ "name" ] = "维多利亚自慰",
        [ "res_path" ] = "Unit/Video/lover_weiduoliya_sex/lover_weiduoliya_sex_pb",
    },
    [ 9007 ] = {
        [ "ch_key" ] = "杰西卡自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9007,
        [ "name" ] = "杰西卡自慰",
        [ "res_path" ] = "Unit/Video/lover_jiexika_sex/lover_jiexika_sex_pb",
    },
    [ 9008 ] = {
        [ "ch_key" ] = "莉莉自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9008,
        [ "name" ] = "莉莉自慰",
        [ "res_path" ] = "Unit/Video/lover_lili_sex/lover_lili_sex_pb",
    },
    [ 9009 ] = {
        [ "ch_key" ] = "塔琳娜自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9009,
        [ "name" ] = "塔琳娜自慰",
        [ "res_path" ] = "Unit/Video/lover_talina_sex/lover_talina_sex_pb",
    },
    [ 9010 ] = {
        [ "ch_key" ] = "伊芙琳自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9010,
        [ "name" ] = "伊芙琳自慰",
        [ "res_path" ] = "Unit/Video/lover_yifulin_sex/lover_yifulin_sex_pb",
    },
    [ 9011 ] = {
        [ "ch_key" ] = "艾米自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9011,
        [ "name" ] = "艾米自慰",
        [ "res_path" ] = "Unit/Video/lover_aimi_sex/lover_aimi_sex_pb",
    },
    [ 9012 ] = {
        [ "ch_key" ] = "莫妮卡自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9012,
        [ "name" ] = "莫妮卡自慰",
        [ "res_path" ] = "Unit/Video/lover_monika_sex/lover_monika_sex_pb",
    },
    [ 9013 ] = {
        [ "ch_key" ] = "伊丽莎白自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9013,
        [ "name" ] = "伊丽莎白自慰",
        [ "res_path" ] = "Unit/Video/lover_yilishabai_sex/lover_yilishabai_sex_pb",
    },
    [ 9014 ] = {
        [ "ch_key" ] = "章亦灵自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9014,
        [ "name" ] = "章亦灵自慰",
        [ "res_path" ] = "Unit/Video/lover_zhangyilin_sex/lover_zhangyilin_sex_pb",
    },
    [ 9015 ] = {
        [ "ch_key" ] = "邦妮自慰",
        [ "default_anim" ] = "idle",
        [ "id" ] = 9015,
        [ "name" ] = "邦妮自慰",
        [ "res_path" ] = "Unit/Video/lover_bangni_sex/lover_bangni_sex_pb",
    },
    [ 11011 ] = {
        [ "ch_key" ] = "大卫",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011011,
        [ "id" ] = 11011,
        [ "model_path" ] = "Unit/Hero3D/dawei_3d_pb",
        [ "name" ] = "柯尔特",
        [ "res_path" ] = "Unit/Hero/hero_dawei/dawei_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11012 ] = {
        [ "ch_key" ] = "特蕾莎",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011012,
        [ "id" ] = 11012,
        [ "model_path" ] = "Unit/Hero3D/teleisha_3d_pb",
        [ "name" ] = "特蕾莎",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_teleisha/teleisha_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11021 ] = {
        [ "ch_key" ] = "亚当",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011021,
        [ "id" ] = 11021,
        [ "model_path" ] = "Unit/Hero3D/yadang_3d_pb",
        [ "name" ] = "亚当",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_yadang/yadang_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11022 ] = {
        [ "ch_key" ] = "维克托",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011022,
        [ "id" ] = 11022,
        [ "model_path" ] = "Unit/Hero3D/weiketuo_3d_pb",
        [ "name" ] = "维克托",
        [ "res_path" ] = "Unit/Hero/hero_weiketuo/weiketuo_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11031 ] = {
        [ "ch_key" ] = "凯瑟琳",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011031,
        [ "id" ] = 11031,
        [ "model_path" ] = "Unit/Hero3D/kaiselin_3d_pb",
        [ "name" ] = "代号：六",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Hero/hero_kaiselin/kaiselin_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11032 ] = {
        [ "ch_key" ] = "杰克",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011032,
        [ "id" ] = 11032,
        [ "model_path" ] = "Unit/Hero3D/jieke_3d_pb",
        [ "name" ] = "赫克托",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_jieke/jieke_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11042 ] = {
        [ "ch_key" ] = "亨利",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011042,
        [ "id" ] = 11042,
        [ "model_path" ] = "Unit/Hero3D/hengli_3d_pb",
        [ "name" ] = "亨利",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Hero/hero_hengli/hengli_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11043 ] = {
        [ "ch_key" ] = "戴维",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011041,
        [ "id" ] = 11043,
        [ "model_path" ] = "Unit/Hero3D/daiwei_3d_pb",
        [ "name" ] = "戴维",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_daiwei/daiwei_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11051 ] = {
        [ "ch_key" ] = "Sakura",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011051,
        [ "id" ] = 11051,
        [ "model_path" ] = "Unit/Hero3D/sakura_3d_pb",
        [ "name" ] = "Sakura",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Hero/hero_sakura/sakura_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11052 ] = {
        [ "ch_key" ] = "贝蒂",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011052,
        [ "id" ] = 11052,
        [ "model_path" ] = "Unit/Hero3D/beidi_3d_pb",
        [ "name" ] = "贝蒂",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_beidi/beidi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11061 ] = {
        [ "ch_key" ] = "威廉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011061,
        [ "id" ] = 11061,
        [ "model_path" ] = "Unit/Hero3D/weilian_3d_pb",
        [ "name" ] = "威廉",
        [ "res_path" ] = "Unit/Hero/hero_weilian/weilian_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 11062 ] = {
        [ "ch_key" ] = "琼斯",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50011062,
        [ "id" ] = 11062,
        [ "model_path" ] = "Unit/Hero3D/qiongsi_3d_pb",
        [ "name" ] = "阿尔法",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_qiongsi/qiongsi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12011 ] = {
        [ "ch_key" ] = "伊万",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012011,
        [ "id" ] = 12011,
        [ "model_path" ] = "Unit/Hero3D/yiwan_3d_pb",
        [ "name" ] = "伊万",
        [ "res_path" ] = "Unit/Hero/hero_yiwan/yiwan_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12012 ] = {
        [ "ch_key" ] = "克里斯",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012012,
        [ "id" ] = 12012,
        [ "model_path" ] = "Unit/Hero3D/kelisi_3d_pb",
        [ "name" ] = "道格拉斯",
        [ "res_path" ] = "Unit/Hero/hero_kelisi/kelisi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12021 ] = {
        [ "ch_key" ] = "麦迪",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012021,
        [ "id" ] = 12021,
        [ "model_path" ] = "Unit/Hero3D/maidi_3d_pb",
        [ "name" ] = "约翰",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_maidi/maidi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12023 ] = {
        [ "ch_key" ] = "扎西罗",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012022,
        [ "id" ] = 12023,
        [ "model_path" ] = "Unit/Hero3D/zhaxiluo_3d_pb",
        [ "name" ] = "扎西罗",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_zhaxiluo/zhaxiluo_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12031 ] = {
        [ "ch_key" ] = "艾伦",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012031,
        [ "id" ] = 12031,
        [ "model_path" ] = "Unit/Hero3D/ailun_3d_pb",
        [ "name" ] = "艾伦",
        [ "res_path" ] = "Unit/Hero/hero_ailun/ailun_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12032 ] = {
        [ "ch_key" ] = "欧文",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012032,
        [ "id" ] = 12032,
        [ "model_path" ] = "Unit/Hero3D/ouwen_3d_pb",
        [ "name" ] = "欧文",
        [ "res_path" ] = "Unit/Hero/hero_ouwen/ouwen_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12041 ] = {
        [ "ch_key" ] = "卡尔",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012041,
        [ "id" ] = 12041,
        [ "model_path" ] = "Unit/Hero3D/kaer_3d_pb",
        [ "name" ] = "毒蝎",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Hero/hero_kaer/kaer_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12042 ] = {
        [ "ch_key" ] = "杰森",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012042,
        [ "id" ] = 12042,
        [ "model_path" ] = "Unit/Hero3D/jiesen_3d_pb",
        [ "name" ] = "杰森",
        [ "res_path" ] = "Unit/Hero/hero_jiesen/jiesen_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12051 ] = {
        [ "ch_key" ] = "拉尔夫",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012051,
        [ "id" ] = 12051,
        [ "model_path" ] = "Unit/Hero3D/laerfu_3d_pb",
        [ "name" ] = "朱可夫",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_laerfu/laerfu_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12052 ] = {
        [ "ch_key" ] = "巴赫",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012052,
        [ "id" ] = 12052,
        [ "model_path" ] = "Unit/Hero3D/bahe_3d_pb",
        [ "name" ] = "巴赫",
        [ "res_path" ] = "Unit/Hero/hero_bahe/bahe_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12061 ] = {
        [ "ch_key" ] = "霍尔",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012061,
        [ "id" ] = 12061,
        [ "model_path" ] = "Unit/Hero3D/huoer_3d_pb",
        [ "name" ] = "剃刀",
        [ "res_path" ] = "Unit/Hero/hero_huoer/huoer_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 12062 ] = {
        [ "ch_key" ] = "但丁",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50012062,
        [ "id" ] = 12062,
        [ "model_path" ] = "Unit/Hero3D/danding_3d_pb",
        [ "name" ] = "但丁",
        [ "res_path" ] = "Unit/Hero/hero_danding/danding_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13011 ] = {
        [ "ch_key" ] = "远藤银次",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013011,
        [ "id" ] = 13011,
        [ "model_path" ] = "Unit/Hero3D/yuantengyinci_3d_pb",
        [ "name" ] = "远藤银次",
        [ "res_path" ] = "Unit/Hero/hero_yuantengyyinci/yuantengyinci_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13012 ] = {
        [ "ch_key" ] = "鬼宗",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013012,
        [ "id" ] = 13012,
        [ "model_path" ] = "Unit/Hero3D/guizong_3d_pb",
        [ "name" ] = "龙王",
        [ "res_path" ] = "Unit/Hero/hero_guizong/guizong_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13021 ] = {
        [ "ch_key" ] = "阿龙",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013021,
        [ "id" ] = 13021,
        [ "model_path" ] = "Unit/Hero3D/along_3d_pb",
        [ "name" ] = "李龙",
        [ "res_path" ] = "Unit/Hero/hero_along/along_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13022 ] = {
        [ "ch_key" ] = "叶莲",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013022,
        [ "id" ] = 13022,
        [ "model_path" ] = "Unit/Hero3D/yelian_3d_pb",
        [ "name" ] = "叶莲",
        [ "res_path" ] = "Unit/Hero/hero_yelian/yelian_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13031 ] = {
        [ "ch_key" ] = "肖恩",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013031,
        [ "id" ] = 13031,
        [ "model_path" ] = "Unit/Hero3D/xiaoen_3d_pb",
        [ "name" ] = "卡萨",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_xiaoen/xiaoen_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13041 ] = {
        [ "ch_key" ] = "黑蛇",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013041,
        [ "id" ] = 13041,
        [ "model_path" ] = "Unit/Hero3D/heishe_3d_pb",
        [ "name" ] = "黑蛇",
        [ "res_path" ] = "Unit/Hero/hero_heishe/heishe_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13042 ] = {
        [ "ch_key" ] = "梵",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013042,
        [ "id" ] = 13042,
        [ "model_path" ] = "Unit/Hero3D/fan_3d_pb",
        [ "name" ] = "梵",
        [ "res_path" ] = "Unit/Hero/hero_fan/fan_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13043 ] = {
        [ "ch_key" ] = "嘉米",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013032,
        [ "id" ] = 13043,
        [ "model_path" ] = "Unit/Hero3D/jiami_3d_pb",
        [ "name" ] = "嘉米",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_jiami/jiami_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13051 ] = {
        [ "ch_key" ] = "迪让",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013051,
        [ "id" ] = 13051,
        [ "model_path" ] = "Unit/Hero3D/dirang_3d_pb",
        [ "name" ] = "迪让",
        [ "res_path" ] = "Unit/Hero/hero_dirang/dirang_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13052 ] = {
        [ "ch_key" ] = "萨米特",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013052,
        [ "id" ] = 13052,
        [ "model_path" ] = "Unit/Hero3D/samite_3d_pb",
        [ "name" ] = "蜘蛛",
        [ "res_path" ] = "Unit/Hero/hero_samite/samite_pb",
        [ "unit_scale" ] = 1.05,
    },
    [ 13053 ] = {
        [ "ch_key" ] = "送葬者",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013062,
        [ "id" ] = 13053,
        [ "model_path" ] = "Unit/Hero3D/songzangzhe_3d_pb",
        [ "name" ] = "收割者",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_songzangzhe/songzangzhe_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 13061 ] = {
        [ "ch_key" ] = "LE",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50013061,
        [ "id" ] = 13061,
        [ "model_path" ] = "Unit/Hero3D/L.E_3d_pb",
        [ "name" ] = "LE",
        [ "res_path" ] = "Unit/Hero/hero_L.E/L.E_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14011 ] = {
        [ "ch_key" ] = "安德鲁",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014011,
        [ "id" ] = 14011,
        [ "model_path" ] = "Unit/Hero3D/andelu_3d_pb",
        [ "name" ] = "布莱尼亚克",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_andelu/andelu_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14012 ] = {
        [ "ch_key" ] = "茱迪",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014022,
        [ "id" ] = 14012,
        [ "model_path" ] = "Unit/Hero3D/zhudi_3d_pb",
        [ "name" ] = "米娅",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_zhudi/zhudi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14021 ] = {
        [ "ch_key" ] = "约翰",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014021,
        [ "id" ] = 14021,
        [ "model_path" ] = "Unit/Hero3D/yuehan_3d_pb",
        [ "name" ] = "链锯",
        [ "res_path" ] = "Unit/Hero/hero_yuehan/yuehan_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14022 ] = {
        [ "ch_key" ] = "保罗",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014012,
        [ "id" ] = 14022,
        [ "model_path" ] = "Unit/Hero3D/baoluo_3d_pb",
        [ "name" ] = "保罗",
        [ "res_path" ] = "Unit/Hero/hero_baoluo/baoluo_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14031 ] = {
        [ "ch_key" ] = "韩朴仁",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014031,
        [ "id" ] = 14031,
        [ "model_path" ] = "Unit/Hero3D/hanpuren_3d_pb",
        [ "name" ] = "韩朴仁",
        [ "res_path" ] = "Unit/Hero/hero_hanpuren/hanpuren_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14032 ] = {
        [ "ch_key" ] = "梅尔",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014032,
        [ "id" ] = 14032,
        [ "model_path" ] = "Unit/Hero3D/meier_3d_pb",
        [ "name" ] = "梅尔",
        [ "res_path" ] = "Unit/Hero/hero_meier/meier_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14041 ] = {
        [ "ch_key" ] = "比尔",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014041,
        [ "id" ] = 14041,
        [ "model_path" ] = "Unit/Hero3D/bier_3d_pb",
        [ "name" ] = "比尔",
        [ "res_path" ] = "Unit/Hero/hero_bier/bier_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14042 ] = {
        [ "ch_key" ] = "罗杰",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014042,
        [ "id" ] = 14042,
        [ "model_path" ] = "Unit/Hero3D/luojie_3d_pb",
        [ "name" ] = "罗杰",
        [ "res_path" ] = "Unit/Hero/hero_luojie/luojie_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14051 ] = {
        [ "ch_key" ] = "萨拉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014051,
        [ "id" ] = 14051,
        [ "model_path" ] = "Unit/Hero3D/sala_3d_pb",
        [ "name" ] = "萨拉",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_sala/sala_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14052 ] = {
        [ "ch_key" ] = "乔治",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014052,
        [ "id" ] = 14052,
        [ "model_path" ] = "Unit/Hero3D/qiaozhi_3d_pb",
        [ "name" ] = "乔治",
        [ "res_path" ] = "Unit/Hero/hero_qiaozhi/qiaozhi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14061 ] = {
        [ "ch_key" ] = "D-13",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014061,
        [ "id" ] = 14061,
        [ "model_path" ] = "Unit/Hero3D/D13_3d_pb",
        [ "name" ] = "赫里奥",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/D-13/D13_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 14062 ] = {
        [ "ch_key" ] = "乔瑟夫",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50014062,
        [ "id" ] = 14062,
        [ "model_path" ] = "Unit/Hero3D/qiaosefu_3d_pb",
        [ "name" ] = "乔瑟夫",
        [ "res_path" ] = "Unit/Hero/hero_qiaosefu/qiaosefu_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 21011 ] = {
        [ "ch_key" ] = "伊芙琳",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80004,
        [ "id" ] = 21011,
        [ "lover_detail_stand_pos_x" ] = 48,
        [ "name" ] = "伊芙琳",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_yifulin/yifulin_pb",
    },
    [ 21012 ] = {
        [ "ch_key" ] = "伊芙琳坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80004,
        [ "id" ] = 21012,
        [ "name" ] = "伊芙琳坐姿",
        [ "res_path" ] = "Unit/Lover/lover_yifulinzuozi/yifulinzuozi_pb",
        [ "spoil_pos_y" ] = -451,
    },
    [ 21021 ] = {
        [ "ch_key" ] = "杰西卡",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80002,
        [ "id" ] = 21021,
        [ "lover_detail_stand_pos_x" ] = 85,
        [ "name" ] = "杰西卡",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_jiexika/jiexika_pb",
    },
    [ 21022 ] = {
        [ "ch_key" ] = "杰西卡坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80002,
        [ "id" ] = 21022,
        [ "name" ] = "杰西卡坐姿",
        [ "res_path" ] = "Unit/Lover/lover_jiexikazuozi/jiexikazuozi_pb",
        [ "spoil_pos_y" ] = -1361,
    },
    [ 21031 ] = {
        [ "ch_key" ] = "莉莉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80012,
        [ "id" ] = 21031,
        [ "lover_detail_stand_pos_x" ] = 67,
        [ "name" ] = "莉莉",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_lili/lili_pb",
    },
    [ 21032 ] = {
        [ "ch_key" ] = "莉莉坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80012,
        [ "id" ] = 21032,
        [ "name" ] = "莉莉坐姿",
        [ "res_path" ] = "Unit/Lover/lover_lilizuozi/lilizuozi_pb",
        [ "spoil_pos_y" ] = -1179,
    },
    [ 21041 ] = {
        [ "ch_key" ] = "娜塔莉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80006,
        [ "id" ] = 21041,
        [ "name" ] = "娜塔莉",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_talina/talina_pb",
    },
    [ 21042 ] = {
        [ "ch_key" ] = "娜塔莉坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80006,
        [ "id" ] = 21042,
        [ "name" ] = "娜塔莉坐姿",
        [ "res_path" ] = "Unit/Lover/lover_talinazuozi/talinazuozi_pb",
        [ "spoil_pos_y" ] = -1299,
    },
    [ 21051 ] = {
        [ "ch_key" ] = "凯莉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80001,
        [ "id" ] = 21051,
        [ "lover_detail_stand_pos_x" ] = 70,
        [ "name" ] = "凯莉",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_kaili/kaili_pb",
    },
    [ 21052 ] = {
        [ "ch_key" ] = "凯莉坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80001,
        [ "id" ] = 21052,
        [ "name" ] = "凯莉坐姿",
        [ "res_path" ] = "Unit/Lover/lover_kailizuozi/kailizuozi_pb",
        [ "spoil_pos_y" ] = -1348,
    },
    [ 21061 ] = {
        [ "ch_key" ] = "佐伊",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80005,
        [ "id" ] = 21061,
        [ "lover_detail_stand_pos_x" ] = 79,
        [ "name" ] = "佐伊",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_zuoyi/zuoyi_pb",
    },
    [ 21062 ] = {
        [ "ch_key" ] = "佐伊坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80005,
        [ "id" ] = 21062,
        [ "name" ] = "佐伊坐姿",
        [ "res_path" ] = "Unit/Lover/lover_zuoyizuozi/zuoyizuozi_pb",
        [ "spoil_pos_y" ] = -1315,
    },
    [ 22011 ] = {
        [ "ch_key" ] = "娜斯提娅",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80007,
        [ "id" ] = 22011,
        [ "lover_detail_stand_pos_x" ] = 98,
        [ "name" ] = "娜斯提娅",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_nasitiya/nasitiya_pb",
    },
    [ 22012 ] = {
        [ "ch_key" ] = "娜斯提娅坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80007,
        [ "id" ] = 22012,
        [ "name" ] = "娜斯提娅坐姿",
        [ "res_path" ] = "Unit/Lover/lover_nasitiyazuozi/nasitiyazuozi_pb",
        [ "spoil_pos_y" ] = -1330,
    },
    [ 22021 ] = {
        [ "ch_key" ] = "莫妮卡",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80014,
        [ "id" ] = 22021,
        [ "lover_detail_stand_pos_x" ] = 76,
        [ "name" ] = "莫妮卡",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_monika/monika_pb",
    },
    [ 22022 ] = {
        [ "ch_key" ] = "莫妮卡坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80014,
        [ "id" ] = 22022,
        [ "name" ] = "莫妮卡坐姿",
        [ "res_path" ] = "Unit/Lover/lover_monikazuozi/monikazuozi_pb",
        [ "spoil_pos_y" ] = -1363,
    },
    [ 22031 ] = {
        [ "ch_key" ] = "伊丽莎白",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80003,
        [ "id" ] = 22031,
        [ "lover_detail_stand_pos_x" ] = 83,
        [ "name" ] = "伊丽莎白",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_yilishabai/yilishabai_pb",
    },
    [ 22032 ] = {
        [ "ch_key" ] = "伊丽莎白坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80003,
        [ "id" ] = 22032,
        [ "name" ] = "伊丽莎白坐姿",
        [ "res_path" ] = "Unit/Lover/lover_yilishabaizuo/yilishabaizuo_pb",
        [ "spoil_pos_y" ] = -384,
    },
    [ 22041 ] = {
        [ "ch_key" ] = "伊莎贝拉",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80008,
        [ "id" ] = 22041,
        [ "lover_detail_stand_pos_x" ] = 46,
        [ "name" ] = "伊莎贝拉",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_yishabeila/yishabeila_pb",
    },
    [ 22042 ] = {
        [ "ch_key" ] = "伊莎贝拉坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80008,
        [ "id" ] = 22042,
        [ "name" ] = "伊莎贝拉坐姿",
        [ "res_path" ] = "Unit/Lover/lover_yishabeilazuozi/yishabeilazuozi_pb",
        [ "spoil_pos_y" ] = -1407,
    },
    [ 22051 ] = {
        [ "ch_key" ] = "海蒂",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80009,
        [ "id" ] = 22051,
        [ "lover_detail_stand_pos_x" ] = 48,
        [ "name" ] = "海蒂",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_haidi/haidi_pb",
    },
    [ 22052 ] = {
        [ "ch_key" ] = "海蒂坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80009,
        [ "id" ] = 22052,
        [ "name" ] = "海蒂坐姿",
        [ "res_path" ] = "Unit/Lover/lover_haidizuozi/haidizuozi_pb",
        [ "spoil_pos_y" ] = -1353,
    },
    [ 22061 ] = {
        [ "ch_key" ] = "维多利亚",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80022,
        [ "id" ] = 22061,
        [ "lover_detail_stand_pos_x" ] = 139,
        [ "name" ] = "维多利亚",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/weiduoliya/weiduoliya_pb",
    },
    [ 22062 ] = {
        [ "ch_key" ] = "维多利亚坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80022,
        [ "id" ] = 22062,
        [ "name" ] = "维多利亚坐姿",
        [ "res_path" ] = "Unit/Lover/weiduoliyazuozi/weiduoliyazuozi_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 23011 ] = {
        [ "ch_key" ] = "中岛希子",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80011,
        [ "id" ] = 23011,
        [ "lover_detail_stand_pos_x" ] = 52,
        [ "name" ] = "中岛希子",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_zhongdaoxizi/zhongdaoxizi_pb",
    },
    [ 23012 ] = {
        [ "ch_key" ] = "中岛希子坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80011,
        [ "id" ] = 23012,
        [ "name" ] = "中岛希子坐姿",
        [ "res_path" ] = "Unit/Lover/lover_zhongdaoxizizuozi/zhongdaoxizizuozi_pb",
        [ "spoil_pos_y" ] = -1324,
    },
    [ 23021 ] = {
        [ "ch_key" ] = "章亦灵",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80013,
        [ "id" ] = 23021,
        [ "lover_detail_stand_pos_x" ] = 104,
        [ "name" ] = "章亦灵",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_zhangyiling/zhangyiling_pb",
    },
    [ 23022 ] = {
        [ "ch_key" ] = "章亦灵坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80013,
        [ "id" ] = 23022,
        [ "name" ] = "章亦灵坐姿",
        [ "res_path" ] = "Unit/Lover/lover_zhangyilingzuozi/zhangyilingzuozi_pb",
        [ "spoil_pos_y" ] = -1318,
    },
    [ 23031 ] = {
        [ "ch_key" ] = "爱丽丝",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80024,
        [ "id" ] = 23031,
        [ "lover_detail_stand_pos_x" ] = 67,
        [ "name" ] = "爱丽丝",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_ailisi/ailisi_pb",
    },
    [ 23032 ] = {
        [ "ch_key" ] = "爱丽丝坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80024,
        [ "id" ] = 23032,
        [ "name" ] = "爱丽丝坐姿",
        [ "res_path" ] = "Unit/Lover/lover_ailisizuozi/ailisizuozi_pb",
        [ "spoil_pos_y" ] = -1344,
    },
    [ 23033 ] = {
        [ "ch_key" ] = "艾米时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80016,
        [ "id" ] = 23033,
        [ "name" ] = "艾米时装1",
        [ "res_path" ] = "Unit/Lover/lover_aimi_2/lover_aimi_2_pb",
        [ "spoil_pos_y" ] = -836,
    },
    [ 23034 ] = {
        [ "ch_key" ] = "艾米时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80016,
        [ "id" ] = 23034,
        [ "name" ] = "艾米时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment0701/prefab_spine_uigirl_bigappointment0701_pb",
        [ "spoil_pos_y" ] = -836,
    },
    [ 23035 ] = {
        [ "ch_key" ] = "菲欧娜时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80019,
        [ "id" ] = 23035,
        [ "name" ] = "菲欧娜时装1",
        [ "res_path" ] = "Unit/Lover/lover_feiounan_2/lover_feiounan_2_pb",
    },
    [ 23036 ] = {
        [ "ch_key" ] = "菲欧娜时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80019,
        [ "id" ] = 23036,
        [ "name" ] = "菲欧娜时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1802/prefab_spine_uigirl_bigappointment1802_pb",
        [ "spoil_pos_y" ] = -1336,
    },
    [ 23037 ] = {
        [ "ch_key" ] = "海蒂时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80009,
        [ "id" ] = 23037,
        [ "name" ] = "海蒂时装1",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1301/prefab_spine_uigirl_bigappointment1301_pb",
    },
    [ 23038 ] = {
        [ "ch_key" ] = "海蒂时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80009,
        [ "id" ] = 23038,
        [ "name" ] = "海蒂时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1601/prefab_spine_uigirl_bigappointment1601_pb",
        [ "spoil_pos_y" ] = -1353,
    },
    [ 23039 ] = {
        [ "ch_key" ] = "杰西卡时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80002,
        [ "id" ] = 23039,
        [ "name" ] = "杰西卡时装1",
        [ "res_path" ] = "Unit/Lover/lover_jiexika_2/lover_jiexika_2_pb",
    },
    [ 23040 ] = {
        [ "ch_key" ] = "杰西卡时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80002,
        [ "id" ] = 23040,
        [ "name" ] = "杰西卡时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1201/prefab_spine_uigirl_bigappointment1201_pb",
        [ "spoil_pos_y" ] = -1361,
    },
    [ 23041 ] = {
        [ "ch_key" ] = "Rose",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80010,
        [ "id" ] = 23041,
        [ "lover_detail_stand_pos_x" ] = 92,
        [ "name" ] = "Rose",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_rose/rose_pb",
    },
    [ 23042 ] = {
        [ "ch_key" ] = "Rose坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80010,
        [ "id" ] = 23042,
        [ "name" ] = "Rose坐姿",
        [ "res_path" ] = "Unit/Lover/lover_rosezuozi/rosezuozi_pb",
        [ "spoil_pos_y" ] = -1337,
    },
    [ 23051 ] = {
        [ "ch_key" ] = "艾玛",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80015,
        [ "id" ] = 23051,
        [ "lover_detail_stand_pos_x" ] = 53,
        [ "name" ] = "艾玛",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_aima/aima_pb",
    },
    [ 23052 ] = {
        [ "ch_key" ] = "艾玛坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80015,
        [ "id" ] = 23052,
        [ "name" ] = "艾玛坐姿",
        [ "res_path" ] = "Unit/Lover/lover_aimazuozi/aimazuozi_pb",
        [ "spoil_pos_y" ] = -1064,
    },
    [ 23061 ] = {
        [ "ch_key" ] = "艾米",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80016,
        [ "id" ] = 23061,
        [ "lover_detail_stand_pos_x" ] = 90,
        [ "name" ] = "艾米",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_aimi/aimi_pb",
    },
    [ 23062 ] = {
        [ "ch_key" ] = "艾米坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80016,
        [ "id" ] = 23062,
        [ "name" ] = "艾米坐姿",
        [ "res_path" ] = "Unit/Lover/lover_aimizuozi/aimizuozi_pb",
        [ "spoil_pos_y" ] = -836,
    },
    [ 24011 ] = {
        [ "ch_key" ] = "艾琳娜",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80018,
        [ "id" ] = 24011,
        [ "lover_detail_stand_pos_x" ] = 59,
        [ "name" ] = "艾琳娜",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_ailinna/ailinna_pb",
    },
    [ 24012 ] = {
        [ "ch_key" ] = "艾琳娜坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80018,
        [ "id" ] = 24012,
        [ "name" ] = "艾琳娜坐姿",
        [ "res_path" ] = "Unit/Lover/lover_ailinnazuozi/ailinnazuozi_pb",
        [ "spoil_pos_y" ] = -1195,
    },
    [ 24021 ] = {
        [ "ch_key" ] = "菲欧娜",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80019,
        [ "id" ] = 24021,
        [ "lover_detail_stand_pos_x" ] = 27,
        [ "name" ] = "菲欧娜",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_feiounan/feiounan_pb",
    },
    [ 24022 ] = {
        [ "ch_key" ] = "菲欧娜坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80019,
        [ "id" ] = 24022,
        [ "name" ] = "菲欧娜坐姿",
        [ "res_path" ] = "Unit/Lover/lover_feiounazuozi/feiounazuozi_pb",
        [ "spoil_pos_y" ] = -1336,
    },
    [ 24031 ] = {
        [ "ch_key" ] = "索菲亚",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80023,
        [ "id" ] = 24031,
        [ "lover_detail_stand_pos_x" ] = 67,
        [ "name" ] = "索菲亚",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_suofeiya/suofeiya_pb",
    },
    [ 24032 ] = {
        [ "ch_key" ] = "索菲亚坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80023,
        [ "id" ] = 24032,
        [ "name" ] = "索菲亚坐姿",
        [ "res_path" ] = "Unit/Lover/lover_suofeiyazuozi/suofeiyazuozi_pb",
        [ "spoil_pos_y" ] = -1344,
    },
    [ 24041 ] = {
        [ "ch_key" ] = "苏珊",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80020,
        [ "id" ] = 24041,
        [ "lover_detail_stand_pos_x" ] = 46,
        [ "name" ] = "苏珊",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_sanshanzhanzi/sanshan_pb",
    },
    [ 24042 ] = {
        [ "ch_key" ] = "苏珊坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80020,
        [ "id" ] = 24042,
        [ "name" ] = "苏珊坐姿",
        [ "res_path" ] = "Unit/Lover/lover_sushanzuozi/sushanzuozi_pb",
        [ "spoil_pos_y" ] = -1407,
    },
    [ 24051 ] = {
        [ "ch_key" ] = "邦妮",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80017,
        [ "id" ] = 24051,
        [ "lover_detail_stand_pos_x" ] = 139,
        [ "name" ] = "邦妮",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_bangni/bangni_pb",
    },
    [ 24052 ] = {
        [ "ch_key" ] = "邦妮坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80017,
        [ "id" ] = 24052,
        [ "name" ] = "邦妮坐姿",
        [ "res_path" ] = "Unit/Lover/lover_bangnizuozi/bangnizuozi_pb",
        [ "spoil_pos_y" ] = -1218,
    },
    [ 24061 ] = {
        [ "ch_key" ] = "琳恩",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80021,
        [ "id" ] = 24061,
        [ "lover_detail_stand_pos_x" ] = 37,
        [ "name" ] = "琳恩",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_lingen/lingen_pb",
    },
    [ 24062 ] = {
        [ "ch_key" ] = "琳恩坐姿",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80021,
        [ "id" ] = 24062,
        [ "name" ] = "琳恩坐姿",
        [ "res_path" ] = "Unit/Lover/lover_linenzuozi/linenzuozi_pb",
        [ "spoil_pos_y" ] = -1344,
    },
    [ 25001 ] = {
        [ "ch_key" ] = "琳恩卡时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80021,
        [ "id" ] = 25001,
        [ "name" ] = "琳恩卡时装1",
        [ "res_path" ] = "Unit/Lover/lover_lingen_2/lover_lingen_2_pb",
    },
    [ 25002 ] = {
        [ "ch_key" ] = "琳恩卡时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80021,
        [ "id" ] = 25002,
        [ "name" ] = "琳恩卡时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3201/prefab_spine_uigirl_bigappointment3201_pb",
        [ "spoil_pos_y" ] = -1344,
    },
    [ 25003 ] = {
        [ "ch_key" ] = "伊芙琳时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80004,
        [ "id" ] = 25003,
        [ "name" ] = "伊芙琳时装1",
        [ "res_path" ] = "Unit/Lover/lover_yifulin_2/lover_yifulin_2_pb",
    },
    [ 25004 ] = {
        [ "ch_key" ] = "伊芙琳时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80004,
        [ "id" ] = 25004,
        [ "name" ] = "伊芙琳时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment2002/prefab_spine_uigirl_bigappointment2002_pb",
        [ "spoil_pos_y" ] = -451,
    },
    [ 25005 ] = {
        [ "ch_key" ] = "中岛希子时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80011,
        [ "id" ] = 25005,
        [ "name" ] = "中岛希子时装1",
        [ "res_path" ] = "Unit/Lover/lover_zhongdaoxizi_2/lover_zhongdaoxizi_2_pb",
    },
    [ 25006 ] = {
        [ "ch_key" ] = "中岛希子时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80011,
        [ "id" ] = 25006,
        [ "name" ] = "中岛希子时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3902/prefab_spine_uigirl_bigappointment3902_pb",
        [ "spoil_pos_y" ] = -1361,
    },
    [ 25007 ] = {
        [ "ch_key" ] = "维多利亚时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80022,
        [ "id" ] = 25007,
        [ "name" ] = "维多利亚时装1",
        [ "res_path" ] = "Unit/Lover/lover_weiduoliya_2/lover_weiduoliya_2_pb",
    },
    [ 25008 ] = {
        [ "ch_key" ] = "维多利亚时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80022,
        [ "id" ] = 25008,
        [ "name" ] = "维多利亚时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3601/prefab_spine_uigirl_bigappointment3601_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25009 ] = {
        [ "ch_key" ] = "爱丽丝时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80024,
        [ "id" ] = 25009,
        [ "name" ] = "爱丽丝时装1",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3702/prefab_spine_uigirl_bigappointment3702_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25010 ] = {
        [ "ch_key" ] = "莉莉时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80012,
        [ "id" ] = 25010,
        [ "name" ] = "莉莉时装1",
        [ "res_path" ] = "Unit/Lover/lover_lili_2/lover_lili_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25011 ] = {
        [ "ch_key" ] = "Rose时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80010,
        [ "id" ] = 25011,
        [ "name" ] = "Rose时装1",
        [ "res_path" ] = "Unit/Lover/lover_rose_2/lover_rose_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25012 ] = {
        [ "ch_key" ] = "索菲亚时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80023,
        [ "id" ] = 25012,
        [ "name" ] = "索菲亚时装1",
        [ "res_path" ] = "Unit/Lover/lover_suofeiya_2/lover_suofeiya_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25013 ] = {
        [ "ch_key" ] = "伊丽莎白时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80003,
        [ "id" ] = 25013,
        [ "name" ] = "伊丽莎白时装1",
        [ "res_path" ] = "Unit/Lover/lover_yilishabai_2/lover_yilishabai_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25014 ] = {
        [ "ch_key" ] = "苏珊时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80020,
        [ "id" ] = 25014,
        [ "name" ] = "苏珊时装1",
        [ "res_path" ] = "Unit/Lover/lover_sanshanzhanzi_2/lover_sanshanzhanzi_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25015 ] = {
        [ "ch_key" ] = "伊莎贝拉时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80008,
        [ "id" ] = 25015,
        [ "name" ] = "伊莎贝拉时装1",
        [ "res_path" ] = "Unit/Lover/lover_yishabeila_2/lover_yishabeila_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25016 ] = {
        [ "ch_key" ] = "娜塔莉时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80006,
        [ "id" ] = 25016,
        [ "name" ] = "娜塔莉时装1",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3401/prefab_spine_uigirl_bigappointment3401_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25017 ] = {
        [ "ch_key" ] = "艾米漏胸",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80016,
        [ "id" ] = 25017,
        [ "name" ] = "艾米漏胸",
        [ "res_path" ] = "Unit/Lover/lover_aimi_nude/lover_aimi_nude_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25018 ] = {
        [ "ch_key" ] = "琳恩漏胸",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80021,
        [ "id" ] = 25018,
        [ "name" ] = "琳恩漏胸",
        [ "res_path" ] = "Unit/Lover/lover_lingen_nude/lover_lingen_nude_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25019 ] = {
        [ "ch_key" ] = "爱丽丝时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80024,
        [ "id" ] = 25019,
        [ "name" ] = "爱丽丝时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3701/prefab_spine_uigirl_bigappointment3701_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25020 ] = {
        [ "ch_key" ] = "莉莉时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80012,
        [ "id" ] = 25020,
        [ "name" ] = "莉莉时装2",
        [ "res_path" ] = "Unit/Lover/lover_lili_4/lover_lili_4_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25021 ] = {
        [ "ch_key" ] = "Rose时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80010,
        [ "id" ] = 25021,
        [ "name" ] = "Rose时装2",
        [ "res_path" ] = "Unit/Lover/lover_rose_4/lover_rose_4_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25022 ] = {
        [ "ch_key" ] = "索菲亚时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80023,
        [ "id" ] = 25022,
        [ "name" ] = "索菲亚时装2",
        [ "res_path" ] = "Unit/Lover/lover_suofeiya_4/lover_suofeiya_4_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25023 ] = {
        [ "ch_key" ] = "伊丽莎白时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80003,
        [ "id" ] = 25023,
        [ "name" ] = "伊丽莎白时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3402/prefab_spine_uigirl_bigappointment3402_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25024 ] = {
        [ "ch_key" ] = "苏珊时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80020,
        [ "id" ] = 25024,
        [ "name" ] = "苏珊时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3502/prefab_spine_uigirl_bigappointment3502_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25025 ] = {
        [ "ch_key" ] = "伊莎贝拉时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80008,
        [ "id" ] = 25025,
        [ "name" ] = "伊莎贝拉时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1701/prefab_spine_uigirl_bigappointment1701_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25026 ] = {
        [ "ch_key" ] = "娜塔莉时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80006,
        [ "id" ] = 25026,
        [ "name" ] = "娜塔莉时装2",
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3302/prefab_spine_uigirl_bigappointment3302_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25027 ] = {
        [ "ch_key" ] = "娜塔莉漏胸",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80006,
        [ "id" ] = 25027,
        [ "name" ] = "娜塔莉漏胸",
        [ "res_path" ] = "Unit/Lover/lover_talina_nude/lover_talina_nude_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25028 ] = {
        [ "ch_key" ] = "莫妮卡时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80014,
        [ "id" ] = 25028,
        [ "lover_detail_stand_pos_x" ] = 76,
        [ "name" ] = "莫妮卡时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_monika_2/lover_monika_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25029 ] = {
        [ "ch_key" ] = "莫妮卡时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80014,
        [ "id" ] = 25029,
        [ "lover_detail_stand_pos_x" ] = 76,
        [ "name" ] = "莫妮卡时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_monika_4/lover_monika_4_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25030 ] = {
        [ "ch_key" ] = "艾琳娜时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80018,
        [ "id" ] = 25030,
        [ "lover_detail_stand_pos_x" ] = 59,
        [ "name" ] = "艾琳娜时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment1401/prefab_spine_uigirl_bigappointment1401_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25031 ] = {
        [ "ch_key" ] = "艾琳娜时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80018,
        [ "id" ] = 25031,
        [ "lover_detail_stand_pos_x" ] = 59,
        [ "name" ] = "艾琳娜时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3501/prefab_spine_uigirl_bigappointment3501_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25032 ] = {
        [ "ch_key" ] = "艾玛时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80015,
        [ "id" ] = 25032,
        [ "lover_detail_stand_pos_x" ] = 53,
        [ "name" ] = "艾玛时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_aima_2/lover_aima_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25033 ] = {
        [ "ch_key" ] = "艾玛时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80015,
        [ "id" ] = 25033,
        [ "lover_detail_stand_pos_x" ] = 53,
        [ "name" ] = "艾玛时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3802/prefab_spine_uigirl_bigappointment3802_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25034 ] = {
        [ "ch_key" ] = "邦妮时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80017,
        [ "id" ] = 25034,
        [ "lover_detail_stand_pos_x" ] = 139,
        [ "name" ] = "邦妮时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_bangni_2/lover_bangni_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25035 ] = {
        [ "ch_key" ] = "邦妮时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80017,
        [ "id" ] = 25035,
        [ "lover_detail_stand_pos_x" ] = 139,
        [ "name" ] = "邦妮时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3602/prefab_spine_uigirl_bigappointment3602_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25036 ] = {
        [ "ch_key" ] = "凯莉时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80001,
        [ "id" ] = 25036,
        [ "lover_detail_stand_pos_x" ] = 70,
        [ "name" ] = "凯莉时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_kaili_2/lover_kaili_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25037 ] = {
        [ "ch_key" ] = "凯莉时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80001,
        [ "id" ] = 25037,
        [ "lover_detail_stand_pos_x" ] = 70,
        [ "name" ] = "凯莉时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment2101/prefab_spine_uigirl_bigappointment2101_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25038 ] = {
        [ "ch_key" ] = "娜斯提娅时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80007,
        [ "id" ] = 25038,
        [ "lover_detail_stand_pos_x" ] = 98,
        [ "name" ] = "娜斯提娅时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_nasitiya_2/lover_nasitiya_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25039 ] = {
        [ "ch_key" ] = "娜斯提娅时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80007,
        [ "id" ] = 25039,
        [ "lover_detail_stand_pos_x" ] = 98,
        [ "name" ] = "娜斯提娅时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment0901/prefab_spine_uigirl_bigappointment0901_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25040 ] = {
        [ "ch_key" ] = "章亦灵时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80013,
        [ "id" ] = 25040,
        [ "lover_detail_stand_pos_x" ] = 104,
        [ "name" ] = "章亦灵时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_zhangyiling_2/lover_zhangyiling_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25041 ] = {
        [ "ch_key" ] = "章亦灵时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80013,
        [ "id" ] = 25041,
        [ "lover_detail_stand_pos_x" ] = 104,
        [ "name" ] = "章亦灵时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3504/prefab_spine_uigirl_bigappointment3504_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25042 ] = {
        [ "ch_key" ] = "佐伊时装1",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80005,
        [ "id" ] = 25042,
        [ "lover_detail_stand_pos_x" ] = 79,
        [ "name" ] = "佐伊时装1",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_zuoyi_2/lover_zuoyi_2_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25043 ] = {
        [ "ch_key" ] = "佐伊时装2",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80005,
        [ "id" ] = 25043,
        [ "lover_detail_stand_pos_x" ] = 79,
        [ "name" ] = "佐伊时装2",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment0501/prefab_spine_uigirl_bigappointment0501_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25044 ] = {
        [ "ch_key" ] = "苏珊漏胸",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80020,
        [ "id" ] = 25044,
        [ "lover_detail_stand_pos_x" ] = 79,
        [ "name" ] = "苏珊漏胸",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/lover_sushan_nude/lover_sushan_nude_pb",
        [ "spoil_pos_y" ] = -1325,
    },
    [ 25045 ] = {
        [ "ch_key" ] = "宠爱模型",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 80015,
        [ "id" ] = 25045,
        [ "name" ] = "宠爱模型",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Lover/prefab_spine_uigirl_bigappointment3501/prefab_spine_uigirl_bigappointment3501_pb",
    },
    [ 30001 ] = {
        [ "ch_key" ] = "裸体1",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30001,
        [ "name" ] = "裸体1",
        [ "res_path" ] = "Unit/Dialogue/lover_001/lover_001_pb",
    },
    [ 30002 ] = {
        [ "ch_key" ] = "裸体2",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30002,
        [ "name" ] = "裸体2",
        [ "res_path" ] = "Unit/Dialogue/lover_002/lover_002_pb",
    },
    [ 30003 ] = {
        [ "ch_key" ] = "裸体3",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30003,
        [ "name" ] = "裸体3",
        [ "res_path" ] = "Unit/Dialogue/lover_003/lover_003_pb",
    },
    [ 30004 ] = {
        [ "ch_key" ] = "裸体4",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30004,
        [ "name" ] = "裸体4",
        [ "res_path" ] = "Unit/Dialogue/lover_004/lover_004_pb",
    },
    [ 30005 ] = {
        [ "ch_key" ] = "裸体5",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30005,
        [ "name" ] = "裸体5",
        [ "res_path" ] = "Unit/Dialogue/lover_005/lover_005_pb",
    },
    [ 30006 ] = {
        [ "ch_key" ] = "裸体6",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30006,
        [ "name" ] = "裸体6",
        [ "res_path" ] = "Unit/Dialogue/lover_006/lover_006_pb",
    },
    [ 30007 ] = {
        [ "ch_key" ] = "裸体7",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30007,
        [ "name" ] = "裸体7",
        [ "res_path" ] = "Unit/Dialogue/lover_007/lover_007_pb",
    },
    [ 30008 ] = {
        [ "ch_key" ] = "裸体8",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30008,
        [ "name" ] = "裸体8",
        [ "res_path" ] = "Unit/Dialogue/lover_008/lover_008_pb",
    },
    [ 30009 ] = {
        [ "ch_key" ] = "裸体9",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30009,
        [ "name" ] = "裸体9",
        [ "res_path" ] = "Unit/Dialogue/lover_009/lover_009_pb",
    },
    [ 30010 ] = {
        [ "ch_key" ] = "裸体10",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30010,
        [ "name" ] = "裸体10",
        [ "res_path" ] = "Unit/Dialogue/lover_010/lover_010_pb",
    },
    [ 30011 ] = {
        [ "ch_key" ] = "裸体11",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30011,
        [ "name" ] = "裸体11",
        [ "res_path" ] = "Unit/Dialogue/lover_011/lover_011_pb",
    },
    [ 30012 ] = {
        [ "ch_key" ] = "裸体12",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30012,
        [ "name" ] = "裸体12",
        [ "res_path" ] = "Unit/Dialogue/lover_012/lover_012_pb",
    },
    [ 30013 ] = {
        [ "ch_key" ] = "裸体13",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30013,
        [ "name" ] = "裸体13",
        [ "res_path" ] = "Unit/Dialogue/lover_013/lover_013_pb",
    },
    [ 30014 ] = {
        [ "ch_key" ] = "裸体14",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30014,
        [ "name" ] = "裸体14",
        [ "res_path" ] = "Unit/Dialogue/lover_014/lover_014_pb",
    },
    [ 30015 ] = {
        [ "ch_key" ] = "裸体15",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30015,
        [ "name" ] = "裸体15",
        [ "res_path" ] = "Unit/Dialogue/lover_015/lover_015_pb",
    },
    [ 30016 ] = {
        [ "ch_key" ] = "裸体16",
        [ "default_anim" ] = "idle",
        [ "id" ] = 30016,
        [ "name" ] = "裸体16",
        [ "res_path" ] = "Unit/Dialogue/lover_016/lover_016_pb",
    },
    [ 35001 ] = {
        [ "ch_key" ] = "汤姆",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035001,
        [ "id" ] = 35001,
        [ "model_path" ] = "Unit/Hero3D/tangmu_3d_pb",
        [ "name" ] = "汤姆",
        [ "oriented" ] = 2,
        [ "res_path" ] = "Unit/Hero/hero_tangmu/tangmu_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35002 ] = {
        [ "ch_key" ] = "亚伯",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035002,
        [ "id" ] = 35002,
        [ "model_path" ] = "Unit/Hero3D/yabo_3d_pb",
        [ "name" ] = "亚伯",
        [ "oriented" ] = 2,
        [ "res_path" ] = "Unit/Hero/hero_yabo/yabo_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35003 ] = {
        [ "ch_key" ] = "宫崎龙井",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035003,
        [ "id" ] = 35003,
        [ "model_path" ] = "Unit/Hero3D/gongqi_3d_pb",
        [ "name" ] = "宫崎龙井",
        [ "res_path" ] = "Unit/Hero/hero_gongqi/gongqi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35004 ] = {
        [ "ch_key" ] = "山口平胜",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035004,
        [ "id" ] = 35004,
        [ "model_path" ] = "Unit/Hero3D/shankou_3d_pb",
        [ "name" ] = "山口平胜",
        [ "oriented" ] = 0,
        [ "res_path" ] = "Unit/Hero/hero_shankou/shankou_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35005 ] = {
        [ "ch_key" ] = "路易斯",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035005,
        [ "id" ] = 35005,
        [ "model_path" ] = "Unit/Hero3D/luyisi_3d_pb",
        [ "name" ] = "路易斯",
        [ "oriented" ] = 1,
        [ "res_path" ] = "Unit/Hero/hero_luyisi/luyisi_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35006 ] = {
        [ "ch_key" ] = "丹尼尔",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035006,
        [ "id" ] = 35006,
        [ "model_path" ] = "Unit/Hero3D/dannier_3d_pb",
        [ "name" ] = "丹尼尔",
        [ "res_path" ] = "Unit/Hero/hero_dannier/dannier_pb",
        [ "unit_scale" ] = 0.05,
    },
    [ 35009 ] = {
        [ "ch_key" ] = "阿雄",
        [ "default_anim" ] = "idle",
        [ "icon" ] = 50035009,
        [ "id" ] = 35009,
        [ "model_path" ] = "Unit/Hero3D/axiong_3d_pb",
        [ "name" ] = "阿雄",
        [ "res_path" ] = "Unit/Hero/hero_axiong/axiong_pb",
        [ "unit_scale" ] = 1.05,
    },
    [ 100001 ] = {
        [ "ch_key" ] = "一级士兵",
        [ "default_anim" ] = "beimian_idle",
        [ "id" ] = 100001,
        [ "name" ] = "一级士兵",
        [ "res_path" ] = "Unit/Soldier/soldier_nvjiqiangbing/nvjiqiangbing_pb",
        [ "unit_scale" ] = 1,
    },
    [ 100002 ] = {
        [ "ch_key" ] = "二级士兵",
        [ "default_anim" ] = "beimian_idle",
        [ "id" ] = 100002,
        [ "name" ] = "二级士兵",
        [ "res_path" ] = "Unit/Soldier/soldier_nanshouqiangbing1/nanshouqiangbing_pb",
        [ "unit_scale" ] = 1,
    },
    [ 100003 ] = {
        [ "ch_key" ] = "三级士兵",
        [ "default_anim" ] = "beimian_idle",
        [ "id" ] = 100003,
        [ "name" ] = "三级士兵",
        [ "res_path" ] = "Unit/Soldier/soldier_nanshouqiangbing2/nanshouqiangbing2_pb",
        [ "unit_scale" ] = 1,
    },
    [ 100004 ] = {
        [ "ch_key" ] = "四级士兵",
        [ "default_anim" ] = "beimian_idle",
        [ "id" ] = 100004,
        [ "name" ] = "四级士兵",
        [ "res_path" ] = "Unit/Soldier/soldier_zhandouxiaobing__beimian/motuobei_pb",
        [ "unit_scale" ] = 1,
    },
    [ 110001 ] = {
        [ "ch_key" ] = "旗帜1",
        [ "default_anim" ] = "hdlm_01",
        [ "id" ] = 110001,
        [ "name" ] = "战斧",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110002 ] = {
        [ "ch_key" ] = "旗帜2",
        [ "default_anim" ] = "hdlm_02",
        [ "id" ] = 110002,
        [ "name" ] = "黑手党",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110003 ] = {
        [ "ch_key" ] = "旗帜3",
        [ "default_anim" ] = "hdlm_03",
        [ "id" ] = 110003,
        [ "name" ] = "剃刀党",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110004 ] = {
        [ "ch_key" ] = "旗帜4",
        [ "default_anim" ] = "hdlm_04",
        [ "id" ] = 110004,
        [ "name" ] = "马赛黑帮",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110005 ] = {
        [ "ch_key" ] = "旗帜5",
        [ "default_anim" ] = "hdlm_05",
        [ "id" ] = 110005,
        [ "name" ] = "Bandidos",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110006 ] = {
        [ "ch_key" ] = "旗帜6",
        [ "default_anim" ] = "hdlm_06",
        [ "id" ] = 110006,
        [ "name" ] = "Shadow",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110007 ] = {
        [ "ch_key" ] = "旗帜7",
        [ "default_anim" ] = "jwbp_01",
        [ "id" ] = 110007,
        [ "name" ] = "山口组",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110008 ] = {
        [ "ch_key" ] = "旗帜8",
        [ "default_anim" ] = "jwbp_02",
        [ "id" ] = 110008,
        [ "name" ] = "华青帮",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110009 ] = {
        [ "ch_key" ] = "旗帜9",
        [ "default_anim" ] = "jwbp_03",
        [ "id" ] = 110009,
        [ "name" ] = "avenger",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110010 ] = {
        [ "ch_key" ] = "旗帜10",
        [ "default_anim" ] = "jwbp_04",
        [ "id" ] = 110010,
        [ "name" ] = "蝮蛇",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110011 ] = {
        [ "ch_key" ] = "旗帜11",
        [ "default_anim" ] = "jwbp_05",
        [ "id" ] = 110011,
        [ "name" ] = "Black Rise",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110012 ] = {
        [ "ch_key" ] = "旗帜12",
        [ "default_anim" ] = "jwbp_06",
        [ "id" ] = 110012,
        [ "name" ] = "17U",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110013 ] = {
        [ "ch_key" ] = "旗帜13",
        [ "default_anim" ] = "jzbp_01",
        [ "id" ] = 110013,
        [ "name" ] = "捷尔达诺家族",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110014 ] = {
        [ "ch_key" ] = "旗帜14",
        [ "default_anim" ] = "jzbp_02",
        [ "id" ] = 110014,
        [ "name" ] = "甘比诺家族",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110015 ] = {
        [ "ch_key" ] = "旗帜15",
        [ "default_anim" ] = "jzbp_03",
        [ "id" ] = 110015,
        [ "name" ] = "布鲁诺家族",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110016 ] = {
        [ "ch_key" ] = "旗帜16",
        [ "default_anim" ] = "jzbp_04",
        [ "id" ] = 110016,
        [ "name" ] = "克里亚家族",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110017 ] = {
        [ "ch_key" ] = "旗帜17",
        [ "default_anim" ] = "jzbp_05",
        [ "id" ] = 110017,
        [ "name" ] = "科拉迪家族",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110018 ] = {
        [ "ch_key" ] = "旗帜18",
        [ "default_anim" ] = "jzbp_06",
        [ "id" ] = 110018,
        [ "name" ] = "死兆会",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110019 ] = {
        [ "ch_key" ] = "旗帜19",
        [ "default_anim" ] = "wfjt_01",
        [ "id" ] = 110019,
        [ "name" ] = "ZERO贸易集团",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110020 ] = {
        [ "ch_key" ] = "旗帜20",
        [ "default_anim" ] = "wfjt_02",
        [ "id" ] = 110020,
        [ "name" ] = "D24雇佣兵",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110021 ] = {
        [ "ch_key" ] = "旗帜21",
        [ "default_anim" ] = "wfjt_03",
        [ "id" ] = 110021,
        [ "name" ] = "罗伯特财团",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110022 ] = {
        [ "ch_key" ] = "旗帜22",
        [ "default_anim" ] = "wfjt_04",
        [ "id" ] = 110022,
        [ "name" ] = "Free heaven娱乐集团",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110023 ] = {
        [ "ch_key" ] = "旗帜23",
        [ "default_anim" ] = "wfjt_05",
        [ "id" ] = 110023,
        [ "name" ] = "Ranger雇佣兵",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110024 ] = {
        [ "ch_key" ] = "旗帜24",
        [ "default_anim" ] = "wfjt_06",
        [ "id" ] = 110024,
        [ "name" ] = "DOL犯罪集团",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110025 ] = {
        [ "ch_key" ] = "旗帜25",
        [ "default_anim" ] = "wjxz_01",
        [ "id" ] = 110025,
        [ "name" ] = "玩家自选1",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110026 ] = {
        [ "ch_key" ] = "旗帜26",
        [ "default_anim" ] = "wjxz_02",
        [ "id" ] = 110026,
        [ "name" ] = "玩家自选2",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110027 ] = {
        [ "ch_key" ] = "旗帜27",
        [ "default_anim" ] = "wjxz_03",
        [ "id" ] = 110027,
        [ "name" ] = "玩家自选3",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110028 ] = {
        [ "ch_key" ] = "旗帜28",
        [ "default_anim" ] = "wjxz_04",
        [ "id" ] = 110028,
        [ "name" ] = "玩家自选4",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110029 ] = {
        [ "ch_key" ] = "旗帜29",
        [ "default_anim" ] = "wjxz_05",
        [ "id" ] = 110029,
        [ "name" ] = "玩家自选5",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 110030 ] = {
        [ "ch_key" ] = "旗帜30",
        [ "default_anim" ] = "wjxz_06",
        [ "id" ] = 110030,
        [ "name" ] = "玩家自选6",
        [ "res_path" ] = "Unit/Other/Flag/CityFlag",
    },
    [ 1000010 ] = {
        [ "ch_key" ] = "敌人士兵1",
        [ "default_anim" ] = "zhengmian_idle",
        [ "id" ] = 1000010,
        [ "name" ] = "敌人士兵1",
        [ "res_path" ] = "Unit/Soldier/soldier_nanjiqiangbing/nanjiqiangbing_pb",
        [ "unit_scale" ] = 1,
    },
    [ 1000011 ] = {
        [ "ch_key" ] = "敌人士兵2",
        [ "default_anim" ] = "zhengmian_idle",
        [ "id" ] = 1000011,
        [ "name" ] = "敌人士兵2",
        [ "res_path" ] = "Unit/Soldier/soldier_nanshouqiangbing1/nanshouqiangbing_pb",
        [ "unit_scale" ] = 1,
    },
    [ 1000012 ] = {
        [ "ch_key" ] = "敌人士兵3",
        [ "default_anim" ] = "zhengmian_idle",
        [ "id" ] = 1000012,
        [ "name" ] = "敌人士兵3",
        [ "res_path" ] = "Unit/Soldier/soldier_nanshouqiangbing2/nanshouqiangbing2_pb",
        [ "unit_scale" ] = 1,
    },
    [ 1000013 ] = {
        [ "ch_key" ] = "敌人士兵4",
        [ "default_anim" ] = "zhengmian_idle",
        [ "id" ] = 1000013,
        [ "name" ] = "敌人士兵4",
        [ "res_path" ] = "Unit/Soldier/soldier_zhandouxiaobing__zhengmian/motuozheng_pb",
        [ "unit_scale" ] = 1,
    },
}